# Gaming Toxicity Detection

**Authors:** Beibarys Nyussupov, Ruby Ngo, Paola Calle, Jett Forward

In [1]:
# libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path 
import re 
import sys
sys.path.insert(0, str(Path("../..").resolve()))

# custom functions - tokenizer, step evaluator
from src.tokenizer import tokenize
from src.prep_evaluation_multi import eval_step

# reproducibility
seed = 7524
np.random.seed(seed)

# project root (notebooks/gaming/ - notebooks/ - project root)
PROJECT_ROOT = Path().resolve().parent.parent

In [2]:
# data directories
DATA_DIR_WOT  = PROJECT_ROOT / "data/raw_data/wot/"
DATA_DIR_DOTA = PROJECT_ROOT / "data/raw_data/dota/"

## World of Tanks

**World of Tanks**
| Class | Terminology |
|---|---|
| 0 | Non-Toxic |
| 1 | Insults and Flaming |
| 2 | Other Offensive Texts |
| 3 | Hate and Harassment |
| 4 | Threats |
| 5 | Extremism |

#### Inspect each split

In [3]:
# import data 
train = pd.read_csv(DATA_DIR_WOT / "train.csv")
val = pd.read_csv(DATA_DIR_WOT / "val.csv")

# test dataset 
test_text = pd.read_csv(DATA_DIR_WOT /  "test_index_text.csv")
test_label = pd.read_csv(DATA_DIR_WOT / "test_index_label.csv")

# check the data 
for name, df in [("train", train), ("val", val), ("test_text", test_text), ("test_label", test_label)]:
    print(f"--- {name} ---")
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print(f"First few rows of the dataset:\n{df.head(3)}")
    print()

--- train ---
Shape: (42959, 3)
Columns: ['index', 'message', 'label']
First few rows of the dataset:
   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0

--- val ---
Shape: (5367, 3)
Columns: ['index', 'message', 'label']
First few rows of the dataset:
   index       message  label
0  31697  e50 is there    0.0
1  52311   this scouts    0.0
2   2775       i guess    0.0

--- test_text ---
Shape: (5375, 2)
Columns: ['index', 'message']
First few rows of the dataset:
   index         message
0  17775  aim you monkey
1  28228   Pz kill artys
2  19888             ggs

--- test_label ---
Shape: (5375, 2)
Columns: ['index', 'label']
First few rows of the dataset:
   index  label
0  17775    2.0
1  28228    0.0
2  19888    0.0

The test set is stored in two separate files - text and labels indexed by the same `index` column. Train and val are already complete. We need to join the test files on `index` before merging everything.

#### Reconstruct test split and merge all

In [4]:
# merge test text and labels
test = test_text.merge(test_label, on="index", how="inner")

# concatenate all data
wot = pd.concat([train, val, test], ignore_index=True)

print(f"Test join shape: {test.shape}\n")
print(f"Merged shape: {wot.shape}\n")
print(f"First few rows of the data:\n{wot.head(3)}\n")
print(f"Information about the data: {wot.info()}")

Test join shape: (5375, 3)

Merged shape: (53701, 3)

First few rows of the data:
   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53701 entries, 0 to 53700
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    53701 non-null  int64
 1   message  53701 non-null  object
 2   label    53701 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ MB
Information about the data: None

The test join uses `inner` - any index present in only one file would be silently dropped. If test shape after join is smaller than either file's length, there is an alignment issue in the original data.

In [5]:
# to test improvement or degradation after each preprocessing step, 
# we export the data as raw parquet and compare score of predictions of raw vs processed data. 
wot.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

# baseline — before any cleaning
preprocessing_impact = eval_step("baseline_raw", datasets = ("WoT",))

        step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
baseline_raw     WoT 53701    0.4765       0.8608         0.553           0.4586             0.0           0.0              0.0

#### Non-english language

Since we are going to model classifier on english data, it is important for us to detect non-english cases as many as we can.

In [6]:
# detecting Non-lating language first

# covers all major non-Latin scripts
NON_LATIN_SCRIPT = re.compile(
    r"[\u0400-\u04FF"   # Cyrillic
    r"\u4E00-\u9FFF"    # CJK unified ideographs
    r"\u3400-\u4DBF"    # CJK extension A
    r"\uF900-\uFAFF"    # CJK compatibility ideographs
    r"\u0600-\u06FF"    # Arabic
    r"\u0590-\u05FF"    # Hebrew
    r"\u3040-\u30FF"    # Japanese (Hiragana + Katakana)
    r"\uAC00-\uD7AF"    # Korean (Hangul syllables)
    r"\u1100-\u11FF"    # Korean (Hangul Jamo)
    r"\u0E00-\u0E7F"    # Thai
    r"\u0900-\u097F"    # Devanagari (Hindi)
    r"\u0980-\u09FF"    # Bengali
    r"\u0370-\u03FF"    # Greek
    r"\u10A0-\u10FF"    # Georgian
    r"\u0530-\u058F"    # Armenian
    r"\u1000-\u109F"    # Myanmar
    r"\u1780-\u17FF]"   # Khmer
)

# drop any message containing even 1 non-Latin script char
print(f"Non-english documents:\n{wot[wot['message'].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)}\n")

# changes 
before = len(wot)
wot_en = wot[~wot["message"].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)
print(f"Dropped {before - len(wot_en)} ({(before - len(wot_en))/before:.1%})")
print(f"Rows after the drop: {wot_en.shape[0]}")
# save new step again
wot_en.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

Non-english documents:
      index                message  label
0     13087          ще злийте )))    1.0
1     31917       перший бій, сток    0.0
2     40395                ФОКУСЯТ    0.0
3     54412  елка спасибо тебе ...    0.0
4      5457                 уроди!    0.0
...     ...                    ...    ...
3845   5453                 я кину    0.0
3846   5456                светите    0.0
3847  13081       в чём притензия?    0.0
3848   7331      вот и подкруточки    0.0
3849  50128  тут танки стоят уебак    0.0

[3850 rows x 3 columns]

Dropped 3850 (7.2%)
Rows after the drop: 49851

In [7]:
# check non-latin language drop
preprocessing_impact = eval_step("after_nonlatin_drop", preprocessing_impact, datasets="WoT")
preprocessing_impact

               step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_nonlatin_drop     WoT 49851    0.4946       0.8679        0.5919           0.4756          0.0181        0.0389            0.017

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.017

In [8]:
from lingua import Language, LanguageDetectorBuilder

# detector to find latin but non-english documents 
detector = (LanguageDetectorBuilder 
    # detect all other languages using latin
    .from_all_languages_with_latin_script()
    # if top-2 languages are within 25% confidence of each other - do not drop 
    .with_minimum_relative_distance(0.25)
    .build())

# function to detect such documents 
def is_latin_non_english(text):
    if len(str(text).strip()) < 30:
        return False  # too short - keep
    lang = detector.detect_language_of(str(text))
    return lang is not None and lang != Language.ENGLISH

# such documents 
mask = wot_en["message"].apply(is_latin_non_english)
with pd.option_context("display.max_rows", 800):
    print(f"Non-english documents:\n{wot_en[mask]}\n")
    print(f"How many documents with non-english text:{wot_en[mask].shape[0]}")

Non-english documents:
       index                                            message  label
364    14038                    Menj már nemm kapsz spotot.....    0.0
494    29761          no ayudaste a nadie shptk ahora no llores    1.0
573     7353                  3 dingi od pierdolonych papier??w    2.0
683    35518                Etwas Hilfe bei D4 wäre schon nett!    0.0
778     6397        Hilfe! Ich werde gleich auf A3 verpr??gelt!    0.0
907     6395        Hilfe! Ich werde gleich auf C1 verpr??gelt!    0.0
957     1934  jeszcze t54 zespotowany byl wczesniej wiec wid...    0.0
1109    7645                     how many dmg arty? 2k? XDDDDDD    0.0
1110   51836                   LOSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS    0.0
1184    1984                   5x ep... mehr muss man net sagen    0.0
1373    6449  Hali! A MAATT kl??n akt??v j??t??kosokat keres...    0.0
1425   30904                  ooo polaczek, no jakby inaczej XD    0.0
1527    5943  tu ecris ce que tu veux, dans la mesure du cor...    0.0
1695   26683  Den Sinn von Funk erkannt, aber kein TS? Nutz ...    0.0
2002   33391  ich checkls nicht seit wann lässst man diese s...    3.0
2032   44040                Kann mir wer bei C2 zur Hand gehen!    0.0
2120    3989     amikor arrol e helyr??l m??r el is mozdultam..    0.0
3070   51396  Aufgeklärt bei Position E3. Etwas Hilfe währe ...    0.0
3198   21011  aahahhahahahsahahsahsyhsahnahsedbnfsdsbnfsfssh...    0.0
3380   24140            sry ulozim si replay a mozme pokracovat    0.0
3649   31989  Danke Type das ich deinen Job gemacht habe... ...    1.0
3704   49558  no wlasnie stojac za mna gdzie ja trzymalem po...    0.0
3709   44045                  Du siehst mich, Ich seh Dich! F2!    0.0
3788   32334                     HAHAHAAAAAA:::NEXT KINDER TEAM    1.0
4018   51394  Aufgeklärt bei Position D3. Etwas Hilfe währe ...    0.0
4061    2261  Les fr??res d'armes [L_F_A] recrutent.Clan fra...    0.0
4188   51835  FASZYSTOWSKIE ŚWINIE WOTOWSKA WAGNEROWSKA BAND...    5.0
4948   33305                     ihr seid so schlecht ihr wixxa    1.0
5075   11094  meine sch??sse prallen ab und ich platze nach ...    0.0
5100   47390                Etwas Hilfe bei E7 wäre schon nett!    0.0
5176   10263   tylko is-3a jest dobry reszta to jebane ??cierwo    1.0
5438   27984                    ich schmeiß dir die Brügel raus    1.0
5449   47483  3k damage für die katz weil unser team verkack...    2.0
5687   17614  shut up froschschenkelfresser oder laber in en...    1.0
6023    9386   gggggggggggggggggggggggggggggggggggggggggggggggg    0.0
6084   14709   szerinted rosszabb lesz ez mint a tog vagy jobb?    0.0
6227   13269  Wir die Grizzly's suchen noch aktive deutsche ...    0.0
6449   54201  FFFFFFFFFFFFUUUUUUUUUCKING ARTYYYYYYYYYYYYYYYY...    1.0
6553   46888               progetto are you ******* ***********    0.0
6597   52151  und die 6 camper kraulen sich wie immer die ei...    1.0
6724   50811          össze vissza vagyok borúlva tess sgítssss    0.0
6739   35299                Etwas Hilfe bei H5 wäre schon nett!    0.0
6845   13862  protože jsem dostával do neviditelnýho gsoru a...    0.0
6937    1985                    bananen gibts nur f??r nen sieg    3.0
6950   30955                 nie pisz do mnie po rusku ty kurwo    3.0
7004   48113  scheiss camper idioten löscht das game und geh...    1.0
7032    2530      nigerians are anglaise colonie...non francais    0.0
7156   10262                 a my kurwa takie boty mamy ze szok    2.0
7240   30166  Die Puma Community ist nun soweit auch den 2. ...    0.0
7290   33481            report chojowi smacie na warapcku is wg    1.0
7840   24719  nevím jak můžete hrát tuto hru tak pojebaně vy...    1.0
7858   38487                  e 100 wycofaj bo mi kamo ściągasz    0.0
7912   35519                Etwas Hilfe bei E3 wäre schon nett!    0.0
8155    1662  waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...    0.0
8292   26049  stul pysk, durniu, naotwartej mapie wystawiasz...    1.0
8438   18360  Szukasz klanu ? Zapraszamy do -AP- Po więcej i...    0.0
8449   33078       Viel Glück an alle! (Good luck to everyone!)    0.0
8613   39783                  bewegt euch doch mal ein bisschen    0.0
8617    6011                    Lippu haltuun k??mpp??ys loppuu    0.0
8775   32266   Kann es sein das ich Dumm bin oder so, bin offen    1.0
8804   14361  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...    0.0
9037   51745                   od mojej strony jedzie kv4 uwaga    0.0
9349   27972  twoja stara ma parkinsona e tak sie bujasz tym...    1.0
9652   33524  nur wixxer in die dreck können und nicht aufra...    0.0
9678   11782  ach, zdalne... pamiętam zdalną sesję na uczeln...    0.0
9760   52848  mindenre alkalmatlan volt az angolok ingyen ad...    0.0
10069  49554                popłacz tam sie kurwa jeszcze hahaa    2.0
10127  43747  mit so einem Team geht man auch gerne durch di...    2.0
10856  34731            WWWWWWWWWDWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    0.0
10859  41748                  una scimmia mi ha spottato in D7!    0.0
10942  51731  deszcze nie spokojne potargaly sad a ja musze ...    0.0
11339  39375      ez game ez win T95 bedzie jechało pyr pyr pyr    0.0
11948  10515  leckt mich doch am ar... nutzt irgendwer die k...    0.0
12159  44031                  Du siehst mich, Ich seh Dich! D2!    0.0
12432  35005  zawsze w lato pod dyskoteką ze straganem stoi pan    0.0
12473  44041                Kann mir wer bei C2 zur Hand gehen!    0.0
12709  35520                Etwas Hilfe bei F3 wäre schon nett!    0.0
12867  17615  jawohl herr hauptman , eat wurst and kartofeln...    3.0
12897  47391                Etwas Hilfe bei F7 wäre schon nett!    0.0
12945  32888                 JOO TÄMÄ KÄÄNTYY JÄRKEVÄN NOPEASTI    0.0
13231  53297                    tol je tak složitý použít mozek    1.0
13434  31829  ich liebe es wie wot einen nur noch verarscht ...    1.0
13517   3357  man muss hier nur ein Jude, Kommunist, Slave, ...    3.0
13710  18631  hp vida solo no tenian que dejarlo pasar inutiles    0.0
13848  49550  no nie twoja bo ja chujowo podjechalem ale poz...    0.0
14095  49557  ja pierdole jak sa tacy gracze jak ty to sredn...    1.0
14535  11788      obecnie piszę pracę dyplomową, w lutym obrona    0.0
14686  51824    bedziesz kurwa morde zacieszal za 2 godziny max    0.0
15136  12179  usta ben 60tp kasıyorum 8 seviyedeyim 9u alınc...    1.0
15200   8115                  Du siehst mich, Ich seh Dich! E3!    0.0
15235  45286  Du reportest die Gegner ungerne alleine oder f...    0.0
15305  49542  ten jeo kolega gra lepiej od Ciebie i nie wpie...    0.0
15552  21946        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa    0.0
15795  37767  bráško gratuluju... menší throw teď ke konci.....    0.0
15938  51891  meinst du jetzt chess algeimein oder den clan ...    0.0
16112  18552                kurwa chuje nie gioncie jak wszmaty    1.0
16402  54627  Szia! Épp streamelek twitchen,ugorj be, örömme...    0.0
16570   7732                   ten ji-ro to jaki?? nowy czo??g?    0.0
16602  49545  a nie moja wina ze mnie pchasz zeby w arte trs...    0.0
17013  27800  nyomornc rtetkes kurva anyátok remélem már meg...    1.0
17015  20645                 skąd masz taki zajebisty rower co?    0.0
17222   4091  abi 10 el oynad??m bu kadar ??erefsiz bir oyun...    0.0
17426  12290           kolejna lanie ale to normalka w wocie :)    0.0
17608  33462  nee, wird ja immer schlimmer mit den Luschen d...    1.0
17687  13088                NAHUI POSHLA HUESOSKA BLEA IOBANAEA    2.0
17722   6536                     i kurwa nastepne zjebane cioty    0.0
17725   1943         JA BYM ICH POZABIJAL ALE SAM NIC NIEZROBIE    0.0
17987  30916                   dobra, dziękuję ci za rady XDDDD    0.0
18235  20915         HHHHHHHHHHHHEEEEEEEEEEEEEEEYYYYYYYYYYYYYYY    0.0
19084  20641        dzieki takim debilom przegrywa cala druzyna    1.0
19156   6450  aaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww...    0.0
19194  27962                  zamknij morde jebany rski smieciu    1.0
19219  38953  die wünsche ich dir auch, dann hörst vielleich...    0.0
19267  49549             popłacz sie najlepiej i idz do mamusie    2.0
19477  18936   unfassbar sieben Gefecht davon Sechs mal LOWTIER    0.0
19926  35514                Etwas Hilfe bei C7 wäre schon nett!    0.0
20079   6398        Hilfe! Ich werde gleich auf A3 verpr??gelt!    0.0
20241   4092                  hep mi mallar bize denk gelir amk    0.0
20287  16898  siema opłaca sie dokupic stabe bo mam dosyłacz...    0.0
20326  36686                   sam se musze podświetlać masakra    0.0
20329  41746                  una scimmia mi ha spottato in G1!    0.0
20389  32265   Kann es sein das ich Dumm bin oder so, bin offen    1.0
20479  33379                ihr dreckigen schweine kanaken pack    1.0
20538  14714  ha zavar az 1es tier akkor mehetünk tier 8 ha ...    0.0
20850  43257                  Emil...bist du ein bisschen dumm?    2.0
20918  44034                  Du siehst mich, Ich seh Dich! D2!    0.0
21105  47397                Etwas Hilfe bei K0 wäre schon nett!    0.0
21186  27140              gleich raus mit solchen Schwachköpfen    1.0
21230  17234  son una mierda, tengo que defender porque casi...    1.0
21352  51400  Aufgeklärt bei Position F1. Etwas Hilfe währe ...    0.0
21641  30446  qrwa flanki nie potrafia obstawic pierdolone gady    1.0
22109   7878  za pocetak samo da jebem mater svi ljudima sto...    2.0
22232  35516                Etwas Hilfe bei B5 wäre schon nett!    0.0
22261  16518    emil yerime geçersen sana boru anahtarı sokarım    0.0
22274  50186  Nowo powstały klan NIPL rekrutacja otwarta,zer...    0.0
22290   4037    EinfachSmon (IS-4), you are blocking my target!    0.0
22385  30917   jak wy to kurwa wygracie to ja pierdolnę fikołka    1.0
22432  30299  KEWNFKJNkwjsnfeijnijwNKBFBwebbubgvgvvvgvvyvuvV...    0.0
22659  26349  sag mal du dämlicher scout idiot?? Schießt du ...    1.0
22742  41745                  una scimmia mi ha spottato in G1!    0.0
22986  49541  niech ten twoj kolega naiuczy sie grac kołowec...    0.0
23056  51393  Aufgeklärt bei Position D3. Etwas Hilfe währe ...    0.0
23212  41749                  una scimmia mi ha spottato in B5!    0.0
23327   7354       od lajta i kurwa 2 boki ci????kich czo??g??w    1.0
23865   3988             kil??ttem r?? 5 m??sodpercre ki l??...    0.0
23898  11787  na polibudzie sobie nie poradziłem na drugim r...    0.0
24014  26247                  ein freundliches Hallo an alle...    0.0
24182  51398  Aufgeklärt bei Position F2. Etwas Hilfe währe ...    0.0
24245   6396        Hilfe! Ich werde gleich auf B1 verpr??gelt!    0.0
24628  14715                    rontja a statot a kicsi tier :D    0.0
24859  25111  Tros_winner (Mäuschen), you‘re blocking my lin...    0.0
24923  14793  Salut,clanul GLADIATORII asteapta jucatori,cin...    0.0
24992  11792  ja to jeszcze 4 kalsa szkoly zostala ale w mak...    0.0
25018  49556  nie blokowałem aby sie zatrzymałem i stałem w ...    0.0
25050  15570            regler en defaite par le serveur nul :(    0.0
25184  52723               tyy głupi huju 703 wypierdalaj nobie    3.0
25614  17612  mais c'est reparti l'arty sur wot , ils ont fa...    0.0
25716  33711                 gg keiner fährt rechts ihr idioten    1.0
25877  16345         Hilfe! ich werde auf J4 gleich verprügelt!    0.0
25906  30035    gorev vari ne guzel oluru burda yalan oldu yine    0.0
26211  15798    WEHATSPOŐ JEDjipoáőtegijpkolnőémádhgéjkonmsfmál    0.0
26371   2525                 flanc l'ouest camarade communistes    3.0
26632  46683              reıs burdaydılar en son bana sıkarken    0.0
26770  16346         Hilfe! ich werde auf J4 gleich verprügelt!    0.0
26771  38482  kurwa kocham ta gre 80% pierwszych bitew arta ...    0.0
26920  31168                     e wezma cie do lepszego klanu?    0.0
27059  11095       deshalb gaaanz hinten bleiben oder versenken    0.0
27149  17601                    go og ogogo go og ogo go go ooo    0.0
27163  32916  ruszki681212 (05.05.2023 0:51:45) kurd meg a r...    3.0
27450   8550                 fressed vesela ihre schuhe rotwein    0.0
27550  38510           l2p schweinepanzer 2 und rucksacktourist    0.0
27895   2402               Ja grindivaunu, ei parasta tykki??..    0.0
27910   5167              asdfjkoa seughfiuagfeiuygaseiyuafweg]    0.0
28000   9546        Hilfe! Ich werde gleich auf C4 verpr??gelt!    0.0
28201  51392  Aufgeklärt bei Position C3. Etwas Hilfe währe ...    0.0
28211  18165         senin gibi oruspu cocuklari yuzunden oldum    1.0
28424  35517                Etwas Hilfe bei C4 wäre schon nett!    0.0
28493  18287         nicht gut abschilessen &gt;&lt; roflkopter    0.0
28536  35278  herrlich gibnt es heute nur 10e matche für mic...    0.0
29110  35521                Etwas Hilfe bei F2 wäre schon nett!    0.0
29157  51401  Aufgeklärt bei Position G2. Etwas Hilfe währe ...    0.0
29669  32264   Kann es sein das ich Dumm bin oder so, bin offen    1.0
29965  46074                     alter was seid ihr fürn haufen    1.0
30421  31777          e25 unser held :) echt gut gespielt junge    0.0
30674  35345    skurwielcu jebany znojda cie w realu i rozjebia    0.0
30701  14716                     szerintem pont hogy nem rontja    0.0
30848  47202  WY KURWY JEABane slepe mam nadzieje ze kruwa k...    0.0
31669  23994              az artiknak ti lesztek a kedvencei :D    0.0
31890  47398                Etwas Hilfe bei J0 wäre schon nett!    0.0
32003  45849            rusz ta pizde kurwa is potuj szmaciarzu    1.0
32142   6392        Hilfe! Ich werde gleich auf J7 verpr??gelt!    0.0
32148  39206  artyyyyyyyyyyyyyyyyyyyyyyyyyyyy!!!!!!!!!!!!!!!...    0.0
32226   9538        Hilfe! Ich werde gleich auf G1 verpr??gelt!    0.0
32534  49560               ale kij z tym powodzenia w nastepnym    0.0
32584  27968  wr a co to kurwa jest niedojebany kacapski obc...    3.0
32697  19125                    kiedy masz takie kurwy nie myte    3.0
32721   8114                  Du siehst mich, Ich seh Dich! D3!    0.0
32835  53243  Bonjour ! Clan Fr. Nous recrutons&quot;AV424-L...    0.0
33231  17216  fast alle auf einer Seite kann nicht funktioni...    0.0
33373  51402  Aufgeklärt bei Position H1. Etwas Hilfe währe ...    0.0
33378  33626             full life mäusschen.. MOVE YOUR ASS!!!    1.0
33456   1137  FR ROCK recrute francophones, voir conditions ...    0.0
33832  51399  Aufgeklärt bei Position F2. Etwas Hilfe währe ...    0.0
33851  20639  pierdolona cioto z ciezkiego w warcabi idz gra...    1.0
34077   4904             Das hab ich so uch npoch nicht gesehen    0.0
34565   2541                     except our communiste espagnol    3.0
34794   9535        Hilfe! Ich werde gleich auf G1 verpr??gelt!    0.0
35267  41269                   Heilige Einfachheit, bewege dich    0.0
35317  19986      jak cos do mnie mowisz to wyjmij chuja z buzi    1.0
35627   5483     man zieh den finger aus deinem arsch und fahre    1.0
35655  16257  wer sich schon joergimaus nennt... ab zum CSD ...    0.0
36156   2485             ihr arschgefickten dummen schei?? bots    1.0
36197  27969  majac takich graczy jak ty to i ma sie takie z...    3.0
36774  10942  POOOOUHHHHHHHHHHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAA...    0.0
36915  54186  salaklar arkanızda ben varım amk malları biraz...    0.0
36976  36277     há mennyi megmondó ember van itt is hihetetlen    0.0
37230   9542        Hilfe! Ich werde gleich auf E1 verpr??gelt!    0.0
37286   4239  no kurwa jebana, nie mia??o jakiej mapy poloso...    0.0
37594  11645       nie do???? ??e pizda na topie to jescze zjeb    1.0
38064  33298                   tepe kurwy ruchane w dupe szmaty    3.0
39155  44044                Kann mir wer bei C2 zur Hand gehen!    0.0
39222  30168  Die Puma Community ist nun soweit auch den 2. ...    0.0
39268  27964  twoj stary debil ze sie nie spuscil na kupe la...    3.0
39494   4105     sah dannach aus als w??rdest du hilfe brauchen    0.0
39573   2202  ja rozumie byc slabym graczem ale zeby miec 20...    0.0
39769   8120                  Du siehst mich, Ich seh Dich! F2!    0.0
39788  30905                  a ty to kurwa kto? Książe persji?    3.0
39835  52847  agyonbaszott buffolt szartartály mattilda a va...    2.0
39860   5518  rsdvsdrzhsdtubdtfujbdtfbjsdtjdrtjbdrtjdrbrtfuj...    0.0
39935   6394        Hilfe! Ich werde gleich auf C1 verpr??gelt!    0.0
40113  44029                Kann mir wer bei C2 zur Hand gehen!    0.0
40150  11793  mam już pracę stałą. Od ręki mnie zatrudnili z...    0.0
40190  14208                 hát ez nem igazán sikerült barátom    0.0
40192  47395                Etwas Hilfe bei K0 wäre schon nett!    0.0
40235  25883  GG GUYS HIDE HARXDER ;L.OKLKLIKOOLLKOOLLOOLOKK...    0.0
40413  33319      ei tuu mittää tästä hommasta tälläi selvinpäi    1.0
40539  33510             ihr arschgefickten dummnen scheiß bots    1.0
40806  12326            schon wieder zuviele hohlkörper im team    0.0
41263  28551              EN NATUURLIJK TARGETARTY MIJ WEER GVD    0.0
41352  30906             przyjechales pchac pizde i sie prujesz    1.0
41445  30914  a jak jestes slepy i nie widzisz jak sie na ko...    1.0
41460  44032                Kann mir wer bei C3 zur Hand gehen!    0.0
41501  47394                Etwas Hilfe bei K8 wäre schon nett!    0.0
41606  11797                no ładny, lecz pisownię ma powaloną    0.0
41611  32263   Kann es sein das ich Dumm bin oder so, bin offen    1.0
41776  32823    a jak niewiadomo o co chodzi to chodzi o kutasa    1.0
42014   2400  eka t???? oma samanlainen vaunu puski tohon sa...    0.0
42416  51391  Aufgeklärt bei Position C3. Etwas Hilfe währe ...    0.0
42454  51736           odbic to ci moge buta na ryju jak chcesz    2.0
42464  48002                   alles nur noch clowns am spielen    0.0
42897  48981  MOCSKOSALJASFÉREGFASSZOPÓPATKÁNYCSICSKAKÖCSÖGB...    3.0
42915  44047                  Du siehst mich, Ich seh Dich! G3!    0.0
42970  11447  ja spierdalam na kolacje bede afk grajcie z 5 ...    0.0
43036  12293                  takie cuda tylko w wocie hahaha:)    0.0
43080  18285  na die bringen dem team wenigstens mehr liebe ...    0.0
43302  28370  Wer Lust auf einen Clan hat, kann mich nach de...    0.0
43331  16348         Hilfe! ich werde auf J4 gleich verprügelt!    0.0
43925  43957  killyourself scheiss hurensöhne enrstahft kill...    4.0
43980  16352         Hilfe! ich werde auf E3 gleich verprügelt!    0.0
43995  16355         Hilfe! ich werde auf B7 gleich verprügelt!    0.0
44450  34680                junge unterstüzung und nicht campen    0.0
44464   7701  was f??r deppen auf meiner seite warum lasst i...    0.0
44500  38380  VerteidiGER5 (KV-1SA), you are blocking my tar...    0.0
44658  44036                  Du siehst mich, Ich seh Dich! D2!    0.0
45052  32262   Kann es sein das ich Dumm bin oder so, bin offen    1.0
45508   8116                  Du siehst mich, Ich seh Dich! E3!    0.0
45583  43247  ich weiss nicht wie man sich so dumm aufteilen...    2.0
45804   8410           no chlopie na tej arcie robisz robote :D    0.0
45827   8732             dont expect a super unicum to auto aim    0.0
45897  18161                   amina kodugumun oruspu çocuklari    2.0
46000  33791         und wieder ein dämliches Arschlochteam !!!    1.0
46061  21141  GRILLLE CROOOSOOSOSOSOSOS ANNDND YOOUUUUU SSLL...    1.0
46085  35515                Etwas Hilfe bei B6 wäre schon nett!    0.0
46255  10881  mit solchen spielern wie euch,blamiert man sic...    0.0
46296   6988                jajajaj estamos tiudos de este lado    0.0
46998  36833  sympa les bataille de samedi soir, sur le twit...    0.0
47097   9539        Hilfe! Ich werde gleich auf G1 verpr??gelt!    0.0
47229  16354         Hilfe! ich werde auf C3 gleich verprügelt!    0.0
47275  44575     reportarlo? jajaja que done los organos jajaja    0.0
47327  28549  Dit is trouwens waarom ik nooit anders dan ran...    0.0

Only 294 rows. Let's drop that as well.

In [9]:
# dataset update
wot_en = wot_en[~mask].reset_index(drop = True)
# length after the drop 
print(f"Length after the drop:{wot_en.shape[0]}")
wot_en.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

Length after the drop:49557

In [10]:
# evaluate impact 
preprocessing_impact = eval_step("after_noneng_drop", preprocessing_impact, datasets = ("WoT",))
preprocessing_impact

             step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_noneng_drop     WoT 49557     0.503       0.8681        0.6037           0.4862          0.0084        0.0118           0.0106

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106

#### Duplicates

In [11]:
# look at dataset with duplicates 
wot_dup = wot_en[wot_en.duplicated(subset="message", keep=False)].sort_values("message")
# look at some examples
wot_dup.head(10)

       index  message  label
14174  31613        !    0.0
43460  40582        !    0.0
39717   6872        !    0.0
45444   1278     !!!!    0.0
33323  32907     !!!!    0.0
27555  39948     !!!!    0.0
11512   8848        #    0.0
9424   16596        #    0.0
33920  18520  #ERROR!    0.0
13678   3574  #ERROR!    0.0

In [12]:
# top 100 duplicated messages
wot_dup["message"].value_counts(ascending=False).head(100)

message
gg                   3188
lol                   458
nice                  396
gj                    315
wtf                   201
                     ...
fu                     26
leo                    26
??                     26
ggg                    26
Im Spotted at G2!      26
Name: count, Length: 100, dtype: int64

Most of these duplicates are useful and important data to train or models for detecting toxicity. We need to check for same messages but different labels.

In [13]:
# Look for duplicates with same messages but different labels
conflicts = wot_en.groupby("message")["label"].nunique()
conflicts = conflicts[conflicts > 1]

conflict_rows = wot_en[wot_en["message"].isin(conflicts.index)].sort_values("message")

# Check how large is the proportion of conflicting duplicates
conflict_pct = len(conflict_rows) / len(wot_en) * 100
print(f"Proportion of messages with conflicting labels: {conflict_pct:.2f}%")
print(f"Number of messages with conflicting labels: {len(conflict_rows)}")

Proportion of messages with conflicting labels: 14.73%
Number of messages with conflicting labels: 7298

In [14]:
# check conflicting rows 
conflict_rows

       index                      message  label
44073  24318                      #ERROR!    0.0
10225  19840                      #ERROR!    0.0
31944  13407                      #ERROR!    0.0
36805  14302                      #ERROR!    0.0
42297  14881                      #ERROR!    0.0
...      ...                          ...    ...
21121  44232                     you lost    2.0
21022  13279                     you lost    1.0
45626  17220                     you lost    0.0
5404    1393  you wanna loose that right?    1.0
27959   9108  you wanna loose that right?    2.0

[7298 rows x 3 columns]

These messages can not be used for analysis, since it is a problem of `annotation`. Using them will be equal to guessing. Duplicated rows account for 14% of the data, which is a huge loss but we can not use that.

In [15]:
# drop conflicting messages
wot_dup = wot_en[~wot_en["message"].isin(conflicts.index)].reset_index(drop=True)
print(wot_dup.shape)

(42259, 3)

In [16]:
# save again and evaluate 
wot_dup.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)
preprocessing_impact = eval_step("after_duplicates_removal", preprocessing_impact, datasets = ("WoT",))

                    step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_duplicates_removal     WoT 42259    0.4692       0.8671        0.5551           0.4631         -0.0338       -0.0486          -0.0231

In [17]:
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231

This did not work, our score started decreasing. Instead of dropping duplicated conflicting labels, we assign a majority label to each.

In [18]:
# majority label for similar words 
majority_label = wot_en.groupby("message")["label"].agg(lambda x: x.value_counts().index[0])

# drop duplicates and map majority label 
wot_deduped = wot_en.copy()
wot_deduped["label"] = wot_deduped["message"].map(majority_label)

# check same ex duplicates 
wot_deduped[wot_deduped["message"].isin(conflicts.index)][["message", "label"]].head(20)

               message  label
4                  lol    0.0
11             #ERROR!    0.0
18                 bot    1.0
23              retard    1.0
46   Im Spotted at H6!    0.0
47                  ty    0.0
53                  ns    0.0
62                 wtf    2.0
64             #ERROR!    0.0
85              idiots    1.0
86           holy shit    0.0
89            eat shit    2.0
92           game over    2.0
96                  gg    0.0
98                  :(    0.0
108                 gg    0.0
116                 gg    0.0
120                 gg    0.0
126                 gg    0.0
127                 gg    0.0

In [19]:
# save again and evaluate 
wot_deduped.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)
preprocessing_impact = eval_step("after_duplicates_majority_map", preprocessing_impact, datasets = ("WoT",))
preprocessing_impact

                         step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_duplicates_majority_map     WoT 49557    0.5211        0.877        0.6204           0.5036          0.0519        0.0653           0.0405

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405

That is the best we can do and it actually improves the score.

#### Data Artifacts

In [20]:
# #ERROR! entries
error_count = wot_deduped["message"].str.contains(r"#ERROR!", regex=False, na=False).sum()
print(f"#ERROR! messages: {error_count}")

# HTML entities
html_mask = wot_deduped["message"].str.contains(r"&\w+;", regex=True, na=False)
print(f"Messages with HTML entities: {html_mask.sum()}")
wot_deduped[html_mask][["message", "label"]].head(10)

#ERROR! messages: 171
Messages with HTML entities: 147

                                                message  label
24                                                &lt;#    0.0
128                                              &gt;bz    0.0
293                                               &lt;3    0.0
384                                               &lt;3    0.0
455   I've gotten all city maps today so I was like ...    0.0
551   czech_mad_man[BD_CR] (Centurion 7/1), you‘re B...    0.0
1235                           tog &amp; roll !! ladies    0.0
1615                                           &quot;_)    0.0
2712                                              &lt;3    0.0
2769                                              &lt;3    0.0

In [21]:
import html as html_lib

# drop #ERROR! rows
wot_clean = wot_deduped.copy()
wot_clean = wot_clean[~wot_clean["message"].str.contains(r"#ERROR!", regex=False, na=False)].reset_index(drop=True)

# decode HTML entities inline
wot_clean["message"] = wot_clean["message"].apply(html_lib.unescape)

print(f"Shape after artifact removal: {wot_clean.shape}")
# HTML entities
html_mask = wot_clean["message"].str.contains(r"&\w+;", regex=True, na=False)
print(f"Messages with HTML entities: {html_mask.sum()}")
wot_clean[html_mask][["message", "label"]].head(10)

Shape after artifact removal: (49386, 3)
Messages with HTML entities: 0

Empty DataFrame
Columns: [message, label]
Index: []

In [22]:
# check decoded messages 
wot_clean.loc[[24, 128, 293, 384, 455, 551, 
                 1235, 1615, 2712, 2769], ["message", "label"]]

                message  label
24    Im Spotted at E5!    0.0
128   Im Spotted at K6!    0.0
293               3 cap    0.0
384                  ez    0.0
455                  gj    0.0
551                  gg    0.0
1235  lock at that T 95    0.0
1615  arta support strv    0.0
2712              wp wp    0.0
2769             wtf???    2.0

In [23]:
# save again and evaluate 
wot_clean.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)
preprocessing_impact = eval_step("after_artifacts_removal", preprocessing_impact, datasets = ("WoT",))

                   step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_artifacts_removal     WoT 49386    0.5227       0.8766        0.6177           0.5094          0.0016       -0.0027           0.0058

In [24]:
# check 
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058

Step 5 essentially neutral: +0.0016 F1, -0.0027 recall, +0.0058 precision. Within noise range.

#### Mislabeled data

In [25]:
# few top rows of the data
wot_clean.head(5)

   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0
3  25964                      3 gunmark    0.0
4  28643                            lol    0.0

We might have mislabeled toxicity data that was classified as non-toxic or opposite. We need to detect and fix that as well.

In [26]:
from cleanlab.filter import find_label_issues
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_predict

# splits 
X = wot_clean["message"].values
y = wot_clean["label"].astype(int).values

# simple pipeline 
pipe = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_df=0.95,
                 sublinear_tf=True, norm="l2",
                 analyzer="word", tokenizer=tokenize, token_pattern=None)),
    ("clf", LogisticRegression(max_iter=1000, random_state=7524, 
                               class_weight = "balanced")),
])

# out-of-fold predicted probabilities (needs predict_proba - LR not LinearSVC)
oof_probs = cross_val_predict(pipe, X, y, cv=5, method="predict_proba", n_jobs=-1)

# find label issues
issue_idx = find_label_issues(
    labels=y,
    pred_probs=oof_probs,
    return_indices_ranked_by="self_confidence",  # worst first
)

print(f"Suspected mislabeled: {len(issue_idx)} ({len(issue_idx)/len(y):.1%})")

# inspect top offenders
wot_clean.iloc[issue_idx[:50]][["message", "label"]].assign(
    predicted=oof_probs[issue_idx[:50]].argmax(axis=1)
)

Suspected mislabeled: 4598 (9.3%)

                           message  label  predicted
47178        they call me an idiot    0.0          1
43809               idiot campersw    0.0          1
42383         nicalo idiot and all    0.0          1
10086                cromvel idiot    0.0          1
4708                     its a bot    0.0          1
7428                        to bot    0.0          1
7793                     its a bot    0.0          1
8440              top tier top bot    0.0          1
9591                      just bot    0.0          1
16809              S5 was a bot :/    0.0          1
11739             was that a bot??    0.0          1
29023               and an afk bot    0.0          1
25970             top tier top bot    0.0          1
32438                    me bot...    0.0          1
33891                      top bot    0.0          1
37357                  t1heavy bot    0.0          1
40236                    die there    1.0          4
47783               monti bot move    0.0          1
27054      wtf i win this and loss    0.0          2
47636       fucking useless morons    0.0          1
31062          gggo and die 1d1ots    1.0          4
30082                       wtf...    0.0          2
30708                      wtf ebr    0.0          2
34834                      WTF LOL    0.0          2
35004  wtf is that ???????????????    0.0          2
32302                      wtf ebr    0.0          2
35236                       is wtf    0.0          2
28444                 Fucking mesh    0.0          2
40426             fucking hopeless    0.0          2
46923                wtf you doing    0.0          2
40858                  wtf no spot    0.0          2
47303                  no guys wtf    0.0          2
49142                       GO wtf    0.0          2
42676                   idiot game    2.0          1
36281           and fucking naaabs    0.0          1
12957                      wtf lol    0.0          2
13061                     like wtf    0.0          2
17082                       WTF xD    0.0          2
12317                      wtf lol    0.0          2
38645                 fuck you RNG    0.0          2
4779                    lnacen wtf    0.0          2
12565                      fuck wg    0.0          2
20843                        wtf a    0.0          2
26684                     like wtf    0.0          2
42864                        fuck]    0.0          2
43125             go fuck yourself    0.0          2
25907                     fuck yes    0.0          2
28943                      fuck wg    0.0          2
48690          in die Zange nehmen    0.0          4
39845                 dont die pls    0.0          4

In [27]:
# clean data before update 
wot_clean1 = wot_clean.copy()
# relabel mislabeled rows with cleanlab's suggested labels instead of dropping
wot_clean1.loc[issue_idx, "label"] = oof_probs[issue_idx].argmax(axis=1)
print(f"Relabeled {len(issue_idx)} rows ({len(issue_idx)/len(wot_clean1):.1%})")

Relabeled 4598 rows (9.3%)

In [28]:
# save again and evaluate 
wot_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)
preprocessing_impact = eval_step("after_labels_fix", preprocessing_impact, datasets = ("WoT",))

            step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_labels_fix     WoT 49386    0.7886       0.9265        0.8545           0.7504          0.2659        0.2368            0.241

In [29]:
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410

That might be a model inflation. Let's check if gains are real with other model.

In [31]:
from sklearn.svm import LinearSVC

# impact 
preprocessing_impact = eval_step("after_labels_fix_svc", preprocessing_impact,
                                  datasets=("WoT",),
                                  clf=LinearSVC(max_iter=2000, random_state=7524, 
                                                class_weight = "balanced"))
preprocessing_impact

                step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_labels_fix_svc     WoT 49386    0.8126       0.9386        0.8381              0.8           0.024       -0.0164           0.0496

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410
7,after_labels_fix_svc,WoT,49386,0.8126,0.9386,0.8381,0.8000,0.0240,-0.0164,0.0496

There's still a risk that the score gains are inflated, however the data cleaning is real and coherent.

#### Final verification

In [33]:
# basic data checks
print("=== Shape ===")
print(wot_clean1.shape)

print("\n=== Nulls ===")
print(wot_clean1.isnull().sum())

print("\n=== Overall label distribution ===")
counts = wot_clean1["label"].value_counts().sort_index()
pct = wot_clean1["label"].value_counts(normalize=True).sort_index().mul(100).round(2)
print(pd.DataFrame({"count": counts, "pct%": pct}))

=== Shape ===
(49386, 3)

=== Nulls ===
index      0
message    0
label      0
dtype: int64

=== Overall label distribution ===
       count   pct%
label
0.0    38055  77.06
1.0     6248  12.65
2.0     4278   8.66
3.0      393   0.80
4.0      380   0.77
5.0       32   0.06

In [34]:
# save to parquet for easier loading in future steps
wot_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

## Dota

**Dota**
| Class | Label |
|---|---|
| 0 | Other (non-toxic) |
| 1 | Ego |
| 2 | Aggression |
| 3 | Impolite |

#### Inspect each split

In [35]:
# import data
train = pd.read_csv(DATA_DIR_DOTA / "CONDA_train.csv")
val = pd.read_csv(DATA_DIR_DOTA / "CONDA_valid.csv")

# inspect each split
for name, df in [("train", train), ("val", val)]:
    print(f"--- {name} ---")
    print(f"Shape: {df.shape}\n")
    print(f"Columns: {list(df.columns)}\n")
    print(f"First few rows of the data:\n{df.head(3)}\n")

--- train ---
Shape: (26921, 10)

Columns: ['Id', 'matchId', 'conversationId', 'utterance', 'chatTime', 'playerSlot', 'playerId', 'intentClass', 'slotClasses', 'slotTokens']

First few rows of the data:
      Id  matchId  conversationId utterance  chatTime  playerSlot  \
0  11263      697            3193      wow!        76           0
1  13741      843            3809       WTF      1563           5
2  22125     1412            6199   wpe wpe      2853           1

                  playerId intentClass slotClasses          slotTokens
0  ANTS IN MY EYES JOHNSON           O          O            wow (O),
1                      M.k           O          T            WTF (T),
2              Acqua Ragia           O        O O   wpe (O), wpe (O),

--- val ---
Shape: (8974, 10)

Columns: ['Id', 'matchId', 'conversationId', 'utterance', 'chatTime', 'playerSlot', 'playerId', 'intentClass', 'slotClasses', 'slotTokens']

First few rows of the data:
      Id  matchId  conversationId                 utterance  chatTime  \
0   6911      456            1987                        GG      3031
1   1512      132             509                        gg      2887
2  43138     2905           12306  GG [SEPA] nice late game      2783

   playerSlot                         playerId intentClass    slotClasses  \
0           9                               OG           O             S
1           9                             Xion           O             S
2           1  Im  good but my team is so  bad           O  S SEPA O O O

                                          slotTokens
0                                           GG (S),
1                                           gg (S),
2  GG (S), [SEPA] (SEPA), nice (O), late (O), gam...

#### Clean, merge and standardise

In [36]:
# map intentClass to numeric label consistent with WoT schema
label_map = {'O': 0, 'E': 1, 'A': 2, 'I': 3}

# add split column and map labels
train["split"] = "train"
val["split"]   = "val"

# merge train + val (no test split in CONDA)
dota = pd.concat([train, val], ignore_index=True)

# keep only relevant columns and rename to match WoT schema
dota = dota[["Id", "utterance", "intentClass", "split"]].rename(columns={
    "Id": "index",
    "utterance":   "message",
    "intentClass": "label",
})

# map string labels to numeric
dota["label"] = dota["label"].map(label_map)

# drop nulls in message (7 train + 1 val)
dota = dota.dropna(subset=["message"]).reset_index(drop=True)

# shape 
print(f"Merged shape: {dota.shape}\n")
print(f"First few rows of the data:\n{dota.head(3)}\n")
print("\nInformation about the dataset:\n")
dota.info()

Merged shape: (35887, 4)

First few rows of the data:
   index  message  label  split
0  11263     wow!      0  train
1  13741      WTF      0  train
2  22125  wpe wpe      0  train


Information about the dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    35887 non-null  int64
 1   message  35887 non-null  object
 2   label    35887 non-null  int64
 3   split    35887 non-null  object
dtypes: int64(2), object(2)
memory usage: 1.1+ MB

In [37]:
# save raw dota as baseline for ablation
dota.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_baseline_raw", preprocessing_impact, datasets=("Dota",))

             step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro
dota_baseline_raw    Dota 35887    0.7566       0.8709        0.7946           0.7318

In [38]:
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410
7,after_labels_fix_svc,WoT,49386,0.8126,0.9386,0.8381,0.8000,0.0240,-0.0164,0.0496
8,dota_baseline_raw,Dota,35887,0.7566,0.8709,0.7946,0.7318,NaN,NaN,NaN

Only `utterance`, `intentClass`, `Id`, and `split` are kept = the remaining columns (matchId, conversationId, chatTime, playerSlot, playerId, slotClasses, slotTokens) carry no linguistic content relevant to toxicity detection. Labels are mapped to integers matching the WoT schema where 0 = non-toxic. Null utterances are dropped - they carry no text signal.

#### Non-english language

Since we are going to model classifier on english data, it is important for us to detect non-english cases as many as we can.

In [39]:
# covers all major non-Latin scripts
NON_LATIN_SCRIPT = re.compile(
    r"[\u0400-\u04FF"   # Cyrillic
    r"\u4E00-\u9FFF"    # CJK unified ideographs
    r"\u3400-\u4DBF"    # CJK extension A
    r"\uF900-\uFAFF"    # CJK compatibility ideographs
    r"\u0600-\u06FF"    # Arabic
    r"\u0590-\u05FF"    # Hebrew
    r"\u3040-\u30FF"    # Japanese (Hiragana + Katakana)
    r"\uAC00-\uD7AF"    # Korean (Hangul syllables)
    r"\u1100-\u11FF"    # Korean (Hangul Jamo)
    r"\u0E00-\u0E7F"    # Thai
    r"\u0900-\u097F"    # Devanagari (Hindi)
    r"\u0980-\u09FF"    # Bengali
    r"\u0370-\u03FF"    # Greek
    r"\u10A0-\u10FF"    # Georgian
    r"\u0530-\u058F"    # Armenian
    r"\u1000-\u109F"    # Myanmar
    r"\u1780-\u17FF]"   # Khmer
)

# drop any message containing even 1 non-Latin script char
print(f"Non-english documents:\n{dota[dota['message'].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)}\n")

before = len(dota)
dota_en = dota[~dota["message"].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)
print(f"Dropped {before - len(dota_en)} ({(before - len(dota_en))/before:.1%})")
print(f"Rows after the drop: {dota_en.shape[0]}")

Non-english documents:
    index                                   message  label  split
0    8390                       s [SEPA] v [SEPA] ツ      0  train
1   23981      sure go mid with bh [SEPA] ¯\_(ツ)_/¯      0  train
2   24030                                       Νοο      0  train
3   36141                           noob [SEPA] กาก      1  train
4   19064                                     ใจยเน      0  train
5   18820                                ညသ တေမိ  ၊      0  train
6   23983                                 ¯\_(ツ)_/¯      0  train
7   27051                              เเ [SEPA] gg      0  train
8    8391                                         ツ      0  train
9   27048                                         ื      0  train
10  37396                                        ำผ      0  train
11  25892                              ไย [SEPA] wp      0  train
12  41950                                       กาก      0    val
13  19066                                     คนไทย      0    val
14  32824                                        ทำ      0    val
15   8670  dochu....양학....... [SEPA] 일본...재패니즈몽키...      0    val
16  33829                                       戒了吧      0    val
17  24017                                 ¯\_(ツ)_/¯      0    val

Dropped 18 (0.1%)
Rows after the drop: 35869

In [40]:
# save and evaluate non-Latin drop
dota_en.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_after_nonlatin_drop", preprocessing_impact, datasets=("Dota",))
preprocessing_impact

                    step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_nonlatin_drop    Dota 35869    0.7585       0.8715        0.7948           0.7344          0.0019        0.0002           0.0026

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410
7,after_labels_fix_svc,WoT,49386,0.8126,0.9386,0.8381,0.8000,0.0240,-0.0164,0.0496
8,dota_baseline_raw,Dota,35887,0.7566,0.8709,0.7946,0.7318,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7585,0.8715,0.7948,0.7344,0.0019,0.0002,0.0026

In [41]:
# detect latin but non-english documents - same detector as WoT
mask_d = dota_en["message"].apply(is_latin_non_english)
with pd.option_context("display.max_rows", 800):
    print(f"Non-english documents:{dota_en[mask_d]}")
    print(f"How many documents with non-english text: {dota_en[mask_d].shape[0]}")

Non-english documents:       index                                            message  label  split
1189   38131  reporta [SEPA] pro ibama [SEPA] fdp sacrifica ...      2  train
1196   40006  its in the bag  [SEPA] los q no tienen plata [...      0  train
1594   27145  vcs sao lixos [SEPA] n fode [SEPA] acha q fez ...      0  train
2393   38352  pukingina ka [SEPA] kangkong lancer [SEPA] goo...      0  train
4136     466  REPORT MI TEAM [SEPA] REPORT TODO MI TEAM BURR...      2  train
5763   12964                   LOOOOOOOOOL [SEPA] RECOMIENDENME      0  train
6385   37068                   oyoyoyoyoyoyoy wombo combo......      0  train
6470   25399  pro farmer [SEPA] orge farmt mehr als jeder bauer      0  train
6864   42190  very [SEPA] report a los 4 les puede tocar est...      2  train
6940   41505                 ez [SEPA] ez [SEPA] ez [SEPA] ezwp      3  train
8738   34169  POTANG INA KAYO [SEPA] BIGYAN NIYO NAMAN AKO N...      0  train
9138   33088  OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [...      0  train
9245    3484                    eZAASASAAS! [SEPA] SO EZA game!      0  train
9792    3131  gg report me team agggg [SEPA] report me team ...      2  train
10031  37028  XD [SEPA] XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...      0  train
10221  22135     xddddddddddddddddddddddddd [SEPA] ahgahahahaha      0  train
10399  36032            unluck ? [SEPA] EAIUHEAIUHEAIUEAIUHEAEA      0  train
10531  34340                    tienes que darme como 500 manos      0  train
10875  26090  qweeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...      0  train
12037  33090  OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [...      0  train
12798  10842               22 min agha undying [SEPA] yaysayaay      0  train
14232   6512     haahahaha [SEPA] CRY ASSHOLES [SEPA] kraaaaaay      1  train
14597  38130  reporta [SEPA] esse sf [SEPA] figueiredo [SEPA...      2  train
16345  43997                jaja pobre lloron [SEPA] hay basura      0  train
16571   1485  hay actualizacion [SEPA] lol [SEPA] se va a de...      0  train
18688  32694  ez bot ba>? [SEPA] ibig mong sabihin bobo kamp...      3  train
18725  33382       slardar pushhhhhhh [SEPA] slardar ds 1v1 mid      0  train
18838  33743  cRY MORE LA [SEPA] pinOYYYYYYYYY [SEPA] aW  [S...      0  train
20823  34335            diarrea eres} [SEPA] para eos vas medio      0  train
21088  37016  ojala no vuelva [SEPA] no quiero jugar con est...      0  train
21129  38353             it's a teamwipe [SEPA] it's a dizaztah      0  train
21481   2035  that slark [SEPA] HAWHWAHAW [SEPA] SO BAD [SEP...      1  train
21979  33078  Rsdfkpghsdšjhjosfh [SEPA] www.leagueoflegends....      0  train
22102  24484           GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      0  train
22157  27649  KKKKK [SEPA] KKKKKKKKKKKKK [SEPA] KKKKKKKKKKKK...      0  train
23133  28152       jogo muito n [SEPA] só desisti dessa partida      0  train
23330  28151  eu adoro bater em rubick q quer pagar de q jog...      0  train
24965  43767               JAJAJAJJA NO SABE A QUIEN GOLPEAR XD      0  train
25577  28145  `no susto? [SEPA] eu to tentando ensinar meu t...      0  train
26422  35195  1 for 1  [SEPA] haha [SEPA] kasrma [SEPA] is b...      1  train
27771  27910  HEHEHEHEHEEHEHEHEHEHEHEHEEHEHEHEHEHEHEHEHEHEEH...      0    val
28190  24480  ASDFSADFASDFASDFASDFASFASDFASDFSAFASDFSDAFSADF...      0    val
28557  27101        Report sf [SEPA] pinaka bobo sa buong mundo      2    val
29161   3519                THWN ORAXCLE AND WIM +1000% TO WIN!      0    val
29219  40639             I HATE THIS TEAM!!!!! [SEPA] HHSHSDHSD      1    val
29258  33881                   uya [SEPA] ks [SEPA] kayyyy esss      0    val
30964  28631  PORFAVOR AYUDEN NO LES GUSTARIA Q LES TOQUE ES...      0    val
31601  17235                   woierjewkhfiwepojoiwehfijwer ok?      0    val
31733   1612  GAGLHWSLHW [SEPA] HSLDHLWHWL [SEPA] LHAWLGAL [...      1    val
33144  32735  MURTAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...      0    val
33602  34543       OH FÜR Gottes willen [SEPA] WARUM SO EINFACH      0    val
33875  39614  WFEPI(J WPIJWPEIFG [SEPA] qfhqiuhfouqehfoqwf [...      2    val
34082  32783  u lile this [SEPA] u shit [SEPA] stfu [SEPA] e...      1    val
34871  28620  XD [SEPA] LINA Y PUGDE REPORTADO [SEPA] LINA Y...      0    val
35075   6491        GG [SEPA] AJAJAJAJAHAHAHAH [SEPA] HSJJAHAHA      0    val
35518  11475         stupid lion [SEPA] lel [SEPA] wkdopqwkdqwp      1    val
How many documents with non-english text: 56

Only 56 rows. Let's drop that as well.

In [42]:
# dataset update
dota_en = dota_en[~mask_d].reset_index(drop=True)
# length after the drop
print(f"Length after the drop: {dota_en.shape[0]}")

Length after the drop: 35813

In [44]:
# save and evaluate Lingua drop
dota_en.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_after_noneng_drop", preprocessing_impact, datasets=("Dota",))
preprocessing_impact

                  step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_noneng_drop    Dota 35813    0.7557       0.8703        0.7936           0.7306         -0.0028       -0.0012          -0.0038

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410
7,after_labels_fix_svc,WoT,49386,0.8126,0.9386,0.8381,0.8000,0.0240,-0.0164,0.0496
8,dota_baseline_raw,Dota,35887,0.7566,0.8709,0.7946,0.7318,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7585,0.8715,0.7948,0.7344,0.0019,0.0002,0.0026
10,dota_after_noneng_drop,Dota,35813,0.7557,0.8703,0.7936,0.7306,-0.0028,-0.0012,-0.0038

-0.0028 is within CV variance. Lingua dropped 56 rows from 35.8k (0.16%), negligible either way. No meaningful signal here.

#### Data Artifacts

In [45]:
# strip [SEPA] separator tokens - data collection artifact, not language
dota_en["message"] = dota_en["message"].str.replace(r"\s*\[SEPA\]\s*", " ", regex=True).str.strip()
print(f"[SEPA] remaining: {dota_en['message'].str.contains(r'\[SEPA\]', regex=True).sum()}")

# save and evaluate SEPA strip
dota_en.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_after_sepa_strip", preprocessing_impact, datasets=("Dota",))
preprocessing_impact

[SEPA] remaining: 0
                 step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_sepa_strip    Dota 35813    0.7667       0.8782        0.7921           0.7477           0.011       -0.0015           0.0171

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410
7,after_labels_fix_svc,WoT,49386,0.8126,0.9386,0.8381,0.8000,0.0240,-0.0164,0.0496
8,dota_baseline_raw,Dota,35887,0.7566,0.8709,0.7946,0.7318,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7585,0.8715,0.7948,0.7344,0.0019,0.0002,0.0026
10,dota_after_noneng_drop,Dota,35813,0.7557,0.8703,0.7936,0.7306,-0.0028,-0.0012,-0.0038
11,dota_after_sepa_strip,Dota,35813,0.7667,0.8782,0.7921,0.7477,0.0110,-0.0015,0.0171

#### Duplicates

In [46]:
# look at dataset with duplicates
dota_dup = dota_en[dota_en.duplicated(subset="message", keep=False)].sort_values("message")
dota_dup.head(10)

       index message  label  split
28737   7592       !      0    val
17605  11136       !      0  train
10917  32061       !      0  train
26859  38158       !      0  train
19114  42692       !      0  train
23736  24950       !      0  train
9434   35992       !      0  train
17620   6806      !!      0  train
33266   1008      !!      0    val
23995  10693    !!!!      0  train

In [47]:
# top 30 most duplicated messages
dota_dup["message"].value_counts(ascending=False).head(30)

message
gg        1466
lol        691
?          445
ggwp       355
haha       348
gg wp      316
GG         291
ez         274
LOL        192
ty         160
:D         147
hahaha     135
wp         133
XD          96
GGWP        91
ok          82
EZ          81
+           78
Gg          74
:)          73
wtf         70
rofl        65
xD          60
wait        59
ez mid      59
HAHA        58
end         58
g           55
:(          55
)           54
Name: count, dtype: int64

In [48]:
# find conflicting labels
conflicts_d = dota_en.groupby("message")["label"].nunique()
conflicts_d = conflicts_d[conflicts_d > 1]
conflict_rows_d = dota_en[dota_en["message"].isin(conflicts_d.index)].sort_values("message")
conflict_pct_d = len(conflict_rows_d) / len(dota_en) * 100
print(f"Messages with conflicting labels: {len(conflicts_d)}")
print(f"Proportion: {conflict_pct_d:.2f}%")
print(f"Rows affected: {len(conflict_rows_d)}")

Messages with conflicting labels: 147
Proportion: 13.68%
Rows affected: 4900

In [49]:
# check conflicting rows
conflict_rows_d

       index message  label  split
9255   21192       )      0  train
4517   38062       )      0  train
33791  37984       )      0    val
18525  34207       )      0  train
31037  41690       )      0    val
...      ...     ...    ...    ...
17506   7192      zz      0  train
960    22280      zz      0  train
856    30365      zz      0  train
31652  26815      zz      0    val
33805  30943      zz      2    val

[4900 rows x 4 columns]

Same as WoT - annotation noise. Dropping would lose training signal. Assign majority label instead.

In [50]:
# majority label for all messages
majority_label_d = dota_en.groupby("message")["label"].agg(lambda x: x.value_counts().index[0])

# remap all labels to majority vote
dota_deduped = dota_en.copy()
dota_deduped["label"] = dota_deduped["message"].map(majority_label_d)

# check former conflicting messages
dota_deduped[dota_deduped["message"].isin(conflicts_d.index)][["message", "label"]].head(20)

     message  label
1        WTF      0
3     hahaha      0
4        wtf      0
22      ggwp      0
35        gg      0
39         ?      0
48        gg      0
52        ez      3
58   ez game      3
71      HAHA      0
97        EZ      3
104     ggwp      0
105      lol      0
110      lol      0
146      LOL      0
151      lol      0
153     noob      1
156       gg      0
161     ggwp      0
162     wait      2

In [51]:
# save and evaluate majority map
dota_deduped.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_after_majority_map", preprocessing_impact, datasets=("Dota",))
preprocessing_impact

                   step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_majority_map    Dota 35813     0.778       0.8843        0.8002           0.7611          0.0113        0.0081           0.0134

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410
7,after_labels_fix_svc,WoT,49386,0.8126,0.9386,0.8381,0.8000,0.0240,-0.0164,0.0496
8,dota_baseline_raw,Dota,35887,0.7566,0.8709,0.7946,0.7318,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7585,0.8715,0.7948,0.7344,0.0019,0.0002,0.0026
10,dota_after_noneng_drop,Dota,35813,0.7557,0.8703,0.7936,0.7306,-0.0028,-0.0012,-0.0038
11,dota_after_sepa_strip,Dota,35813,0.7667,0.8782,0.7921,0.7477,0.0110,-0.0015,0.0171
12,dota_after_majority_map,Dota,35813,0.7780,0.8843,0.8002,0.7611,0.0113,0.0081,0.0134

That is the best we can do and it actually improves the score as well.

#### Mislabeled data

In [52]:
# few top rows of the data
dota_deduped.head(5)

   index  message  label  split
0  11263     wow!      0  train
1  13741      WTF      0  train
2  22125  wpe wpe      0  train
3   6453   hahaha      0  train
4   9644      wtf      0  train

We might have mislabeled toxicity data that was classified as non-toxic or opposite. We need to detect and fix that as well.

In [53]:
# splits
X_d = dota_deduped["message"].values
y_d = dota_deduped["label"].astype(int).values

# simple pipeline - same config as WoT
pipe_d = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_df=0.95,
                              sublinear_tf=True, norm="l2",
                              analyzer="word", tokenizer=tokenize, token_pattern=None)),
    ("clf", LogisticRegression(max_iter=1000, random_state=7524, class_weight="balanced")),
])

# out-of-fold predicted probabilities
oof_probs_d = cross_val_predict(pipe_d, X_d, y_d, cv=5, method="predict_proba", n_jobs=-1)

# find label issues
issue_idx_d = find_label_issues(
    labels=y_d,
    pred_probs=oof_probs_d,
    return_indices_ranked_by="self_confidence",  # worst first
)

print(f"Suspected mislabeled: {len(issue_idx_d)} ({len(issue_idx_d)/len(y_d):.1%})")

# inspect top offenders
dota_deduped.iloc[issue_idx_d[:50]][["message", "label"]].assign(
    predicted=oof_probs_d[issue_idx_d[:50]].argmax(axis=1)
)

Suspected mislabeled: 1956 (5.5%)

                                                 message  label  predicted
7160                                                 EZ)      0          3
7704                                                 EZ^      0          3
16118                                              ez WR      0          3
5384                                                 ez&      0          3
24214  pls just report them so that you dont get them...      0          2
22530                                  REPORT BARAT GGWP      0          2
22672                               mirana please report      0          2
8222               im confsued now, who should i report?      0          2
30038                                        why report?      0          2
6728                                  report my team pls      0          2
25626                                              NOOB!      0          1
23294                                       spectre noob      0          1
14575                              Game was good sf noob      0          1
2231                                             im noob      0          1
15423                                            oh shit      0          1
16790                       see that shit is just spooky      0          1
18290                                            oh shit      0          1
17509                             SHUT UP FUCKING NOOB !      0          1
29943                                        LOL fucking      0          1
23737                                              ez sb      1          3
21774                                            ez riki      1          3
11657                                           ez staks      1          3
10602                                             EZ mmr      1          3
14249                                     EZ PERRUUUUUUU      1          3
8042                                         this was ez      1          3
32501                          good game fuck that pudge      0          1
30663                                      WHAT THE FUCK      0          1
34577                                           LOL FUCK      0          1
32959                           and you can fuck off too      0          1
26948                                       oh what fuck      0          1
24139                                just what the fuck?      0          1
22917                                           fuck lag      0          1
24338                                    Intense as fuck      0          1
9794                                 the fucking keybord      0          1
11665              why the fuck you lion you always lion      0          1
11713         has predicted their team will win! oh fuck      0          1
10857                                              FUCK!      0          1
11119                     its not good game fuck you all      0          1
3539                                 we dont give a fuck      0          1
18239                                      fuck off zeus      0          1
5420                                           2FCKNG EZ      1          3
34450                                  Fuck fucking zeus      0          1
10030                                     okay fuck shit      0          1
24849                                 Fucking PA and QOP      2          1
17902                                  report my team ty      3          2
16015                                      report me too      3          2
20815                                    no i report you      3          2
33561                              FUCKING WAIT for lich      2          1
21351                                       commend lina      0          2
19217                                  commend the juggs      0          2

Most of them are mislabeled. Let's replace labels instead of dropping.

In [54]:
# relabel mislabeled rows with cleanlab's suggested labels instead of dropping
dota_clean = dota_deduped.copy()
dota_clean.loc[issue_idx_d, "label"] = oof_probs_d[issue_idx_d].argmax(axis=1)
print(f"Relabeled {len(issue_idx_d)} rows ({len(issue_idx_d)/len(dota_clean):.1%})")

Relabeled 1956 rows (5.5%)

In [55]:
# save and evaluate labels fix
dota_clean.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_after_labels_fix", preprocessing_impact, datasets=("Dota",))

                 step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_labels_fix    Dota 35813    0.8764       0.9303        0.8865           0.8686          0.0984        0.0863           0.1075

In [56]:
# check 
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410
7,after_labels_fix_svc,WoT,49386,0.8126,0.9386,0.8381,0.8000,0.0240,-0.0164,0.0496
8,dota_baseline_raw,Dota,35887,0.7566,0.8709,0.7946,0.7318,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7585,0.8715,0.7948,0.7344,0.0019,0.0002,0.0026
10,dota_after_noneng_drop,Dota,35813,0.7557,0.8703,0.7936,0.7306,-0.0028,-0.0012,-0.0038
11,dota_after_sepa_strip,Dota,35813,0.7667,0.8782,0.7921,0.7477,0.0110,-0.0015,0.0171
12,dota_after_majority_map,Dota,35813,0.7780,0.8843,0.8002,0.7611,0.0113,0.0081,0.0134
13,dota_after_labels_fix,Dota,35813,0.8764,0.9303,0.8865,0.8686,0.0984,0.0863,0.1075

That might be a model inflation. Let's check if gains are real with other model.

In [57]:
# SVC circularity check
preprocessing_impact = eval_step("dota_after_labels_fix_svc", preprocessing_impact,
                                  datasets=("Dota",), clf=LinearSVC(max_iter=2000, random_state=7524))

                     step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_labels_fix_svc    Dota 35813    0.8973       0.9428        0.8723           0.9258          0.0209       -0.0142           0.0572

In [58]:
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4765,0.8608,0.5530,0.4586,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4946,0.8679,0.5919,0.4756,0.0181,0.0389,0.0170
2,after_noneng_drop,WoT,49557,0.5030,0.8681,0.6037,0.4862,0.0084,0.0118,0.0106
3,after_duplicates_removal,WoT,42259,0.4692,0.8671,0.5551,0.4631,-0.0338,-0.0486,-0.0231
4,after_duplicates_majority_map,WoT,49557,0.5211,0.8770,0.6204,0.5036,0.0519,0.0653,0.0405
5,after_artifacts_removal,WoT,49386,0.5227,0.8766,0.6177,0.5094,0.0016,-0.0027,0.0058
6,after_labels_fix,WoT,49386,0.7886,0.9265,0.8545,0.7504,0.2659,0.2368,0.2410
7,after_labels_fix_svc,WoT,49386,0.8126,0.9386,0.8381,0.8000,0.0240,-0.0164,0.0496
8,dota_baseline_raw,Dota,35887,0.7566,0.8709,0.7946,0.7318,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7585,0.8715,0.7948,0.7344,0.0019,0.0002,0.0026
10,dota_after_noneng_drop,Dota,35813,0.7557,0.8703,0.7936,0.7306,-0.0028,-0.0012,-0.0038
11,dota_after_sepa_strip,Dota,35813,0.7667,0.8782,0.7921,0.7477,0.0110,-0.0015,0.0171
12,dota_after_majority_map,Dota,35813,0.7780,0.8843,0.8002,0.7611,0.0113,0.0081,0.0134
13,dota_after_labels_fix,Dota,35813,0.8764,0.9303,0.8865,0.8686,0.0984,0.0863,0.1075
14,dota_after_labels_fix_svc,Dota,35813,0.8973,0.9428,0.8723,0.9258,0.0209,-0.0142,0.0572

There's still a risk that the score gains are inflated, however the data is now cleaner.

#### Final verification

In [59]:
print("=== Shape ===")
print(dota_clean.shape)

print("=== Nulls ===")
print(dota_clean.isnull().sum())

print("=== Label distribution ===")
counts = dota_clean["label"].value_counts().sort_index()
pct    = dota_clean["label"].value_counts(normalize=True).sort_index().mul(100).round(1)
label_names = {0: "Other (O)", 1: "Ego (E)", 2: "Aggression (A)", 3: "Impolite (I)"}
print(pd.DataFrame({"count": counts, "pct%": pct}).rename(index=label_names))

=== Shape ===
(35813, 4)
=== Nulls ===
index      0
message    0
label      0
split      0
dtype: int64
=== Label distribution ===
                count  pct%
label
Other (O)       25784  72.0
Ego (E)          4778  13.3
Aggression (A)   2708   7.6
Impolite (I)     2543   7.1

In [60]:
# save cleaned dota to parquet for easier loading in future steps
dota_clean.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)

In [61]:
# save our preprocessing rounds
preprocessing_impact.to_csv(
    PROJECT_ROOT / "data/results/cleaning_ablation.csv", 
    index=False
)
print("Saved cleaning_ablation.csv")

Saved cleaning_ablation.csv