# Gaming Toxicity Detection

**Authors:** Beibarys Nyussupov, Ruby Ngo, Paola Calle, Jett Forward

In [1]:
# libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path 
import re 
import sys
sys.path.insert(0, str(Path("../..").resolve()))

# custom functions - tokenizer, step evaluator
from src.tokenizer import tokenize
from src.prep_evaluation_multi import eval_step

# reproducibility
seed = 7524
np.random.seed(seed)

# project root (notebooks/gaming/ - notebooks/ - project root)
PROJECT_ROOT = Path().resolve().parent.parent

In [2]:
# data directories
DATA_DIR_WOT  = PROJECT_ROOT / "data/raw_data/wot/"
DATA_DIR_DOTA = PROJECT_ROOT / "data/raw_data/dota/"

## World of Tanks

**World of Tanks**
| Class | Terminology |
|---|---|
| 0 | Non-Toxic |
| 1 | Insults and Flaming |
| 2 | Other Offensive Texts |
| 3 | Hate and Harassment |
| 4 | Threats |
| 5 | Extremism |

#### Inspect each split

In [3]:
# import data 
train = pd.read_csv(DATA_DIR_WOT / "train.csv")
val = pd.read_csv(DATA_DIR_WOT / "val.csv")

# test dataset 
test_text = pd.read_csv(DATA_DIR_WOT /  "test_index_text.csv")
test_label = pd.read_csv(DATA_DIR_WOT / "test_index_label.csv")

# check the data 
for name, df in [("train", train), ("val", val), ("test_text", test_text), ("test_label", test_label)]:
    print(f"--- {name} ---")
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print(f"First few rows of the dataset:\n{df.head(3)}")
    print()

--- train ---
Shape: (42959, 3)
Columns: ['index', 'message', 'label']
First few rows of the dataset:
   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0

--- val ---
Shape: (5367, 3)
Columns: ['index', 'message', 'label']
First few rows of the dataset:
   index       message  label
0  31697  e50 is there    0.0
1  52311   this scouts    0.0
2   2775       i guess    0.0

--- test_text ---
Shape: (5375, 2)
Columns: ['index', 'message']
First few rows of the dataset:
   index         message
0  17775  aim you monkey
1  28228   Pz kill artys
2  19888             ggs

--- test_label ---
Shape: (5375, 2)
Columns: ['index', 'label']
First few rows of the dataset:
   index  label
0  17775    2.0
1  28228    0.0
2  19888    0.0

The test set is stored in two separate files - text and labels indexed by the same `index` column. Train and val are already complete. We need to join the test files on `index` before merging everything.

#### Reconstruct test split and merge all

In [4]:
# merge test text and labels
test = test_text.merge(test_label, on="index", how="inner")

# concatenate all data
wot = pd.concat([train, val, test], ignore_index=True)

print(f"Test join shape: {test.shape}\n")
print(f"Merged shape: {wot.shape}\n")
print(f"First few rows of the data:\n{wot.head(3)}\n")
print(f"Information about the data: {wot.info()}")

Test join shape: (5375, 3)

Merged shape: (53701, 3)

First few rows of the data:
   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53701 entries, 0 to 53700
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    53701 non-null  int64
 1   message  53701 non-null  object
 2   label    53701 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ MB
Information about the data: None

The test join uses `inner` - any index present in only one file would be silently dropped. If test shape after join is smaller than either file's length, there is an alignment issue in the original data.

In [5]:
# to test improvement or degradation after each preprocessing step, 
# we export the data as raw parquet and compare score of predictions of raw vs processed data. 
wot.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

# baseline — before any cleaning
preprocessing_impact = eval_step("baseline_raw", datasets = ("WoT",))

        step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
baseline_raw     WoT 53701    0.4855        0.861        0.5599           0.4696             0.0           0.0              0.0

#### Non-english language

Since we are going to model classifier on english data, it is important for us to detect non-english cases as many as we can.

In [6]:
# detecting Non-lating-script messages 

# covers all major non-Latin characters
NON_LATIN_SCRIPT = re.compile(
    r"[\u0400-\u04FF"   # Cyrillic
    r"\u4E00-\u9FFF"    # CJK unified ideographs
    r"\u3400-\u4DBF"    # CJK extension A
    r"\uF900-\uFAFF"    # CJK compatibility ideographs
    r"\u0600-\u06FF"    # Arabic
    r"\u0590-\u05FF"    # Hebrew
    r"\u3040-\u30FF"    # Japanese (Hiragana + Katakana)
    r"\uAC00-\uD7AF"    # Korean (Hangul syllables)
    r"\u1100-\u11FF"    # Korean (Hangul Jamo)
    r"\u0E00-\u0E7F"    # Thai
    r"\u0900-\u097F"    # Devanagari (Hindi)
    r"\u0980-\u09FF"    # Bengali
    r"\u0370-\u03FF"    # Greek
    r"\u10A0-\u10FF"    # Georgian
    r"\u0530-\u058F"    # Armenian
    r"\u1000-\u109F"    # Myanmar
    r"\u1780-\u17FF]"   # Khmer
)

# drop any message containing even 1 non-Latin script char
print(f"Non-english documents:\n{wot[wot['message'].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)}\n")

# changes 
before = len(wot)
wot_en = wot[~wot["message"].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)
print(f"Dropped {before - len(wot_en)} ({(before - len(wot_en))/before:.1%})")
print("Label distribution before:")
print(wot["label"].value_counts(normalize=True).sort_index(), "\n")

print("\nLabel distribution after:")
print(wot_en["label"].value_counts(normalize=True).sort_index(), "\n")
print(f"Rows after the drop: {wot_en.shape[0]}")
# save new step again
wot_en.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

Non-english documents:
      index                message  label
0     13087          ще злийте )))    1.0
1     31917       перший бій, сток    0.0
2     40395                ФОКУСЯТ    0.0
3     54412  елка спасибо тебе ...    0.0
4      5457                 уроди!    0.0
...     ...                    ...    ...
3845   5453                 я кину    0.0
3846   5456                светите    0.0
3847  13081       в чём притензия?    0.0
3848   7331      вот и подкруточки    0.0
3849  50128  тут танки стоят уебак    0.0

[3850 rows x 3 columns]

Dropped 3850 (7.2%)
Label distribution before:
label
0.0    0.809985
1.0    0.137930
2.0    0.043630
3.0    0.006499
4.0    0.001397
5.0    0.000559
Name: proportion, dtype: float64


Label distribution after:
label
0.0    0.812782
1.0    0.136126
2.0    0.043770
3.0    0.005376
4.0    0.001384
5.0    0.000562
Name: proportion, dtype: float64

Rows after the drop: 49851

In [7]:
# check non-latin language drop
preprocessing_impact = eval_step("after_nonlatin_drop", preprocessing_impact, datasets="WoT")
preprocessing_impact

               step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_nonlatin_drop     WoT 49851    0.4976       0.8692        0.5921           0.4799          0.0121        0.0322           0.0103

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103

In [8]:
import re
import pandas as pd
from lingua import Language, LanguageDetectorBuilder

# detecting Latin-script but likely non-English messages

# use all Latin-script languages supported by Lingua
# English must stay inside the detector, otherwise English text gets forced into another language
LATIN_LANGUAGES = list(Language.all_with_latin_script())

# detector for Latin-script language detection
# minimum_relative_distance: if top languages are too close, Lingua returns None instead of guessing
detector = (
    LanguageDetectorBuilder
    .from_languages(*LATIN_LANGUAGES)
    .with_minimum_relative_distance(0.25)
    .build()
)

# safety tokens: if these appear, keep the message because it may be gaming/chat English or mixed slang
SAFETY_TOKENS = {
    # gaming / chat
    "gg", "ez", "wp", "gl", "hf", "glhf", "afk", "brb", "lol", "lmao", "lmfao",
    "omg", "wtf", "stfu", "noob", "n00b", "bot", "team", "report", "ban",
    "kick", "mute", "trash", "toxic", "troll", "feed", "feeder", "int", "throw",
    "rank", "elo", "kill", "kys", "die", "fps", "lag", "ping", "server",
    "wot", "dota", "fortnite", "fn",

    # English / toxicity cues
    "you", "your", "you're", "u", "ur", "are", "is", "this", "that", "the",
    "and", "not", "dont", "don't", "fuck", "fucking", "fuk", "fck", "shit",
    "bitch", "ass", "asshole", "idiot", "stupid", "dumb", "moron", "loser",
    "suck", "sucks"
}

TOKEN_RE = re.compile(r"[a-z0-9']+", flags=re.IGNORECASE)


def get_tokens(text):
    return set(TOKEN_RE.findall(str(text).lower()))


def has_safety_token(text):
    return bool(get_tokens(text) & SAFETY_TOKENS)


# function to classify what to do with each Latin-script message
def latin_language_filter_status(text):
    text_str = str(text).strip()
    tokens = get_tokens(text_str)

    # too short - keep
    # language detection is unreliable on short gaming/chat messages
    if len(text_str) < 50 or len(tokens) < 6:
        return "keep_short"

    # possible gaming/chat/English false positive - keep
    if has_safety_token(text_str):
        return "keep_possible_gaming_or_mixed"

    lang = detector.detect_language_of(text_str)

    # ambiguous - keep
    if lang is None:
        return "keep_ambiguous"

    # English - keep
    if lang == Language.ENGLISH:
        return "keep_english"

    # confident Latin-script non-English - drop
    return f"drop_latin_nonenglish_{lang.name.lower()}"


# apply detection
wot_en_lang = wot_en.copy()
wot_en_lang["lang_filter_status"] = wot_en_lang["message"].apply(latin_language_filter_status)

# inspect groups
print("Language filter status counts:")
print(wot_en_lang["lang_filter_status"].value_counts().head(30))


# check ambiguous cases
# these are messages where Lingua did not confidently choose a language
ambiguous_mask = wot_en_lang["lang_filter_status"].eq("keep_ambiguous")

print(f"\nAmbiguous Latin-script language documents kept: {ambiguous_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nAmbiguous documents kept for now:\n",
        wot_en_lang.loc[
            ambiguous_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among ambiguous rows:")
print(
    wot_en_lang.loc[ambiguous_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# check possible gaming / mixed-language false positives
# these are messages that Lingua might classify as non-English, but contain gaming/chat/English cues
mixed_mask = wot_en_lang["lang_filter_status"].eq("keep_possible_gaming_or_mixed")

print(f"\nPossible gaming or mixed-language documents kept: {mixed_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nPossible gaming/mixed documents kept for now:\n",
        wot_en_lang.loc[
            mixed_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among possible gaming/mixed rows:")
print(
    wot_en_lang.loc[mixed_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# drop only confident Latin-script non-English rows
drop_mask = wot_en_lang["lang_filter_status"].str.startswith("drop_latin_nonenglish")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nConfident Latin-script non-English documents to drop:\n",
        wot_en_lang.loc[
            drop_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print(f"\nHow many confident Latin-script non-English documents: {drop_mask.sum()}")


# label distribution sanity check
dropped_latin_nonenglish = wot_en_lang.loc[drop_mask]

print("\nLabel distribution before Latin non-English drop:")
print(wot_en["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after Latin non-English drop:")
print(
    wot_en_lang.loc[~drop_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nLabel distribution among dropped rows:")
print(
    dropped_latin_nonenglish["label"]
    .value_counts(normalize=True)
    .sort_index()
)


# create dataset after Latin non-English drop
# keep ambiguous and mixed/gaming rows
wot_lang_clean = (
    wot_en_lang
    .loc[~drop_mask]
    .drop(columns=["lang_filter_status"])
    .reset_index(drop=True)
)

print(f"\nRows before Latin non-English drop: {len(wot_en)}")
print(f"Dropped {drop_mask.sum()} ({drop_mask.sum() / len(wot_en):.1%})")
print(f"Rows after Latin non-English drop: {len(wot_lang_clean)}")

Language filter status counts:
lang_filter_status
keep_short                         48686
keep_possible_gaming_or_mixed        981
keep_english                          63
keep_ambiguous                        43
drop_latin_nonenglish_polish          29
drop_latin_nonenglish_german          26
drop_latin_nonenglish_hungarian        8
drop_latin_nonenglish_french           6
drop_latin_nonenglish_turkish          3
drop_latin_nonenglish_czech            2
drop_latin_nonenglish_spanish          1
drop_latin_nonenglish_bosnian          1
drop_latin_nonenglish_romanian         1
drop_latin_nonenglish_finnish          1
Name: count, dtype: int64

Ambiguous Latin-script language documents kept: 43

Ambiguous documents kept for now:
                                                                                        message  \
456                             I've gotten all city maps today so I was like &quot;FINE&quot;
532               BattleGreen (Skorpion G), T'es tellement gros que tu bloque mon tir d??gage!
1069     CURVA BLT JUS SUKA GALVOJAT KAD MAN IDOMU BLT 46M SITA CHUINEEEEEEEEEEEEEEEEEEEEEEEEE
3106                                   last 3 shots kinda vanished like a fart in a wind storm
3208                                 i did after 1,3 k much too few for a super conqueror, stb
4434                                  Enemy SPG <font color='#fe7903'>killerkirby99_2013 (M44)
5023                                      sniper medium tank will try to snipe from a distance
6414                                      make more superfast 900 dmg per shot tanks wg please
7810                            Im Spotted at B9! :o But I am wearing a mask! :) I am safe! ;)
8976                                   <font color='#f8f400'>TheAmiableReaper[BABNS] (T-34-85)
9814                            Im Spotted at K6! :o But I am wearing a mask! :) I am safe! ;)
11893                        Enemy SPG <font color='#fe0e00'>gonzales_3 (Lorraine 155 mle. 50)
13309                       Enemy SPG <font color='#fe7903'>Leopard1965 (Lorraine 155 mle. 50)
14933                                 hab schon ??ber legt FV304... schaden.. ist schaden xDDD
15613                                      XD lynx jak bys sie nie pchał po dmg to by było git
17937                                      Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)
18206                        Enemy SPG <font color='#fe0e00'>gonzales_3 (Lorraine 155 mle. 50)
18258                                   ty to VK 28.01.105 i was unable to co to my spot Sorry
18454                             Enemy SPG <font color='#fe0e00'>WMBB (Bat.-Châtillon 155 58)
19043                https://open.spotify.com/track/03RojRDRvvbFEPpabo3Aan?si=ef083469698742a4
19747                                   baaaaa...bagamias pula in mata....trage si tu odata...
19755                                      jebać was cwele ulańca za darmo brawo mami synki :/
20090                                   pls mommy can I be a motherufcking T34 when i grow up!
22562                                   just a useless pos who hs no clue how to play a medium
22618                           Im Spotted at B9! :o But I am wearing a mask! :) I am safe! ;)
24260                       daddy look, i got a clown car...i can sit in a bush in tha back...
24896                                      Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)
30776  ConstantineDeLumberjack (FV215b 183), T'es tellement gros que tu bloque mon tir dégage!
31536                                       they have invis tiger i cant spot him on 50 meters
31823                     que onda? bufearon las artys? porque pegan como padrastro alcoholico
32826                                    Enemy SPG <font color='#fe7903'>PECHOLATA_65 (Hummel)
33202                                 panzertank14 (Leopard 1), nem tudok lönni töled te buzi!
33689                                  i was toptier on front i got only 1 tlowtier td support
34120                               T??ss?? ei riitt??ny gun depressio, silti otti artikutia..
35516                                     S CONQ FULL WILDCAMPER'sss BOTTT GGAAYY2 MUZSIKK 2 X
39370                                     abys dostal doma par facek abys vedel, jak se chovat
40079                         hahahaha no blok demi hahahahaha wg best softver game retard mod
41892                       FUICKING thanbks wg for all 23 clips of preprogrammed misses shots
42585          rinoceronte ty huju zeby ci stara wyruchali w dupsko a potem to wylizała szmata
44983                                 thx skorpio but no other help from these line A! campers
46338                       Enemy SPG <font color='#fe7903'>T_55_Ladelude (AMX 105 AM mle. 47)
47405                             good job medium campers , tier 4 camper idiots .lego players
47879                                      Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)

       label lang_filter_status
456      0.0     keep_ambiguous
532      0.0     keep_ambiguous
1069     1.0     keep_ambiguous
3106     0.0     keep_ambiguous
3208     0.0     keep_ambiguous
4434     0.0     keep_ambiguous
5023     0.0     keep_ambiguous
6414     0.0     keep_ambiguous
7810     0.0     keep_ambiguous
8976     0.0     keep_ambiguous
9814     0.0     keep_ambiguous
11893    0.0     keep_ambiguous
13309    0.0     keep_ambiguous
14933    0.0     keep_ambiguous
15613    0.0     keep_ambiguous
17937    0.0     keep_ambiguous
18206    0.0     keep_ambiguous
18258    0.0     keep_ambiguous
18454    0.0     keep_ambiguous
19043    0.0     keep_ambiguous
19747    2.0     keep_ambiguous
19755    1.0     keep_ambiguous
20090    1.0     keep_ambiguous
22562    1.0     keep_ambiguous
22618    0.0     keep_ambiguous
24260    2.0     keep_ambiguous
24896    0.0     keep_ambiguous
30776    0.0     keep_ambiguous
31536    0.0     keep_ambiguous
31823    0.0     keep_ambiguous
32826    0.0     keep_ambiguous
33202    3.0     keep_ambiguous
33689    0.0     keep_ambiguous
34120    0.0     keep_ambiguous
35516    1.0     keep_ambiguous
39370    1.0     keep_ambiguous
40079    1.0     keep_ambiguous
41892    1.0     keep_ambiguous
42585    3.0     keep_ambiguous
44983    2.0     keep_ambiguous
46338    0.0     keep_ambiguous
47405    1.0     keep_ambiguous
47879    0.0     keep_ambiguous

Label distribution among ambiguous rows:
label
0.0    0.674419
1.0    0.209302
2.0    0.069767
3.0    0.046512
Name: proportion, dtype: float64

Possible gaming or mixed-language documents kept: 981

Possible gaming/mixed documents kept for now:
                                                                                                              message  \
38                                                              this game is so fun when u got 2 chiefs shoting gold
65                                                     Awww... show me on the tank where the bad arty touched you...
100                                           holy crap its almost like playing the wrong side of the map was stupid
113                                                        What are the chances of the LT sitting in the usual bush?
168    https://www.twitch.tv/malpa_gaming_ha_ha KONKURS NA ZLOTO I PREMIUM TANKS ..GIVEWAY FOR GOLD AND PREMIUM TANK
...                                                                                                              ...
49714       come on Fetz...you rush into the ditch cause ya got leet skill and an awesome tank for playing the ditch
49755                                          summary of the day: shit maps, shit MM, gold spammers and moron teams
49794                                                        i would just lay down the throttle and dive in the lake
49823                                                   after 3 years back and this game confusion me so hard now XD
49837                                            and replay goes to wargaming becuase this is starting to be a trend

       label             lang_filter_status
38       0.0  keep_possible_gaming_or_mixed
65       1.0  keep_possible_gaming_or_mixed
100      2.0  keep_possible_gaming_or_mixed
113      0.0  keep_possible_gaming_or_mixed
168      0.0  keep_possible_gaming_or_mixed
...      ...                            ...
49714    2.0  keep_possible_gaming_or_mixed
49755    1.0  keep_possible_gaming_or_mixed
49794    0.0  keep_possible_gaming_or_mixed
49823    0.0  keep_possible_gaming_or_mixed
49837    0.0  keep_possible_gaming_or_mixed

[981 rows x 3 columns]

Label distribution among possible gaming/mixed rows:
label
0.0    0.662589
1.0    0.220183
2.0    0.090724
3.0    0.020387
4.0    0.004077
5.0    0.002039
Name: proportion, dtype: float64

Confident Latin-script non-English documents to drop:
                                                                                                                                                          message  \
957                                                                 jeszcze t54 zespotowany byl wczesniej wiec widac ze jedzie i chuj nawet jeden sie nie ruszyl
1373   Hali! A MAATT kl??n akt??v j??t??kosokat keres. A WN8 nem sz??m??t. J?? t??rsas??g, k??telezetts??gek n??lk??l. Ha ??rdekel keress, k??szi. Sry for spam.
1527                                                                                                          tu ecris ce que tu veux, dans la mesure du correct
1695                                                Den Sinn von Funk erkannt, aber kein TS? Nutz unseres: Eiserne-Krieger.de - Uns gibt es schon ÜBER 10 Jahre!
2002                                                                           ich checkls nicht seit wann lässst man diese seite so offen seit ihr behindert???
3070                                                                                                         Aufgeklärt bei Position E3. Etwas Hilfe währe nett!
3649                                                                                         Danke Type das ich deinen Job gemacht habe... du dummer Flackhelfer
3704                                                                                                         no wlasnie stojac za mna gdzie ja trzymalem pozycje
4018                                                                                                         Aufgeklärt bei Position D3. Etwas Hilfe währe nett!
4061                Les fr??res d'armes [L_F_A] recrutent.Clan francophone, nous cultivons un ??tat d'esprit ouvert.Pas d'obligations, de la bonne humeur,.me MP
4188                                                                                         FASZYSTOWSKIE ŚWINIE WOTOWSKA WAGNEROWSKA BANDA WSPIERAJĄCA FASZYZM
5075                                                                                                  meine sch??sse prallen ab und ich platze nach einem schu??
5687                                                                                               shut up froschschenkelfresser oder laber in englisch du pussy
6845                                                                             protože jsem dostával do neviditelnýho gsoru a nikdo ho nebyl schopnej spotnout
7004                                                                                              scheiss camper idioten löscht das game und geht lieber wichsen
7840                                                                                                        nevím jak můžete hrát tuto hru tak pojebaně vy mrdky
8292                                                                                              stul pysk, durniu, naotwartej mapie wystawiasz durny łeb artom
8438                                                                               Szukasz klanu ? Zapraszamy do -AP- Po więcej info zapraszam priv po bitwie ;)
9349                                                                             twoja stara ma parkinsona e tak sie bujasz tym czolgiem niedojebancu pierdolony
9678                                                                               ach, zdalne... pamiętam zdalną sesję na uczelni, bez problemu szło ściągać xd
9760                                                       mindenre alkalmatlan volt az angolok ingyen adták az oroszoknak mert beolvasztani iscsak kölcség volt
10942                                                                                      deszcze nie spokojne potargaly sad a ja musze tym zlomem dzisiaj grac
13517                     man muss hier nur ein Jude, Kommunist, Slave, Alliierter, Pedophiler, Massenm??dersein und deutsche hassen, dann macht WG dein acc gut
13848                                                                 no nie twoja bo ja chujowo podjechalem ale pozniej na cholere przyjacielu mnie blokowales?
14095                                                           ja pierdole jak sa tacy gracze jak ty to srednio rozwiniety szympans ma wiecej rozumu od ciebie'
15136                                                                     usta ben 60tp kasıyorum 8 seviyedeyim 9u alınca beaber oynarız tekrar sana iyi oyunlar
15305                                                                               ten jeo kolega gra lepiej od Ciebie i nie wpierdala sie tam gdzie nie trzeba
15938                                                                                                       meinst du jetzt chess algeimein oder den clan direkt
16602                                                                                                         a nie moja wina ze mnie pchasz zeby w arte trsafic
17013                                                                                                      nyomornc rtetkes kurva anyátok remélem már megdölgött
17222                                                                                                      abi 10 el oynad??m bu kadar ??erefsiz bir oyun olamaz
20287                                                                                siema opłaca sie dokupic stabe bo mam dosyłacz i wente oczywiscie fioletowe
20538                                                                                                       ha zavar az 1es tier akkor mehetünk tier 8 ha akarod
21230                                                                                               son una mierda, tengo que defender porque casi nadie lo hace
21352                                                                                                        Aufgeklärt bei Position F1. Etwas Hilfe währe nett!
22109                                                                                  za pocetak samo da jebem mater svi ljudima sto prave ovu retardiranu igru
22274                                                                                                    Nowo powstały klan NIPL rekrutacja otwarta,zero wymagań
22986                                                            niech ten twoj kolega naiuczy sie grac kołowecem a nie wpiedala sie na kazdego a zas ma problem
23056                                                                                                        Aufgeklärt bei Position D3. Etwas Hilfe währe nett!
23898                                                                                na polibudzie sobie nie poradziłem na drugim roku, więc łatwiejsze wybrałem
24182                                                                                                        Aufgeklärt bei Position F2. Etwas Hilfe währe nett!
24923                                                  Salut,clanul GLADIATORII asteapta jucatori,cine doreste,rog contactati-ma sau aplicati la clan,multumesc!
24992                                                                     ja to jeszcze 4 kalsa szkoly zostala ale w maku robie takze potencjał poza skale siega
25018                                       nie blokowałem aby sie zatrzymałem i stałem w miejscu a jak mnie pchałes to wciskałem W aby nie ruszyc sie z mijesca
26771                                                                                       kurwa kocham ta gre 80% pierwszych bitew arta = himel a ht malinowka
27163                                                                             ruszki681212 (05.05.2023 0:51:45) kurd meg a retkes kurva anyád te csaló féreg
28201                                                                                                        Aufgeklärt bei Position C3. Etwas Hilfe währe nett!
28536                                                                                                         herrlich gibnt es heute nur 10e matche für mich ..
29157                                                                                                        Aufgeklärt bei Position G2. Etwas Hilfe währe nett!
30848                                                                                    WY KURWY JEABane slepe mam nadzieje ze kruwa kazdy was na raka zdechnie
32584                                                                                          wr a co to kurwa jest niedojebany kacapski obciagaczu ruskich faj
32835                                 Bonjour ! Clan Fr. Nous recrutons&quot;AV424-LES TEMPLIERS DE FRANCE ET DE NAVARRE !!Discord et"casque de chantier » !!!!!
33231                                                                                                      fast alle auf einer Seite kann nicht funktionieren!!!
33373                                                                                                        Aufgeklärt bei Position H1. Etwas Hilfe währe nett!
33456                                                                 FR ROCK recrute francophones, voir conditions sur http://eu.wargaming.net/clans/500071861/
33832                                                                                                        Aufgeklärt bei Position F2. Etwas Hilfe währe nett!
33851                                                                                                     pierdolona cioto z ciezkiego w warcabi idz grac debilu
35655                                                                                                     wer sich schon joergimaus nennt... ab zum CSD du vogel
36197                                      majac takich graczy jak ty to i ma sie takie zjebane bitwy ze stoisz i chuja obisz ciapata kurwo z pod napleta putina
36915                                      salaklar arkanızda ben varım amk malları biraz düzgün oynasaydınız adamların anasını sikerdim 2700 hasarım var botlar
37286                                                                                                         no kurwa jebana, nie mia??o jakiej mapy polosowa??
39268                                      twoj stary debil ze sie nie spuscil na kupe lajn zeby ciebie nie splodzic ale pewnie twoja stara to kurwa alimenciara
39573                                                                                  ja rozumie byc slabym graczem ale zeby miec 20k i 300 wn8 to juz przesada
39835                                                          agyonbaszott buffolt szartartály mattilda a valóságban a világ valaha volt legszarabb tankja volt
40150                                                                          mam już pracę stałą. Od ręki mnie zatrudnili ze względu na znajomość francuskiego
41445                                                                                a jak jestes slepy i nie widzisz jak sie na kogos pchasz, to okulista czeka
42014                                                                                               eka t???? oma samanlainen vaunu puski tohon samaan kohtaan..
42416                                                                                                        Aufgeklärt bei Position C3. Etwas Hilfe währe nett!

In [9]:
# save to parquet
wot_lang_clean.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

# evaluate impact 
preprocessing_impact = eval_step("after_noneng_drop", preprocessing_impact, datasets = ("WoT",))
preprocessing_impact

             step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_noneng_drop     WoT 49773    0.4922       0.8683        0.5921           0.4788         -0.0054           0.0          -0.0011

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011

Decreases in metrics are within noise.

#### Duplicates

In [10]:
# look at dataset with duplicates 
wot_dup = wot_lang_clean[wot_lang_clean.duplicated(subset="message", keep=False)].sort_values("message")
# look at some examples
wot_dup.head(10)

       index  message  label
14235  31613        !    0.0
39883   6872        !    0.0
43647  40582        !    0.0
45639   1278     !!!!    0.0
27680  39948     !!!!    0.0
33470  32907     !!!!    0.0
9468   16596        #    0.0
11562   8848        #    0.0
2637   35311  #ERROR!    0.0
10519  23725  #ERROR!    0.0

In [11]:
# top 100 duplicated messages
wot_dup["message"].value_counts(ascending=False).head(100)

message
gg                   3188
lol                   458
nice                  396
gj                    315
wtf                   201
                     ...
fu                     26
reported               26
??                     26
ggg                    26
Im Spotted at G2!      26
Name: count, Length: 100, dtype: int64

Most of these duplicates are useful and important data to train or models for detecting toxicity. We need to check for same messages but different labels.

In [12]:
# Look for duplicates with same messages but different labels
conflicts = wot_lang_clean.groupby("message")["label"].nunique()
conflicts = conflicts[conflicts > 1]

conflict_rows = wot_lang_clean[wot_lang_clean["message"].isin(conflicts.index)].sort_values("message")

# Check how large is the proportion of conflicting duplicates
conflict_pct = len(conflict_rows) / len(wot_lang_clean) * 100
print(f"Proportion of messages with conflicting labels: {conflict_pct:.2f}%")
print(f"Number of messages with conflicting labels: {len(conflict_rows)}")

Proportion of messages with conflicting labels: 14.66%
Number of messages with conflicting labels: 7298

In [13]:
# check conflicting rows 
conflict_rows

       index                      message  label
44262  24318                      #ERROR!    0.0
10272  19840                      #ERROR!    0.0
32084  13407                      #ERROR!    0.0
36961  14302                      #ERROR!    0.0
42479  14881                      #ERROR!    0.0
...      ...                          ...    ...
21216  44232                     you lost    2.0
21116  13279                     you lost    1.0
45823  17220                     you lost    0.0
5423    1393  you wanna loose that right?    1.0
28087   9108  you wanna loose that right?    2.0

[7298 rows x 3 columns]

These messages can not be used for analysis, since it is a problem of `annotation`. Using them will be equal to guessing. Duplicated rows account for 14% of the data, which is a huge loss but we can not use that.

In [14]:
# drop conflicting messages
wot_dup = wot_lang_clean[~wot_lang_clean["message"].isin(conflicts.index)].reset_index(drop=True)
print(wot_dup.shape)

(42475, 3)

In [15]:
# save again and evaluate 
wot_dup.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)
preprocessing_impact = eval_step("after_duplicates_removal", preprocessing_impact, datasets = ("WoT",))

                    step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_duplicates_removal     WoT 42475    0.4919       0.8658        0.5711           0.5091         -0.0003        -0.021           0.0303

In [16]:
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303

This did not work, our score started decreasing. Instead of dropping duplicated conflicting labels, we assign a majority label to each.

In [17]:
# majority label for similar words 
majority_label = wot_lang_clean.groupby("message")["label"].agg(lambda x: x.value_counts().index[0])

# drop duplicates and map majority label 
wot_deduped = wot_lang_clean.copy()
wot_deduped["label"] = wot_deduped["message"].map(majority_label)

# check same ex duplicates 
wot_deduped[wot_deduped["message"].isin(conflicts.index)][["message", "label"]].head(20)

               message  label
4                  lol    0.0
11             #ERROR!    0.0
18                 bot    1.0
23              retard    1.0
46   Im Spotted at H6!    0.0
47                  ty    0.0
53                  ns    0.0
62                 wtf    2.0
64             #ERROR!    0.0
85              idiots    1.0
86           holy shit    0.0
89            eat shit    2.0
92           game over    2.0
96                  gg    0.0
98                  :(    0.0
108                 gg    0.0
116                 gg    0.0
120                 gg    0.0
126                 gg    0.0
127                 gg    0.0

In [18]:
# save again and evaluate 
wot_deduped.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)
preprocessing_impact = eval_step("after_duplicates_majority_map", preprocessing_impact, datasets = ("WoT",))
preprocessing_impact

                         step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_duplicates_majority_map     WoT 49773    0.5291       0.8778        0.6233           0.5106          0.0372        0.0522           0.0015

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015

That is the best we can do and it actually improves the score.

#### Data Artifacts

In [19]:
# #ERROR! entries
error_count = wot_deduped["message"].str.contains(r"#ERROR!", regex=False, na=False).sum()
print(f"#ERROR! messages: {error_count}")

# HTML entities
html_mask = wot_deduped["message"].str.contains(r"&\w+;", regex=True, na=False)
print(f"Messages with HTML entities: {html_mask.sum()}")
wot_deduped[html_mask][["message", "label"]].head(10)

#ERROR! messages: 171
Messages with HTML entities: 148

                                                message  label
24                                                &lt;#    0.0
128                                              &gt;bz    0.0
293                                               &lt;3    0.0
385                                               &lt;3    0.0
456   I've gotten all city maps today so I was like ...    0.0
553   czech_mad_man[BD_CR] (Centurion 7/1), you‘re B...    0.0
1244                           tog &amp; roll !! ladies    0.0
1625                                           &quot;_)    0.0
2724                                              &lt;3    0.0
2781                                              &lt;3    0.0

In [20]:
import re
import html as html_lib
import pandas as pd

# artifact cleaning
# goal: remove generic technical artifacts, not game-specific phrases
# use wot_deduped as input from the previous preprocessing step

wot_clean = wot_deduped.copy()

# convert messages to string and fill missing values
wot_clean["message"] = wot_clean["message"].fillna("").astype(str)

# decode HTML entities inline
# example: &quot; -> ", &amp; -> &
wot_clean["message"] = wot_clean["message"].apply(html_lib.unescape)

# generic artifact patterns
# no game-specific hardcoding here
ERROR_RE = re.compile(r"#ERROR!", flags=re.IGNORECASE)
URL_RE = re.compile(r"https?://\S+|www\.\S+", flags=re.IGNORECASE)
HTML_TAG_RE = re.compile(r"<[^>]+>", flags=re.IGNORECASE)

# after html.unescape, most entities should disappear
# this catches remaining malformed/unresolved entities
HTML_ENTITY_RE = re.compile(r"&[a-zA-Z]+;|&#\d+;|&#x[0-9a-fA-F]+;")


# classify artifact reason for each row
def artifact_status(text):
    text = str(text)

    if ERROR_RE.search(text):
        return "drop_error"

    if URL_RE.search(text):
        return "drop_url"

    if HTML_TAG_RE.search(text):
        return "drop_html_tag"

    if HTML_ENTITY_RE.search(text):
        return "drop_unresolved_html_entity"

    return "keep"


# apply artifact detection
wot_clean["artifact_status"] = wot_clean["message"].apply(artifact_status)

# inspect artifact counts
print("Artifact status counts:")
print(wot_clean["artifact_status"].value_counts())

# rows to drop
artifact_mask = wot_clean["artifact_status"].ne("keep")

# inspect dropped artifacts
with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nArtifact rows to drop:\n",
        wot_clean.loc[
            artifact_mask,
            ["message", "label", "artifact_status"]
        ]
    )

# label distribution sanity check
print("\nLabel distribution before artifact drop:")
print(wot_deduped["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after artifact drop:")
print(
    wot_clean.loc[~artifact_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nLabel distribution among dropped artifact rows:")
print(
    wot_clean.loc[artifact_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

# create artifact-cleaned dataset
wot_artifact_clean = (
    wot_clean
    .loc[~artifact_mask]
    .drop(columns=["artifact_status"])
    .reset_index(drop=True)
)

print(f"\nRows before artifact drop: {len(wot_deduped)}")
print(f"Dropped {artifact_mask.sum()} ({artifact_mask.sum() / len(wot_deduped):.1%})")
print(f"Rows after artifact drop: {len(wot_artifact_clean)}")

Artifact status counts:
artifact_status
keep             49579
drop_error         171
drop_html_tag       16
drop_url             7
Name: count, dtype: int64

Artifact rows to drop:
                                                                                                              message  \
11                                                                                                           #ERROR!
64                                                                                                           #ERROR!
65                                                     Awww... show me on the tank where the bad arty touched you...
168    https://www.twitch.tv/malpa_gaming_ha_ha KONKURS NA ZLOTO I PREMIUM TANKS ..GIVEWAY FOR GOLD AND PREMIUM TANK
917                                                                                                          #ERROR!
978                                                                                                          #ERROR!
1116                                                                                                         #ERROR!
1799                                                                                                         #ERROR!
1800                                                                                                         #ERROR!
2077                                                                                                 www.xvideos.com
2322                                                                                                         #ERROR!
2637                                                                                                         #ERROR!
4297                                                                                                         #ERROR!
4423                                                        Enemy SPG <font color='#fe7903'>killerkirby99_2013 (M44)
4918                                                                                                         #ERROR!
5248                                                                                                         #ERROR!
6661                                                                                                         #ERROR!
6680                                                                                                         #ERROR!
6771                                                                                                         #ERROR!
6948                                                                                                         #ERROR!
7023                                                                                                         #ERROR!
7181                                                                                                         #ERROR!
7233                                                                                                         #ERROR!
7320                                                                                                         #ERROR!
7531                                                                                                         #ERROR!
7609                                                                                                         #ERROR!
7630                                                                                                         #ERROR!
8124                                                                                      www.twitch.tv/vylizsikapsu
8383                                                                                                         #ERROR!
8539                                                                                                         #ERROR!
8661                                                                                                         #ERROR!
8750                                                                                                         #ERROR!
8958                                                         <font color='#f8f400'>TheAmiableReaper[BABNS] (T-34-85)
9170                                                                                                         #ERROR!
9287                                                                    Enemy SPG <font color='#f8f400'>sp0ks (S-51)
9899                                                                                      www.twitch.tv/vylizsikapsu
10272                                                                                                        #ERROR!
10406                                                                                                        #ERROR!
10460                                                                                                        #ERROR!
10519                                                                                                        #ERROR!
11057                                                                                                        #ERROR!
11871                                              Enemy SPG <font color='#fe0e00'>gonzales_3 (Lorraine 155 mle. 50)
11975                                                                                                        #ERROR!
12002                                                                                                        #ERROR!
12650                                                                                                        #ERROR!
12967                                                                                                        #ERROR!
12984                                                                                                        #ERROR!
13261                                                                                                        #ERROR!
13287                                             Enemy SPG <font color='#fe7903'>Leopard1965 (Lorraine 155 mle. 50)
13389                                                                                                        #ERROR!
13562                                                                                                        #ERROR!
13656                                                                                                        #ERROR!
13739                                                                                                        #ERROR!
13829                                                                               https://www.twitch.tv/yung_xd ??
13954                                                                                                        #ERROR!
13979                                                                                                        #ERROR!
15024                                                                                                        #ERROR!
15729                                                                                                        #ERROR!
16397                                                                                                        #ERROR!
16415                                                                                                        #ERROR!
16877                                                                                                        #ERROR!
17260                                                                                                        #ERROR!
17289                                                                                                        #ERROR!
17906                                                            Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)
17907                                                                                                        #ERROR!
17910                                                                                                        #ERROR!
18175                                              Enemy SPG <font color='#fe0e00'>gonzales_3 (Lorraine 155 mle. 50)
18247                                                                                                        #ERROR!
18337                                                                                                        #ERROR!
18410                                                                                                        #ERROR!
18423                                                   Enemy SPG <font color='#fe0e00'>WMBB (Bat.-Châtillon 155 58)
18480                                                                                                        #ERROR!
18583                                                                                                        #ERROR!
18623                                                                                                        #ERROR!
18880                                                                                                        #ERROR!
19012                                      https://open.spotify.com/track/03RojRDRvvbFEPpabo3Aan?si=ef083469698742a4
19677                                                                                                        #ERROR!
19837                                                                                                        #ERROR!
20061                                                                                                        #ERROR!
20248                                                                                                        #ERROR!
20698                                                                                                        #ERROR!
21169                                                                                                        #ERROR!
21737                                                                                                        #ERROR!
21747                                                                                                        #ERROR!
21847                                                                                                        #ERROR!
22241                                                                                                        #ERROR!
23079                                                                                                        #ERROR!
23129                                                                                                        #ERROR!
23388                                                                                                        #ERROR!
23705                                                                                                        #ERROR!
24447                                                                                                        #ERROR!
24808                                                                                                        #ERROR!
24855                                                            Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)
25015                                                                                                        #ERROR!
25535                                                                 Enemy SPG <font color='#fe7903'>pampos98 (M44)
25810                                                                                                        #ERROR!
26114                                                                                                        #ERROR!
26713                                                                                                        #ERROR!
26784                                                                                                        #ERROR!
26796                                                                                                        #ERROR!
26892                                                                                                        #ERROR!
26967                                                                                                        #ERROR!
27111                                                                                                        #ERROR!
27927                                                                                                        #ERROR!
28245                                                                                                        #ERROR!
28365                                                                                                        #ERROR!
28496                                                                                                        #ERROR!
28981                                                                                                        #ERROR!
29147                                                                                                        #ERROR!
29355                                                                                                        #ERROR!
29361                                                                                                        #ERROR!
29778                                                                                                        #ERROR!
30423                                                                                                        #ERROR!
30489                                                                                                        #ERROR!
30883                                                                                                        #ERROR!
31199                                                                                                        #ERROR!
31836                                                                                                        #ERROR!
31924                                                                                                        #ERROR!
32076                                                                                                        #ERROR!
32084                                                                                                        #ERROR!
32263                                                                                                        #ERROR!
32496                                                                                                        #ERROR!
32532                                                                                                        #ERROR!
32757                                                                                                        #ERROR!
32775                                                          Enemy SPG <font color='#fe7903'>PECHOLATA_65 (Hummel)
32908                                                                                                        #ERROR!
32985                                                                                                        #ERROR!
33346                                                                                                        #ERROR!
33432                                                                                                        #ERROR!
33591                                                                                                        #ERROR!
33629                                                                                                        #ERROR!
33677                                                                                                        #ERROR!
33721                                                                                                        #ERROR!
33995                                                                                                        #ERROR!
34068                                                                                                        #ERROR!
34487                                                                                                        #ERROR!
34683                                                                                                        #ERROR!
35542                                                                                                        #ERROR!
35713                                                                                                <base64encoded>
35788                                                                                                        #ERROR!
35852                                                                                                        #ERROR!
35979                                                                                                        #ERROR!
36378                                                                        <font color='#fe7903'>Monk_Bonk (Luchs)
36436                                                                                                        #ERROR!
36646                                                                                                        #ERROR!
36961                                                                                                        #ERROR!
37479                                                                                                        #ERROR!
37679                                                                                                        #ERROR!
37887                                                                                                        #ERROR!
38015                                                                                                        #ERROR!
38416                                                                                                        #ERROR!
38654                                                                                                        #ERROR!
38727                                                                                                        #ERROR!
38806                                                                                                        #ERROR!
39056                                                                                                        #ERROR!
39246                                                                                                        #ERROR!
39785                                                                                                        #ERROR!
39864                                                                                                        #ERROR!
40337                                                                                                        #ERROR!
40347                                                                                                        #ERROR!
40816                                                                                                        #ERROR!
40957                                                                 Enemy SPG <font color='#fe7903'>pampos98 (M44)
41449                                                                                                        #ERROR!
41506                                                                                                        #ERROR!
41958                                                                                                        #ERROR!
42009                                                                                                        #ERROR!
42115                                                                                                        #ERROR!
42466                                                                                                        #ERROR!

In [21]:
# save again and evaluate 
wot_artifact_clean.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)
preprocessing_impact = eval_step("after_artifacts_removal", preprocessing_impact, datasets = ("WoT",))

                   step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_artifacts_removal     WoT 49579      0.53       0.8772        0.6118           0.5181          0.0009       -0.0115           0.0075

In [22]:
# check 
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075

#### Mislabeled data

In [23]:
# few top rows of the data
wot_artifact_clean.head(10)

   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0
3  25964                      3 gunmark    0.0
4  28643                            lol    0.0
5   4313             i softened him lol    0.0
6   8765                           come    0.0
7  52567            stupid kids grow up    1.0
8  24437          fking light diference    0.0
9  41928                   hori, info ?    0.0

In [24]:
# class distribution check
print("Label distribution after cleaning:")
print(wot_artifact_clean["label"].value_counts(normalize=True).sort_index())

Label distribution after cleaning:
label
0.0    0.811916
1.0    0.137034
2.0    0.043890
3.0    0.005244
4.0    0.001372
5.0    0.000545
Name: proportion, dtype: float64

We might have mislabeled toxicity data that was classified as non-toxic or opposite. We need to detect and fix that as well.

In [25]:
from cleanlab.filter import find_label_issues
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_predict, StratifiedKFold
import numpy as np

# exclude messages under 3 chars — no signal, cleanlab guesses randomly on them
cl_mask = wot_artifact_clean["message"].str.len() >= 3
cl_df = wot_artifact_clean[cl_mask].reset_index(drop=True)

X = cl_df["message"].values
y = cl_df["label"].astype(int).values

# stratified cv with shuffle — avoids ordering bias in folds
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=7524)

# lightweight pipeline to generate calibrated out-of-fold probabilities
# class_weight="balanced" — needed with imbalanced data so minority class errors are detected
# LR required (not SVC) — cleanlab needs predict_proba, not decision_function
pipe = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_df=0.95,
                              sublinear_tf=True, norm="l2",
                              analyzer="word", tokenizer=tokenize, token_pattern=None)),
    ("clf", LogisticRegression(max_iter=1000, random_state=7524, class_weight="balanced")),
])

# each sample predicted by model that never saw it during training
oof_probs = cross_val_predict(pipe, X, y, cv=cv, method="predict_proba", n_jobs=-1)

# normalized_margin more robust than self_confidence on imbalanced data —
# only flags rows where model is confident another class is correct, not just uncertain
issue_idx = find_label_issues(
    labels=y,
    pred_probs=oof_probs,
    return_indices_ranked_by="normalized_margin",
)

predicted = oof_probs[issue_idx].argmax(axis=1)
given = y[issue_idx]

# only trust 0 - {1,2,3} boundary crossings —
# class 4/5 too rare (< 1%) for reliable OOF predictions, causes kill/die false positives
boundary_mask = (
    ((given == 0) & np.isin(predicted, [1, 2, 3]))
    | (np.isin(given, [1, 2, 3]) & (predicted == 0))
)
issue_idx = issue_idx[boundary_mask]

print(f"Suspected mislabeled: {len(issue_idx)} ({len(issue_idx)/len(y):.1%})")

# inspect top 50 — compare original label vs what model predicted
print(cl_df.iloc[issue_idx[:50]][["message", "label"]].assign(
    predicted=oof_probs[issue_idx[:50]].argmax(axis=1)
))

# map issue positions in cl_df back to wot_artifact_clean original index
original_idx = wot_artifact_clean[cl_mask].index[issue_idx]

Suspected mislabeled: 2781 (6.4%)
                           message  label  predicted
41327        they call me an idiot    0.0          1
37108         nicalo idiot and all    0.0          1
8809                 cromvel idiot    0.0          1
38361               idiot campersw    0.0          1
4075                     its a bot    0.0          1
29660                      top bot    0.0          1
6796                     its a bot    0.0          1
23674      wtf i win this and loss    0.0          2
8367                      just bot    0.0          1
7363              top tier top bot    0.0          1
25413               and an afk bot    0.0          1
32693                  t1heavy bot    0.0          1
22714             top tier top bot    0.0          1
14687              S5 was a bot :/    0.0          1
11208               you idiot meds    0.0          1
36990               haftoo be bots    0.0          1
40521                     omg bots    0.0          1
5325           so am i.. im a noob    0.0          1
30663                    lol moron    0.0          1
39694                too many bots    0.0          1
29720                     omg bots    0.0          1
36223                    fckg bots    0.0          1
7946              tem full of bots    0.0          1
40894                        *bots    0.0          1
7232                help your bots    0.0          1
17206               help your bots    0.0          1
19154                su move idiot    0.0          1
19920                     you -gay    0.0          3
42171                  you are gay    0.0          3
6478                        to bot    0.0          1
27908        stupid retard campers    0.0          1
28396                    me bot...    0.0          1
10276             was that a bot??    0.0          1
10231                     idiot Wt    0.0          1
28182                      go bots    0.0          1
19276        just come help idiots    0.0          1
37048    This Tiger gotta be a bot    0.0          1
24078     cmon man when ur spotted    1.0          0
17282         amx you stupid idiot    0.0          1
28917             top tier mongols    0.0          3
30859         come and help me ffs    0.0          2
33678                 time to lose    0.0          2
18307                      we lose    0.0          2
28496  why play, gonna lose anyway    0.0          2
35357    thats why you always lose    0.0          2
6688                dont lose this    0.0          2
8371                       we lose    0.0          2
17507               all go or lose    0.0          2
22634                idiot heavies    0.0          1
6381                   retard team    0.0          1

In [26]:
# copy to preserve original — relabeling wot_clean1, wot_clean stays untouched
wot_clean1 = wot_artifact_clean.copy()
wot_clean1.loc[original_idx, "label"] = oof_probs[issue_idx].argmax(axis=1)

print(f"Relabeled {len(issue_idx)} rows ({len(issue_idx)/len(wot_clean1):.1%})")

Relabeled 2781 rows (5.6%)

In [27]:
# save again and evaluate 
wot_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)
preprocessing_impact = eval_step("after_labels_fix", preprocessing_impact, datasets = ("WoT",))

            step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_labels_fix     WoT 49579    0.6109       0.9116        0.6969            0.615          0.0809        0.0851           0.0969

In [28]:
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969

That might be a model inflation. Let's check if gains are real with other model.

In [29]:
from sklearn.svm import LinearSVC

# impact 
preprocessing_impact = eval_step("after_labels_fix_svc", preprocessing_impact,
                                  datasets=("WoT",),
                                  clf=LinearSVC(max_iter=2000, random_state=7524, 
                                                class_weight = "balanced"))
preprocessing_impact

                step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_labels_fix_svc     WoT 49579    0.6303       0.9218        0.6359           0.6642          0.0194        -0.061           0.0492

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969
7,after_labels_fix_svc,WoT,49579,0.6303,0.9218,0.6359,0.6642,0.0194,-0.0610,0.0492

There's still a risk that the score gains are inflated, however the data cleaning is real and coherent.

#### Final verification

In [30]:
# basic data checks
print("=== Shape ===")
print(wot_clean1.shape)

print("\n=== Nulls ===")
print(wot_clean1.isnull().sum())

print("\n=== Overall label distribution ===")
counts = wot_clean1["label"].value_counts().sort_index()
pct = wot_clean1["label"].value_counts(normalize=True).sort_index().mul(100).round(2)
print(pd.DataFrame({"count": counts, "pct%": pct}))

=== Shape ===
(49579, 3)

=== Nulls ===
index      0
message    0
label      0
dtype: int64

=== Overall label distribution ===
       count   pct%
label
0.0    38993  78.65
1.0     6927  13.97
2.0     3191   6.44
3.0      373   0.75
4.0       68   0.14
5.0       27   0.05

In [31]:
# save to parquet for easier loading in future steps
wot_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

## Dota

**Dota**
| Class | Label |
|---|---|
| 0 | Other (non-toxic) |
| 1 | Ego |
| 2 | Aggression |
| 3 | Impolite |

#### Inspect each split

In [32]:
# import data
train = pd.read_csv(DATA_DIR_DOTA / "CONDA_train.csv")
val = pd.read_csv(DATA_DIR_DOTA / "CONDA_valid.csv")

# inspect each split
for name, df in [("train", train), ("val", val)]:
    print(f"--- {name} ---")
    print(f"Shape: {df.shape}\n")
    print(f"Columns: {list(df.columns)}\n")
    print(f"First few rows of the data:\n{df.head(3)}\n")

--- train ---
Shape: (26921, 10)

Columns: ['Id', 'matchId', 'conversationId', 'utterance', 'chatTime', 'playerSlot', 'playerId', 'intentClass', 'slotClasses', 'slotTokens']

First few rows of the data:
      Id  matchId  conversationId utterance  chatTime  playerSlot  \
0  11263      697            3193      wow!        76           0
1  13741      843            3809       WTF      1563           5
2  22125     1412            6199   wpe wpe      2853           1

                  playerId intentClass slotClasses          slotTokens
0  ANTS IN MY EYES JOHNSON           O          O            wow (O),
1                      M.k           O          T            WTF (T),
2              Acqua Ragia           O        O O   wpe (O), wpe (O),

--- val ---
Shape: (8974, 10)

Columns: ['Id', 'matchId', 'conversationId', 'utterance', 'chatTime', 'playerSlot', 'playerId', 'intentClass', 'slotClasses', 'slotTokens']

First few rows of the data:
      Id  matchId  conversationId                 utterance  chatTime  \
0   6911      456            1987                        GG      3031
1   1512      132             509                        gg      2887
2  43138     2905           12306  GG [SEPA] nice late game      2783

   playerSlot                         playerId intentClass    slotClasses  \
0           9                               OG           O             S
1           9                             Xion           O             S
2           1  Im  good but my team is so  bad           O  S SEPA O O O

                                          slotTokens
0                                           GG (S),
1                                           gg (S),
2  GG (S), [SEPA] (SEPA), nice (O), late (O), gam...

#### Clean, merge and standardise

In [33]:
# map intentClass to numeric label consistent with WoT schema
label_map = {'O': 0, 'E': 1, 'A': 2, 'I': 3}

# add split column and map labels
train["split"] = "train"
val["split"]   = "val"

# merge train + val (no test split in CONDA)
dota = pd.concat([train, val], ignore_index=True)

# keep only relevant columns and rename to match WoT schema
dota = dota[["Id", "utterance", "intentClass", "split"]].rename(columns={
    "Id": "index",
    "utterance":   "message",
    "intentClass": "label",
})

# map string labels to numeric
dota["label"] = dota["label"].map(label_map)

# drop nulls in message (7 train + 1 val)
dota = dota.dropna(subset=["message"]).reset_index(drop=True)

# shape 
print(f"Merged shape: {dota.shape}\n")
print(f"First few rows of the data:\n{dota.head(3)}\n")
print("\nInformation about the dataset:\n")
dota.info()

Merged shape: (35887, 4)

First few rows of the data:
   index  message  label  split
0  11263     wow!      0  train
1  13741      WTF      0  train
2  22125  wpe wpe      0  train


Information about the dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    35887 non-null  int64
 1   message  35887 non-null  object
 2   label    35887 non-null  int64
 3   split    35887 non-null  object
dtypes: int64(2), object(2)
memory usage: 1.1+ MB

In [34]:
# save raw dota as baseline for ablation
dota.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_baseline_raw", preprocessing_impact, datasets=("Dota",))

             step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro
dota_baseline_raw    Dota 35887    0.7538       0.8692        0.7915           0.7288

In [35]:
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969
7,after_labels_fix_svc,WoT,49579,0.6303,0.9218,0.6359,0.6642,0.0194,-0.0610,0.0492
8,dota_baseline_raw,Dota,35887,0.7538,0.8692,0.7915,0.7288,NaN,NaN,NaN

Only `utterance`, `intentClass`, `Id`, and `split` are kept = the remaining columns (matchId, conversationId, chatTime, playerSlot, playerId, slotClasses, slotTokens) carry no linguistic content relevant to toxicity detection. Labels are mapped to integers matching the WoT schema where 0 = non-toxic. Null utterances are dropped - they carry no text signal.

#### Non-english language

Since we are going to model classifier on english data, it is important for us to detect non-english cases as many as we can.

In [36]:
# covers all major non-Latin scripts
NON_LATIN_SCRIPT = re.compile(
    r"[\u0400-\u04FF"   # Cyrillic
    r"\u4E00-\u9FFF"    # CJK unified ideographs
    r"\u3400-\u4DBF"    # CJK extension A
    r"\uF900-\uFAFF"    # CJK compatibility ideographs
    r"\u0600-\u06FF"    # Arabic
    r"\u0590-\u05FF"    # Hebrew
    r"\u3040-\u30FF"    # Japanese (Hiragana + Katakana)
    r"\uAC00-\uD7AF"    # Korean (Hangul syllables)
    r"\u1100-\u11FF"    # Korean (Hangul Jamo)
    r"\u0E00-\u0E7F"    # Thai
    r"\u0900-\u097F"    # Devanagari (Hindi)
    r"\u0980-\u09FF"    # Bengali
    r"\u0370-\u03FF"    # Greek
    r"\u10A0-\u10FF"    # Georgian
    r"\u0530-\u058F"    # Armenian
    r"\u1000-\u109F"    # Myanmar
    r"\u1780-\u17FF]"   # Khmer
)

# drop any message containing even 1 non-Latin script char
print(f"Non-english documents:\n{dota[dota['message'].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)}\n")

before = len(dota)
dota_en = dota[~dota["message"].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)
print(f"Dropped {before - len(dota_en)} ({(before - len(dota_en))/before:.1%})")
print("Label distribution before:")
print(dota["label"].value_counts(normalize=True).sort_index(), "\n")

print("\nLabel distribution after:")
print(dota_en["label"].value_counts(normalize=True).sort_index(), "\n")
print(f"Rows after the drop: {dota_en.shape[0]}")
# save new step again
dota_en.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)

Non-english documents:
    index                                   message  label  split
0    8390                       s [SEPA] v [SEPA] ツ      0  train
1   23981      sure go mid with bh [SEPA] ¯\_(ツ)_/¯      0  train
2   24030                                       Νοο      0  train
3   36141                           noob [SEPA] กาก      1  train
4   19064                                     ใจยเน      0  train
5   18820                                ညသ တေမိ  ၊      0  train
6   23983                                 ¯\_(ツ)_/¯      0  train
7   27051                              เเ [SEPA] gg      0  train
8    8391                                         ツ      0  train
9   27048                                         ื      0  train
10  37396                                        ำผ      0  train
11  25892                              ไย [SEPA] wp      0  train
12  41950                                       กาก      0    val
13  19066                                     คนไทย      0    val
14  32824                                        ทำ      0    val
15   8670  dochu....양학....... [SEPA] 일본...재패니즈몽키...      0    val
16  33829                                       戒了吧      0    val
17  24017                                 ¯\_(ツ)_/¯      0    val

Dropped 18 (0.1%)
Label distribution before:
label
0    0.741299
1    0.131273
2    0.064062
3    0.063366
Name: proportion, dtype: float64


Label distribution after:
label
0    0.741197
1    0.131311
2    0.064094
3    0.063397
Name: proportion, dtype: float64

Rows after the drop: 35869

In [37]:
# save and evaluate non-Latin drop
dota_en.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_after_nonlatin_drop", preprocessing_impact, datasets=("Dota",))
preprocessing_impact

                    step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_nonlatin_drop    Dota 35869    0.7544       0.8691         0.791             0.73          0.0006       -0.0005           0.0012

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969
7,after_labels_fix_svc,WoT,49579,0.6303,0.9218,0.6359,0.6642,0.0194,-0.0610,0.0492
8,dota_baseline_raw,Dota,35887,0.7538,0.8692,0.7915,0.7288,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7544,0.8691,0.7910,0.7300,0.0006,-0.0005,0.0012

In [38]:
import re
import pandas as pd
from lingua import Language, LanguageDetectorBuilder

# detecting Latin-script but likely non-English messages

# use all Latin-script languages supported by Lingua
# English must stay inside the detector, otherwise English text gets forced into another language
LATIN_LANGUAGES = list(Language.all_with_latin_script())

# detector for Latin-script language detection
# minimum_relative_distance: if top languages are too close, Lingua returns None instead of guessing
detector = (
    LanguageDetectorBuilder
    .from_languages(*LATIN_LANGUAGES)
    .with_minimum_relative_distance(0.25)
    .build()
)

# safety tokens: if these appear, keep the message because it may be gaming/chat English or mixed slang
SAFETY_TOKENS = {
    # gaming / chat
    "gg", "ez", "wp", "gl", "hf", "glhf", "afk", "brb", "lol", "lmao", "lmfao",
    "omg", "wtf", "stfu", "noob", "n00b", "bot", "team", "report", "ban",
    "kick", "mute", "trash", "toxic", "troll", "feed", "feeder", "int", "throw",
    "rank", "elo", "kill", "kys", "die", "fps", "lag", "ping", "server",
    "wot", "dota", "fortnite", "fn",

    # English / toxicity cues
    "you", "your", "you're", "u", "ur", "are", "is", "this", "that", "the",
    "and", "not", "dont", "don't", "fuck", "fucking", "fuk", "fck", "shit",
    "bitch", "ass", "asshole", "idiot", "stupid", "dumb", "moron", "loser",
    "suck", "sucks"
}

TOKEN_RE = re.compile(r"[a-z0-9']+", flags=re.IGNORECASE)


def get_tokens(text):
    return set(TOKEN_RE.findall(str(text).lower()))


def has_safety_token(text):
    return bool(get_tokens(text) & SAFETY_TOKENS)


# function to classify what to do with each Latin-script message
def latin_language_filter_status(text):
    text_str = str(text).strip()
    tokens = get_tokens(text_str)

    # too short - keep
    # language detection is unreliable on short gaming/chat messages
    if len(text_str) < 50 or len(tokens) < 6:
        return "keep_short"

    # possible gaming/chat/English false positive - keep
    if has_safety_token(text_str):
        return "keep_possible_gaming_or_mixed"

    lang = detector.detect_language_of(text_str)

    # ambiguous - keep
    if lang is None:
        return "keep_ambiguous"

    # English - keep
    if lang == Language.ENGLISH:
        return "keep_english"

    # confident Latin-script non-English - drop
    return f"drop_latin_nonenglish_{lang.name.lower()}"


# apply detection
dota_en_lang = dota_en.copy()
dota_en_lang["lang_filter_status"] = dota_en_lang["message"].apply(latin_language_filter_status)

# inspect groups
print("Language filter status counts:")
print(dota_en_lang["lang_filter_status"].value_counts().head(30))


# check ambiguous cases
# these are messages where Lingua did not confidently choose a language
ambiguous_mask = dota_en_lang["lang_filter_status"].eq("keep_ambiguous")

print(f"\nAmbiguous Latin-script language documents kept: {ambiguous_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nAmbiguous documents kept for now:\n",
        dota_en_lang.loc[
            ambiguous_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among ambiguous rows:")
print(
    dota_en_lang.loc[ambiguous_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# check possible gaming / mixed-language false positives
# these are messages that Lingua might classify as non-English, but contain gaming/chat/English cues
mixed_mask = dota_en_lang["lang_filter_status"].eq("keep_possible_gaming_or_mixed")

print(f"\nPossible gaming or mixed-language documents kept: {mixed_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nPossible gaming/mixed documents kept for now:\n",
        dota_en_lang.loc[
            mixed_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among possible gaming/mixed rows:")
print(
    dota_en_lang.loc[mixed_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# drop only confident Latin-script non-English rows
drop_mask = dota_en_lang["lang_filter_status"].str.startswith("drop_latin_nonenglish")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nConfident Latin-script non-English documents to drop:\n",
        dota_en_lang.loc[
            drop_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print(f"\nHow many confident Latin-script non-English documents: {drop_mask.sum()}")


# label distribution sanity check
dropped_latin_nonenglish = dota_en_lang.loc[drop_mask]

print("\nLabel distribution before Latin non-English drop:")
print(dota_en["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after Latin non-English drop:")
print(
    dota_en_lang.loc[~drop_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nLabel distribution among dropped rows:")
print(
    dropped_latin_nonenglish["label"]
    .value_counts(normalize=True)
    .sort_index()
)


# create dataset after Latin non-English drop
# keep ambiguous and mixed/gaming rows
dota_lang_clean = (
    dota_en_lang
    .loc[~drop_mask]
    .drop(columns=["lang_filter_status"])
    .reset_index(drop=True)
)

print(f"\nRows before Latin non-English drop: {len(dota_en)}")
print(f"Dropped {drop_mask.sum()} ({drop_mask.sum() / len(dota_en):.1%})")
print(f"Rows after Latin non-English drop: {len(dota_lang_clean)}")

Language filter status counts:
lang_filter_status
keep_short                          33514
keep_possible_gaming_or_mixed        2019
keep_ambiguous                        191
keep_english                          129
drop_latin_nonenglish_portuguese        6
drop_latin_nonenglish_tagalog           6
drop_latin_nonenglish_spanish           3
drop_latin_nonenglish_sotho             1
Name: count, dtype: int64

Ambiguous Latin-script language documents kept: 191

Ambiguous documents kept for now:
                                                                                                                                                                                    message  \
212                                                                                                                             hahaha [SEPA] im only 1 there no one came :( [SEPA] hahaha
451                                                                                                                                   loooooooool i wanted lc x-d [SEPA] le epig missclick
553                                                                                                        Daun [SEPA] na weavere [SEPA] i venge [SEPA] prosto ebanutie  [SEPA] lsi ebanie
669                                                                                                                                   i am 22 13 [SEPA] reprot pudge [SEPA] ty [SEPA] 1 11
775                                                                                                                eu vi [SEPA] tanto q deram [SEPA] tnc [SEPA] vai se fude [SEPA] mlk 7.1
881                                                                                                                           5200 = RO [SEPA] 5150 = radiance [SEPA] still build radiance
1045                                                                                                                                  i never died solo to am in lane [SEPA] Eveeeerrrrrrr
1668                                                                                      below 3k mmr [SEPA] 'omg, he has invis' [SEPA] 'omg, I dunno where to ward, he roams ! [SEPA] XD
2004                                                                                                                             play with me pudge [SEPA] ahahaha [SEPA] es sali ka sakin
2200                                                                                                                              mid retards [SEPA] r s o unbeliaveblay  bad lma [SEPA] O
2269                                                                                                                            daz dced [SEPA] ffs [SEPA] so good porn on pornhub.com atm
2348                                                                                                                             dive [SEPA] I got my ul [SEPA] jug [SEPA] dive [SEPA] jug
2466                                                                                                                   wew [SEPA] if we fail guys commend me ha [SEPA] if we fail [SEPA] ?
2879                                                                                                                              z [SEPA] :( [SEPA] gaben sama no more 4k please [SEPA] z
3033                                                                                                                       weooh [SEPA] GOD kahh. [SEPA] deads on arrivall .. [SEPA] weooh
3197                                                  znaete [SEPA] pered tem ka kriki slil gem [SEPA] on napisal [SEPA] *ja umeju igratj na riki s gemom* [SEPA] *chtobi ne potreatj ego*
3317                                                                                                                           he 63 sec [SEPA] go? [SEPA] maybe? [SEPA] computer restart?
3548                                                                                  oh goddddddddddddddddddddddddddddddd [SEPA] hes gotta have a buddy [SEPA] or he cant hook [SEPA] rip
4106                                                                                                                                  29 [SEPA] 28 [SEPA] 27 [SEPA] 26 [SEPA] 25 [SEPA] 24
4336                                                                                                                                   WIN [SEPA] RAKI NE DAYT WIN [SEPA] ))) [SEPA] NA PA
4513                                                                .qw3kje kowqnheui49jqwmke yqakmsd fvbr2uwieoakf8u49gjirufjnghyju3iuwjfmg h4ijuwiksdfuyiMuyijamjy879ialnbyhabhgl;gnholb
4581                                                                                                                                    B [SEPA] ' B' [SEPA] ' b ' [SEPA] its hard for him
4862                                                                                                                he`s don`t so important [SEPA] guys [SEPA] d0 [SEPA] :D [SEPA] be true
4883                                                                                                                                  SEc please [SEPA] Srg  [SEPA] SUTRALIAN ITNERNET WOO
4973                                                                                                                         let's wait [SEPA] buy back to dead? [SEPA] when Jugg got MKB?
5194                                                                                                                               whole game [SEPA] 0 [SEPA] léti [SEPA] he thinsk he did
5259                                                                                                                  ES [SEPA] JUST AFKING [SEPA] IN LANE [SEPA] FUCKED ME UP [SEPA] HARD
5653                                                                                                    noobs [SEPA] EZZZZZZZZZZZZZZ [SEPA] MUITO FACIL [SEPA] 3 ruim mid [SEPA] 3 bad mid
5850                                                                                                                          Why [SEPA] ok [SEPA] reported [SEPA] feeding? [SEPA] or what
5893                                                                                                              GIVE ME [SEPA] YEAH [SEPA] ALL CARRIES [SEPA] HAHAHA [SEPA] GGWP Guys :)
6010                                                                                                            free rosh [SEPA] free top [SEPA] free mid [SEPA] look at slark [SEPA] ))))
6123                                                                                                                                    ok fast end [SEPA] no d [SEPA] go nest [SEPA] next
6186                                                                                                 zzz [SEPA] worst game ever had [SEPA] invoker gets away 1 hp [SEPA] ta get away 1 hit
6242                                                                                                silencer [SEPA] motrher [SEPA] wjore [SEPA] whore [SEPA] nice gem [SEPA] son of a slut
6264                                                                                                                         ***N I K I T A*** DOWN !!!  [SEPA] ***N I K I T A*** DOWN !!!
6460                                                                                                                             veryyy needed [SEPA] jugg has downs [SEPA] same with riki
6464                                                                                                                                   haha [SEPA] sad game [SEPA] sad player [SEPA] muted
6571                                                                                                                    5K4 BOYZ [SEPA] 1-16 [SEPA] 4-12 [SEPA] SAME PARTY for a reason eh
6852                                                                                                                                4/5 deaths [SEPA] BAM [SEPA] BOM [SEPA] BOM [SEPA] BAm
6950                                                                                                                             maybe slark isnt useless [SEPA] maybe hes just a fuckhead
7148                                                                                                       hahahaha [SEPA] ta [SEPA] go  1v5 [SEPA] ya [SEPA] ta [SEPA] 1v5  now [SEPA] go
7172                                                                                                                                   dunno just to gob smacked [SEPA] by slark [SEPA] ya
7213                                                                                                          easy mid [SEPA] easy life [SEPA] look at my denies [SEPA] easy mid easy life
7324                                                                                    we give him mid but man so bad [SEPA] man i stay vs ds [SEPA] what i must have>? [SEPA] say me plz
7652                                                                                                                               nah [SEPA] i actuially tp'ed in  [SEPA] alone [SEPA] :/
8040                                                                                                                             nah [SEPA] wollongong [SEPA] south of sydney [SEPA] dapto
8343                                                                                                                                Atlas na bobo tanginmao [SEPA] pa cute [SEPA] HAHAHAHA
8409                                                                                                                                    :( [SEPA] my flesh spoils [SEPA] but im a robot...
8734                                                                                                                               ohhh soz [SEPA] forgot man havent played in 1 yr gagaga
8943                                                                                                                                    go paly on peru servers [SEPA] with other shitties
9144                                                                           cant win nid with shtorm  [SEPA] yea [SEPA] cant ult  [SEPA] or buy wards [SEPA] mili herto  [SEPA] on line
9601                                                                                 Meppo [SEPA] Win rate 90% [SEPA] http://www.dotabuff.com/players/113924617 [SEPA] ) [SEPA] NICE ABUSE
9849                                                                                                              haha [SEPA] rekt ? [SEPA] or wat [SEPA] SA`mi bp in mata [SEPA] De sclav
10027                                                                                                                  oh [SEPA] fucker [SEPA] hAHAHA [SEPA] HAHAHAHAHA [SEPA] LET US END?
10186                                                                                                                            ? [SEPA] 179 goldi [SEPA] so slardara [SEPA] na freefarme
10438                                                                                                                            pudge_pick{ [SEPA] If cm_pick(); yes [SEPA] If false; yes
10731                                                                                                                              HAHA LINA STILL ACT LIKE A PRO [SEPA] WTGF [SEPA] SO NC
10814                                                                                                                      easy 1k [SEPA] 1k gold [SEPA] 2k lost in a row [SEPA] dead crow
11039                                                                                                                               spectre from england but cant even talk english so sad
11124                                                                                                                                  one [SEPA] lothar [SEPA] my mid [SEPA] arcane boots
11785                                                                                                               btw [SEPA] dnt get reaped [SEPA] scepter liao [SEPA] 30 sec added time
12042                                                                                                             void 25 mins 0 ulti dropped [SEPA] ggwp [SEPA] alche mid = invo freefarm
12089                                                                                 ebaniy daun [SEPA] shas bi v 4k pati mmchike kontr pikat storma [SEPA] sin blyadi [SEPA] bedzmozgliy
12439                                                                                                         hahahahaha [SEPA] 2v5 [SEPA] hahaha [SEPA] yeah [SEPA] they win [SEPA] hahah
12824                                                                                                                                  delay [SEPA] 20 sec [SEPA] plz [SEPA] rdy [SEPA] ty
12956                                                                                                                                  my frend ... [SEPA] 2 minit..  [SEPA] w8 [SEPA] otw
14297                                                                                                                                  a bit [SEPA] high ground right now so yes, i'm hihg
15125                                                                                                    1 2 3 4 5 6 7 8 9 10 11 12 13  14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
15195                                                                                                                                 how can sm1 pick riki [SEPA] i never had [SEPA] ever
15238                                                                                                                              ghost [SEPA] zzz [SEPA] im scared of ghots [SEPA] ghost
15321                                                                                                                              fuark [SEPA] only one who didnt lose tower in lane hehe
15430                                                                                                                         1 KITER [SEPA] + 1 JUNGLE [SEPA] 1 PUDGE OFF [SEPA] AUTOLOSE
15514                                                                                                                               sladar tell me [SEPA] he rage quit [SEPA] end game plz
15544                                                                                                                                 y so slow PA [SEPA] hahaha [SEPA] wait PA i will mkb
15674                                                                                                              3 min [SEPA] pls [SEPA] connection [SEPA] problem [SEPA] reset computer
15908                                                                                                                          i havent palyed in SEA mmr [SEPA] i started ota 2 in murica
15998                                                                                                                                 1 0 0 [SEPA] 15 mib [SEPA] min* [SEPA] fine [SEPA] 
16791                                                                                                                                 qop [SEPA] please [SEPA] i thoiught wer were friends
16862                                                                                                                        wow [SEPA] qop pickers [SEPA] what a hard hero [SEPA] to play
17104                                                                                        23 min [SEPA] qop no agha [SEPA] slark just got sb [SEPA] fun times as starving pos 6 support
17123                                                                                                                                  i have to water my cactuses [SEPA] no time to pause
17298                                                                                                                                   dumbest sf [SEPA] need bodyguard [SEPA] to win mid
17331                                                                                                                haha [SEPA] HAHHA [SEPA] HAHAH [SEPA] HAHAHA [SEPA] 5 account buyers?
17337                                                                                                      fight with 3 ussles hero  [SEPA] bastard [SEPA] 1000 hp mid carry [SEPA] 900 hp
17387                                                                                                                                i avenge myself [SEPA] hahaha [SEPA] i avenge my selg
17404                                                                                                                               mga tsambahero [SEPA] heee [SEPA] mga tanga [SEPA] hoy
17474                                                                                                                       40 MIN BM  DRUM [SEPA] LETS FLAME INVOKER [SEPA] mother fucker
17598                                                                                                                             sniper lost game for them [SEPA] gyro sange yasha 13 min
17678                                                                                                                          porra perdi 400 de mmr [SEPA] nessa semana [SEPA] kkkkkkkkk
17752                                                                                                                 DASjklpfsegscg][ [SEPA] FKINNNNNNNNN MEDUSAAAAAA [SEPA] fjuck uuuuuu
17798                                                                                                              loooooolll [SEPA] fcukin retared mid [SEPA] fail mid 35 min only orchid
17950                                  OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [SEPA] OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [SEPA] OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog
18015                                                                                                                    recotnra  izi ese mid [SEPA] reporten sf pelase [SEPA] muy mierda
18060                                                                                                                            15 level hahaha nice build haha [SEPA] no carry buld haha
18288                                                                                                               bh [SEPA] Don pick bh to counter me [SEPA] uuseless [SEPA] just sentry
18298                                                                                                      +25 [SEPA] i will tell my mom i won against an alche [SEPA] Pls la [SEPA] i beg
18480                                                                                                                               CUZ MIDDLE RETARD FOR ME [SEPA] NO GANK [SEPA] NO HELP
18607                                                                                last 20 sec [SEPA] 19 [SEPA] 18 [SEPA] 17 [SEPA] 16 [SEPA] 15 [SEPA] 14 [SEPA] 13 [SEPA] 12 [SEPA] 11
18609                                                                                                                                 brain dog [SEPA] random :)) [SEPA] i know  [SEPA] 4k
18746                                                                                                           LOLOLOLOLL [SEPA] come back wisp [SEPA] ya fucken dog [SEPA] hahahahhahaha
19161                                                                                                                      come on doom [SEPA] let me 1v1 him [SEPA] he had his fair aegis
19484                                                                              wait [SEPA] 1 min [SEPA] ga bagay nasad [SEPA] wait lang jud [SEPA] please [SEPA] respect [SEPA] hahaha
19623                                                                        TAS AS BAD AS SF [SEPA] WHY CNT I GET A COMPETNENT CORE [SEPA] ONE GAME [SEPA] thank god [SEPA] he abanbdoned

In [39]:
# save to parquet
dota_lang_clean.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)

# evaluate impact 
preprocessing_impact = eval_step("after_noneng_drop", preprocessing_impact, datasets = ("Dota",))
preprocessing_impact

             step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_noneng_drop    Dota 35853    0.7514       0.8682        0.7885           0.7267          -0.003       -0.0025          -0.0033

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969
7,after_labels_fix_svc,WoT,49579,0.6303,0.9218,0.6359,0.6642,0.0194,-0.0610,0.0492
8,dota_baseline_raw,Dota,35887,0.7538,0.8692,0.7915,0.7288,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7544,0.8691,0.7910,0.7300,0.0006,-0.0005,0.0012
10,after_noneng_drop,Dota,35853,0.7514,0.8682,0.7885,0.7267,-0.0030,-0.0025,-0.0033

Decrease in CV metrics is within a noise range.

#### Data Artifacts

In [40]:
import re
import html as html_lib

# artifact cleaning for Dota — same pattern as WoT
# input: dota_en (after SEPA strip and language filter)
dota_clean = dota_lang_clean.copy()
dota_clean["message"] = dota_clean["message"].fillna("").astype(str)

# strip [SEPA] conversation separator — data collection artifact, no linguistic value
dota_clean["message"] = dota_clean["message"].str.replace(r"\s*\[SEPA\]\s*", " ", regex=True).str.strip()
print(f"[SEPA] remaining: {dota_clean['message'].str.contains(r'[SEPA]', regex=False).sum()}")

# url links 
URL_RE = re.compile(r"https?://\S+|www\.\S+", flags=re.IGNORECASE)
# html tags
HTML_ENTITY_RE = re.compile(r"&[a-zA-Z]+;|&#\d+;|&#x[0-9a-fA-F]+;")
# keyboard mash: 20+ consecutive non-whitespace chars with no vowels or mostly symbols
KEYBOARD_MASH_RE = re.compile(r"\S{20,}")

# function for classifying artifact status of each message
def artifact_status(text):
    text = str(text)
    if URL_RE.search(text):
        return "drop_url"
    if HTML_ENTITY_RE.search(text):
        return "drop_html_entity"
    if KEYBOARD_MASH_RE.search(text):
        return "drop_keyboard_mash"
    return "keep"

# apply artifact detection
dota_clean["artifact_status"] = dota_clean["message"].apply(artifact_status)

print("Artifact status counts:")
print(dota_clean["artifact_status"].value_counts())

# mask for rows to drop
artifact_mask = dota_clean["artifact_status"].ne("keep")

print("\nArtifact rows to drop:")
with pd.option_context("display.max_rows", 50, "display.max_colwidth", 120):
    print(dota_clean.loc[artifact_mask, ["message", "label", "artifact_status"]])

print("\nLabel distribution before artifact drop:")
print(dota_lang_clean["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after artifact drop:")
print(dota_clean.loc[~artifact_mask, "label"].value_counts(normalize=True).sort_index())

# create final cleaned dataset after dropping artifacts
dota_artifact_clean = (
    dota_clean
    .loc[~artifact_mask]
    .drop(columns=["artifact_status"])
    .reset_index(drop=True)
)

print(f"\nRows before: {len(dota_lang_clean)}")
print(f"Dropped: {artifact_mask.sum()} ({artifact_mask.sum()/len(dota_lang_clean):.1%})")
print(f"Rows after: {len(dota_artifact_clean)}")

[SEPA] remaining: 0
Artifact status counts:
artifact_status
keep                  35749
drop_keyboard_mash       97
drop_url                  7
Name: count, dtype: int64

Artifact rows to drop:
                                                       message  label  \
733    lol these 3 eggs these eggs are tsuyuyuy,tsokotomotoko.      0
743                                       lollllllllllllllllll      0
821                                       SOOOOOOOOOOOOOOOOBAD      0
1072                              aaahajahahahahhahahahahahaha      0
1124                                  ooooooooooooooooooooooom      0
...                                                        ...    ...
33398                   peeeeeee sorry peeeeeeeeeeeeeeeeeeeeee      0
33518                    wanted me that badddddddddddddddddddd      0
34697                        fattttttttttttttttttttttttttttttt      0
35405                     BLYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT      0
35732                hahahahahahahahahahahahahahahhahahahahaha      0

          artifact_status
733    drop_keyboard_mash
743    drop_keyboard_mash
821    drop_keyboard_mash
1072   drop_keyboard_mash
1124   drop_keyboard_mash
...                   ...
33398  drop_keyboard_mash
33518  drop_keyboard_mash
34697  drop_keyboard_mash
35405  drop_keyboard_mash
35732  drop_keyboard_mash

[104 rows x 3 columns]

Label distribution before artifact drop:
label
0    0.741165
1    0.131370
2    0.064039
3    0.063426
Name: proportion, dtype: float64

Label distribution after artifact drop:
label
0    0.740944
1    0.131444
2    0.064198
3    0.063414
Name: proportion, dtype: float64

Rows before: 35853
Dropped: 104 (0.3%)
Rows after: 35749

In [41]:
# save to parquet
dota_artifact_clean.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)

# evaluate impact 
preprocessing_impact = eval_step("after_artifact_drop", preprocessing_impact, datasets = ("Dota",))
preprocessing_impact

               step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
after_artifact_drop    Dota 35749    0.7574       0.8717         0.792           0.7334           0.006        0.0035           0.0067

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969
7,after_labels_fix_svc,WoT,49579,0.6303,0.9218,0.6359,0.6642,0.0194,-0.0610,0.0492
8,dota_baseline_raw,Dota,35887,0.7538,0.8692,0.7915,0.7288,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7544,0.8691,0.7910,0.7300,0.0006,-0.0005,0.0012
10,after_noneng_drop,Dota,35853,0.7514,0.8682,0.7885,0.7267,-0.0030,-0.0025,-0.0033
11,after_artifact_drop,Dota,35749,0.7574,0.8717,0.7920,0.7334,0.0060,0.0035,0.0067

#### Duplicates

In [42]:
# look at dataset with duplicates
dota_dup = dota_artifact_clean[dota_artifact_clean.duplicated(subset="message", keep=False)].sort_values("message")
dota_dup.head(10)

       index message  label  split
17567  11136       !      0  train
26805  38158       !      0  train
28681   7592       !      0    val
19074  42692       !      0  train
23685  24950       !      0  train
10894  32061       !      0  train
9417   35992       !      0  train
33203   1008      !!      0    val
17582   6806      !!      0  train
14375  31944    !!!!      0  train

In [43]:
# top 30 most duplicated messages
dota_artifact_clean["message"].value_counts(ascending=False).head(30)

message
gg        1466
lol        691
?          445
ggwp       355
haha       348
gg wp      316
GG         291
ez         274
LOL        192
ty         160
:D         147
hahaha     135
wp         133
XD          96
GGWP        91
ok          82
EZ          81
+           78
Gg          74
:)          73
wtf         70
rofl        65
xD          60
ez mid      59
wait        59
end         58
HAHA        58
g           55
:(          55
)           54
Name: count, dtype: int64

In [44]:
# find conflicting labels
conflicts_d = dota_artifact_clean.groupby("message")["label"].nunique()
conflicts_d = conflicts_d[conflicts_d > 1]
conflict_rows_d = dota_artifact_clean[dota_artifact_clean["message"].isin(conflicts_d.index)].sort_values("message")
conflict_pct_d = len(conflict_rows_d) / len(dota_artifact_clean) * 100
print(f"Messages with conflicting labels: {len(conflicts_d)}")
print(f"Proportion: {conflict_pct_d:.2f}%")
print(f"Rows affected: {len(conflict_rows_d)}")

Messages with conflicting labels: 147
Proportion: 13.71%
Rows affected: 4900

In [45]:
# check conflicting rows
conflict_rows_d

       index message  label  split
9238   21192       )      0  train
4506   38062       )      0  train
33727  37984       )      0    val
18484  34207       )      0  train
30978  41690       )      0    val
...      ...     ...    ...    ...
17468   7192      zz      0  train
957    22280      zz      0  train
853    30365      zz      0  train
31593  26815      zz      0    val
33741  30943      zz      2    val

[4900 rows x 4 columns]

Same as WoT - annotation noise. Dropping would lose training signal. Assign majority label instead.

In [46]:
# majority label for all messages
majority_label_d = dota_artifact_clean.groupby("message")["label"].agg(lambda x: x.value_counts().index[0])

# remap all labels to majority vote
dota_deduped = dota_artifact_clean.copy()
dota_deduped["label"] = dota_deduped["message"].map(majority_label_d)

# check former conflicting messages
dota_deduped[dota_deduped["message"].isin(conflicts_d.index)][["message", "label"]].head(55)

     message  label
1        WTF      0
3     hahaha      0
4        wtf      0
22      ggwp      0
35        gg      0
39         ?      0
48        gg      0
52        ez      3
58   ez game      3
71      HAHA      0
97        EZ      3
104     ggwp      0
105      lol      0
110      lol      0
146      LOL      0
151      lol      0
153     noob      1
156       gg      0
161     ggwp      0
162     wait      2
172     ggwp      0
175       gg      0
179      lol      0
184     ggwp      0
192       wp      0
202       gg      0
216  ez game      3
219       ez      3
228       wp      0
240   hahaha      0
246       gg      0
255       gg      0
276        ?      0
281       gg      0
295       EZ      3
319        ?      0
324      LOL      0
333       EZ      3
335       ez      3
337        ?      0
345      LOL      0
349       ez      3
361      fck      1
368        ?      0
374        ?      0
393       gg      0
394  ez game      3
402       wp      0
464       wp      0
470     easy      0
485       wp      0
486      lol      0
490        ?      0
496      sec      0
502       gg      0

In [47]:
# save and evaluate majority map
dota_deduped.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_after_majority_map", preprocessing_impact, datasets=("Dota",))
preprocessing_impact

                   step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_majority_map    Dota 35749    0.7666       0.8774        0.7961           0.7451          0.0092        0.0041           0.0117

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969
7,after_labels_fix_svc,WoT,49579,0.6303,0.9218,0.6359,0.6642,0.0194,-0.0610,0.0492
8,dota_baseline_raw,Dota,35887,0.7538,0.8692,0.7915,0.7288,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7544,0.8691,0.7910,0.7300,0.0006,-0.0005,0.0012
10,after_noneng_drop,Dota,35853,0.7514,0.8682,0.7885,0.7267,-0.0030,-0.0025,-0.0033
11,after_artifact_drop,Dota,35749,0.7574,0.8717,0.7920,0.7334,0.0060,0.0035,0.0067
12,dota_after_majority_map,Dota,35749,0.7666,0.8774,0.7961,0.7451,0.0092,0.0041,0.0117

That is the best we can do and it actually improves the score as well.

#### Mislabeled data

In [48]:
# few top rows of the data
dota_deduped.head(5)

   index  message  label  split
0  11263     wow!      0  train
1  13741      WTF      0  train
2  22125  wpe wpe      0  train
3   6453   hahaha      0  train
4   9644      wtf      0  train

In [49]:
# class distribution check
print("Label distribution after cleaning:")
print(dota_deduped["label"].value_counts(normalize=True).sort_index())

Label distribution after cleaning:
label
0    0.741503
1    0.130913
2    0.064645
3    0.062939
Name: proportion, dtype: float64

We might have mislabeled toxicity data that was classified as non-toxic or opposite. We need to detect and fix that as well.

In [50]:
from cleanlab.filter import find_label_issues
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_predict, StratifiedKFold
import numpy as np

# exclude messages under 3 chars — no signal, cleanlab guesses randomly on them
cl_mask = dota_deduped["message"].str.len() >= 3
cl_df = dota_deduped[cl_mask].reset_index(drop=True)
    
X = cl_df["message"].values
y = cl_df["label"].astype(int).values

# stratified cv with shuffle — avoids ordering bias in folds
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=7524)

# lightweight pipeline to generate calibrated out-of-fold probabilities
# class_weight="balanced" — needed with imbalanced data so minority class errors are detected
# LR required (not SVC) — cleanlab needs predict_proba, not decision_function
pipe = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_df=0.95,
                              sublinear_tf=True, norm="l2",
                              analyzer="word", tokenizer=tokenize, token_pattern=None)),
    ("clf", LogisticRegression(max_iter=1000, random_state=7524, class_weight="balanced")),
])

# each sample predicted by model that never saw it during training
oof_probs = cross_val_predict(pipe, X, y, cv=cv, method="predict_proba", n_jobs=-1)

# normalized_margin more robust than self_confidence on imbalanced data —
# only flags rows where model is confident another class is correct, not just uncertain
issue_idx = find_label_issues(
    labels=y,
    pred_probs=oof_probs,
    return_indices_ranked_by="normalized_margin",
)

predicted = oof_probs[issue_idx].argmax(axis=1)
given = y[issue_idx]

# only trust 0-toxic boundary crossings — inter-class noise not worth relabeling
boundary_mask = (given == 0) != (predicted == 0)
issue_idx = issue_idx[boundary_mask]
print(f"Suspected mislabeled: {len(issue_idx)} ({len(issue_idx)/len(y):.1%})")

# inspect top 50 — compare original label vs what model predicted
print(cl_df.iloc[issue_idx[:50]][["message", "label"]].assign(
    predicted=oof_probs[issue_idx[:50]].argmax(axis=1)
))

# map issue positions in cl_df back to dota_deduped original index
original_idx = dota_deduped[cl_mask].index[issue_idx]

Suspected mislabeled: 1983 (6.5%)
                                                 message  label  predicted
6590                                                 EZ^      0          3
21911                                              NOOB!      0          1
1922                                             im noob      0          1
19908                                       spectre noob      0          1
6115                                                 EZ)      0          3
4612                                                 ez&      0          3
13177                                            oh shit      0          1
14341                       see that shit is just spooky      0          1
3030                                 we dont give a fuck      0          1
9980               why the fuck you lion you always lion      0          1
20802                                    Intense as fuck      0          1
26230                                      WHAT THE FUCK      0          1
9284                                               FUCK!      0          1
29596                                           LOL FUCK      0          1
10023         has predicted their team will win! oh fuck      0          1
15576                                      fuck off zeus      0          1
23032                                       oh what fuck      0          1
15615                                            oh shit      0          1
28190                           and you can fuck off too      0          1
20630                                just what the fuck?      0          1
14960                             SHUT UP FUCKING NOOB !      0          1
8586                                      okay fuck shit      0          1
25615                                        LOL fucking      0          1
8388                                 the fucking keybord      0          1
29491                                  Fuck fucking zeus      0          1
13032                                           cant w8?      0          2
4779                                        fucking stop      0          1
19363                               mirana please report      0          2
18023                                  fuck your english      0          1
20692  pls just report them so that you dont get them...      0          2
14360                                        Very stupid      0          1
17146                                    ez kill ez life      0          3
7041               im confsued now, who should i report?      0          2
5743                                  report my team pls      0          2
25696                                        why report?      0          2
7399   I WILL ALWAYS SUCK HIS DICK AS LONG AS BARA WA...      0          1
4287   if everyone just fucking calms the fuck down a...      0          1
294                 invoker what the fuck are u playing?      0          1
21387                           Very well fucking played      0          1
26929       has nuthing to do with how shit tiny is lmao      0          1
1008             =)) ez mid next time pick veng not alch      0          3
19247                                  REPORT BARAT GGWP      0          2
13827     no yalll mid yalll noob y didnt u go help tiny      0          1
1606                         come on man fuck you rubick      0          1
24501                                       bg noob team      0          1
4255                                        so long fuck      0          1
24203                                           hey FUCK      0          1
7442                                     10 12 husk EZ?>      0          3
18637                           lc thejm pls sladar noob      0          1
30479                                 ez jungle you mean      0          3

Most of them are mislabeled. Let's replace labels instead of dropping.

In [51]:
# copy to preserve original — relabeling dota_clean1, dota_deduped stays untouched
dota_clean1 = dota_deduped.copy()
dota_clean1.loc[original_idx, "label"] = oof_probs[issue_idx].argmax(axis=1)

print(f"Relabeled {len(issue_idx)} rows ({len(issue_idx)/len(dota_clean1):.1%})")

Relabeled 1983 rows (5.5%)

In [52]:
# save and evaluate labels fix
dota_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)
preprocessing_impact = eval_step("dota_after_labels_fix", preprocessing_impact, datasets=("Dota",))

                 step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_labels_fix    Dota 35749    0.8488       0.9176        0.8736           0.8306          0.0822        0.0775           0.0855

In [53]:
# check 
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969
7,after_labels_fix_svc,WoT,49579,0.6303,0.9218,0.6359,0.6642,0.0194,-0.0610,0.0492
8,dota_baseline_raw,Dota,35887,0.7538,0.8692,0.7915,0.7288,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7544,0.8691,0.7910,0.7300,0.0006,-0.0005,0.0012
10,after_noneng_drop,Dota,35853,0.7514,0.8682,0.7885,0.7267,-0.0030,-0.0025,-0.0033
11,after_artifact_drop,Dota,35749,0.7574,0.8717,0.7920,0.7334,0.0060,0.0035,0.0067
12,dota_after_majority_map,Dota,35749,0.7666,0.8774,0.7961,0.7451,0.0092,0.0041,0.0117
13,dota_after_labels_fix,Dota,35749,0.8488,0.9176,0.8736,0.8306,0.0822,0.0775,0.0855

That might be a model inflation. Let's check if gains are real with other model.

In [54]:
# SVC circularity check
preprocessing_impact = eval_step("dota_after_labels_fix_svc", preprocessing_impact,
                                  datasets=("Dota",), clf=LinearSVC(max_iter=2000, random_state=7524, class_weight="balanced"))

                     step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
dota_after_labels_fix_svc    Dota 35749    0.8703       0.9313        0.8743           0.8676          0.0215        0.0007            0.037

In [55]:
preprocessing_impact

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline_raw,WoT,53701,0.4855,0.8610,0.5599,0.4696,0.0000,0.0000,0.0000
1,after_nonlatin_drop,WoT,49851,0.4976,0.8692,0.5921,0.4799,0.0121,0.0322,0.0103
2,after_noneng_drop,WoT,49773,0.4922,0.8683,0.5921,0.4788,-0.0054,0.0000,-0.0011
3,after_duplicates_removal,WoT,42475,0.4919,0.8658,0.5711,0.5091,-0.0003,-0.0210,0.0303
4,after_duplicates_majority_map,WoT,49773,0.5291,0.8778,0.6233,0.5106,0.0372,0.0522,0.0015
5,after_artifacts_removal,WoT,49579,0.5300,0.8772,0.6118,0.5181,0.0009,-0.0115,0.0075
6,after_labels_fix,WoT,49579,0.6109,0.9116,0.6969,0.6150,0.0809,0.0851,0.0969
7,after_labels_fix_svc,WoT,49579,0.6303,0.9218,0.6359,0.6642,0.0194,-0.0610,0.0492
8,dota_baseline_raw,Dota,35887,0.7538,0.8692,0.7915,0.7288,NaN,NaN,NaN
9,dota_after_nonlatin_drop,Dota,35869,0.7544,0.8691,0.7910,0.7300,0.0006,-0.0005,0.0012
10,after_noneng_drop,Dota,35853,0.7514,0.8682,0.7885,0.7267,-0.0030,-0.0025,-0.0033
11,after_artifact_drop,Dota,35749,0.7574,0.8717,0.7920,0.7334,0.0060,0.0035,0.0067
12,dota_after_majority_map,Dota,35749,0.7666,0.8774,0.7961,0.7451,0.0092,0.0041,0.0117
13,dota_after_labels_fix,Dota,35749,0.8488,0.9176,0.8736,0.8306,0.0822,0.0775,0.0855
14,dota_after_labels_fix_svc,Dota,35749,0.8703,0.9313,0.8743,0.8676,0.0215,0.0007,0.0370

There's still a risk that the score gains are inflated, however the data is now cleaner.

#### Final verification

In [56]:
print("=== Shape ===")
print(dota_clean1.shape)

print("=== Nulls ===")
print(dota_clean1.isnull().sum())

print("=== Label distribution ===")
counts = dota_clean1["label"].value_counts().sort_index()
pct = dota_clean1["label"].value_counts(normalize=True).sort_index().mul(100).round(1)
label_names = {0: "Other (O)", 1: "Ego (E)", 2: "Aggression (A)", 3: "Impolite (I)"}
print(pd.DataFrame({"count": counts, "pct%": pct}).rename(index=label_names))

=== Shape ===
(35749, 4)
=== Nulls ===
index      0
message    0
label      0
split      0
dtype: int64
=== Label distribution ===
                count  pct%
label
Other (O)       25713  71.9
Ego (E)          4790  13.4
Aggression (A)   2711   7.6
Impolite (I)     2535   7.1

In [57]:
# save cleaned dota to parquet for easier loading in future steps
dota_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)

In [58]:
# save our preprocessing rounds
preprocessing_impact.to_csv(
    PROJECT_ROOT / "data/results/cleaning_ablation.csv", 
    index=False
)
print("Saved cleaning_ablation.csv")

Saved cleaning_ablation.csv