# Gaming Toxicity Detection

**Authors:** Beibarys Nyussupov, Ruby Ngo, Paola Calle, Jett Forward

In [1]:
# libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path 
import re 
import sys
sys.path.insert(0, str(Path("../..").resolve()))

# custom functions - tokenizer, step evaluator
from src.tokenizer import tokenize
from src.prep_evaluation_multi import eval_step

# to split the data into train and test
from sklearn.model_selection import train_test_split

# reproducibility
seed = 7524
np.random.seed(seed)

# project root (notebooks/gaming/ - notebooks/ - project root)
PROJECT_ROOT = Path().resolve().parent.parent

In [2]:
# data directories
DATA_DIR_WOT  = PROJECT_ROOT / "data/raw_data/wot/"
DATA_DIR_DOTA = PROJECT_ROOT / "data/raw_data/dota/"

## World of Tanks

**World of Tanks**
| Class | Terminology |
|---|---|
| 0 | Non-Toxic |
| 1 | Insults and Flaming |
| 2 | Other Offensive Texts |
| 3 | Hate and Harassment |
| 4 | Threats |
| 5 | Extremism |

#### Inspect each split

In [3]:
# import data 
train = pd.read_csv(DATA_DIR_WOT / "train.csv")
val = pd.read_csv(DATA_DIR_WOT / "val.csv")

# test dataset 
test_text = pd.read_csv(DATA_DIR_WOT /  "test_index_text.csv")
test_label = pd.read_csv(DATA_DIR_WOT / "test_index_label.csv")

# check the data 
for name, df in [("train", train), ("val", val), ("test_text", test_text), ("test_label", test_label)]:
    print(f"--- {name} ---")
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print(f"First few rows of the dataset:\n{df.head(3)}")
    print()

--- train ---
Shape: (42959, 3)
Columns: ['index', 'message', 'label']
First few rows of the dataset:
   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0

--- val ---
Shape: (5367, 3)
Columns: ['index', 'message', 'label']
First few rows of the dataset:
   index       message  label
0  31697  e50 is there    0.0
1  52311   this scouts    0.0
2   2775       i guess    0.0

--- test_text ---
Shape: (5375, 2)
Columns: ['index', 'message']
First few rows of the dataset:
   index         message
0  17775  aim you monkey
1  28228   Pz kill artys
2  19888             ggs

--- test_label ---
Shape: (5375, 2)
Columns: ['index', 'label']
First few rows of the dataset:
   index  label
0  17775    2.0
1  28228    0.0
2  19888    0.0

The test set is stored in two separate files - text and labels indexed by the same `index` column. Train and val are already complete. We need to join the test files on `index` before merging everything.

#### Reconstruct test split and merge all

In [4]:
# merge test text and labels
test = test_text.merge(test_label, on="index", how="inner")

# concatenate all data
wot = pd.concat([train, val, test], ignore_index=True)

print(f"Test join shape: {test.shape}\n")
print(f"Merged shape: {wot.shape}\n")
print(f"First few rows of the data:\n{wot.head(3)}\n")
print(f"Information about the data: {wot.info()}")

Test join shape: (5375, 3)

Merged shape: (53701, 3)

First few rows of the data:
   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53701 entries, 0 to 53700
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    53701 non-null  int64
 1   message  53701 non-null  object
 2   label    53701 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ MB
Information about the data: None

The test join uses `inner` - any index present in only one file would be silently dropped. If test shape after join is smaller than either file's length, there is an alignment issue in the original data.

In [5]:
# X and Y
X = wot["message"]
y = wot["label"]

# split the data into our train and test 
x_train, x_validation, y_train, y_validation = train_test_split(X, y, test_size=0.2, random_state=seed, 
                                             shuffle = True, stratify=y)

# distributions for each split 
print("Distribution of labels in the training set normalized and not-normalized:")
print(y_train.value_counts())
print(y_train.value_counts(normalize=True))
print("\nDistribution of labels in the validation set normalized and not-normalized:")
print(y_validation.value_counts())
print(y_validation.value_counts(normalize=True))

# save both datasets as one parquet file each, with message and label columns,
# for easier processing in the next steps
x_train = pd.DataFrame({"message": x_train, "label": y_train})
x_validation = pd.DataFrame({"message": x_validation, "label": y_validation})
x_train.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_train.parquet", index=False)
x_validation.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_validation.parquet", index=False)

Distribution of labels in the training set normalized and not-normalized:
label
0.0    34797
1.0     5926
2.0     1874
3.0      279
4.0       60
5.0       24
Name: count, dtype: int64
label
0.0    0.809986
1.0    0.137942
2.0    0.043622
3.0    0.006494
4.0    0.001397
5.0    0.000559
Name: proportion, dtype: float64

Distribution of labels in the validation set normalized and not-normalized:
label
0.0    8700
1.0    1481
2.0     469
3.0      70
4.0      15
5.0       6
Name: count, dtype: int64
label
0.0    0.809980
1.0    0.137883
2.0    0.043664
3.0    0.006517
4.0    0.001397
5.0    0.000559
Name: proportion, dtype: float64

In [6]:
# baseline - before any cleaning
impact = None
impact = eval_step("baseline", {"WoT": PROJECT_ROOT / "data/processed_data/wot/x_train.parquet"}, impact)
impact

    step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
baseline     WoT 42960    0.4743       0.8646        0.5476           0.4626             0.0           0.0              0.0

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,WoT,42960,0.4743,0.8646,0.5476,0.4626,0.0,0.0,0.0

#### Non-english language

Since we are going to model classifier on english data, it is important for us to detect non-english cases as many as we can.

In [7]:
# detecting Non-lating-script messages 

# covers all major non-Latin characters
NON_LATIN_SCRIPT = re.compile(
    r"[\u0400-\u04FF"   # Cyrillic
    r"\u4E00-\u9FFF"    # CJK unified ideographs
    r"\u3400-\u4DBF"    # CJK extension A
    r"\uF900-\uFAFF"    # CJK compatibility ideographs
    r"\u0600-\u06FF"    # Arabic
    r"\u0590-\u05FF"    # Hebrew
    r"\u3040-\u30FF"    # Japanese (Hiragana + Katakana)
    r"\uAC00-\uD7AF"    # Korean (Hangul syllables)
    r"\u1100-\u11FF"    # Korean (Hangul Jamo)
    r"\u0E00-\u0E7F"    # Thai
    r"\u0900-\u097F"    # Devanagari (Hindi)
    r"\u0980-\u09FF"    # Bengali
    r"\u0370-\u03FF"    # Greek
    r"\u10A0-\u10FF"    # Georgian
    r"\u0530-\u058F"    # Armenian
    r"\u1000-\u109F"    # Myanmar
    r"\u1780-\u17FF]"   # Khmer
)

# drop any message containing even 1 non-Latin script char
print(f"Non-english documents:\n{x_train[x_train['message'].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)}\n")

# changes 
before = len(x_train)
x_train_en = x_train[~x_train["message"].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)
print(f"Dropped {before - len(x_train_en)} ({(before - len(x_train_en))/before:.1%})")
print("Label distribution before:")
print(x_train["label"].value_counts(normalize=True).sort_index(), "\n")

print("\nLabel distribution after:")
print(x_train_en["label"].value_counts(normalize=True).sort_index(), "\n")
print(f"Rows after the drop: {x_train_en.shape[0]}")
# save new step again
x_train_en.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_train.parquet", index=False)

Non-english documents:
                                    message  label
0     по крайслеру ніхто постріляти не може    0.0
1                   Засвет в квадрате J4!!!    0.0
2                              пидоры тупые    1.0
3                     ору в голосину просто    0.0
4                            сыны пидорасов    3.0
...                                     ...    ...
3058                Засвет в квадрате K8!!!    0.0
3059                                   сука    1.0
3060                        они все наверху    0.0
3061                          низкий поклон    0.0
3062                        ВСЕ НАДЕРЕЖАБЛЬ    1.0

[3063 rows x 2 columns]

Dropped 3063 (7.1%)
Label distribution before:
label
0.0    0.809986
1.0    0.137942
2.0    0.043622
3.0    0.006494
4.0    0.001397
5.0    0.000559
Name: proportion, dtype: float64


Label distribution after:
label
0.0    0.812567
1.0    0.136176
2.0    0.043863
3.0    0.005464
4.0    0.001353
5.0    0.000576
Name: proportion, dtype: float64

Rows after the drop: 39897

In [8]:
# check non-latin language drop
impact = eval_step("non_latin_drop", {"WoT": PROJECT_ROOT / "data/processed_data/wot/x_train.parquet"}, impact)
impact

          step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
non_latin_drop     WoT 39897     0.493       0.8699        0.5725           0.4929          0.0187        0.0249           0.0303

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,WoT,42960,0.4743,0.8646,0.5476,0.4626,0.0000,0.0000,0.0000
1,non_latin_drop,WoT,39897,0.4930,0.8699,0.5725,0.4929,0.0187,0.0249,0.0303

In [9]:
# transform that on the validation set as well, to be consistent with the training data.
# drop any message containing even 1 non-Latin script char
print(f"Non-english documents:\n{x_validation[x_validation['message'].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)}\n")

# changes 
before = len(x_validation)
x_validation_en = x_validation[~x_validation["message"].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)
print(f"Dropped {before - len(x_validation_en)} ({(before - len(x_validation_en))/before:.1%})")
print("Label distribution before:")
print(x_validation["label"].value_counts(normalize=True).sort_index(), "\n")

print("\nLabel distribution after:")
print(x_validation_en["label"].value_counts(normalize=True).sort_index(), "\n")
print(f"Rows after the drop: {x_validation_en.shape[0]}")
# save new step again
x_validation_en.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_validation.parquet", index=False)

Non-english documents:
                                       message  label
0                    кто берет в рот тот знает    0.0
1                          він просто пездоліс    1.0
2                                        т95((    0.0
3                                        козлт    0.0
4                                        блять    1.0
..                                         ...    ...
782                                  ТИГР СУКА    1.0
783                    Засвет в квадрате E8!!!    0.0
784                            вбийте дпібного    0.0
785                                 Так точно!    0.0
786  ну писать то он может, значит с монитором    0.0

[787 rows x 2 columns]

Dropped 787 (7.3%)
Label distribution before:
label
0.0    0.809980
1.0    0.137883
2.0    0.043664
3.0    0.006517
4.0    0.001397
5.0    0.000559
Name: proportion, dtype: float64


Label distribution after:
label
0.0    0.813643
1.0    0.135925
2.0    0.043400
3.0    0.005023
4.0    0.001507
5.0    0.000502
Name: proportion, dtype: float64

Rows after the drop: 9954

In [11]:
from lingua import Language, LanguageDetectorBuilder

# detecting Latin-script but likely non-English messages

# use all Latin-script languages supported by Lingua
# English must stay inside the detector, otherwise English text gets forced into another language
LATIN_LANGUAGES = list(Language.all_with_latin_script())

# detector for Latin-script language detection
# minimum_relative_distance: if top languages are too close, Lingua returns None instead of guessing
detector = (
    LanguageDetectorBuilder
    .from_languages(*LATIN_LANGUAGES)
    .with_minimum_relative_distance(0.25)
    .build()
)

# safety tokens: if these appear, keep the message because it may be gaming/chat English or mixed slang
SAFETY_TOKENS = {
    # gaming / chat
    "gg", "ez", "wp", "gl", "hf", "glhf", "afk", "brb", "lol", "lmao", "lmfao",
    "omg", "wtf", "stfu", "noob", "n00b", "bot", "team", "report", "ban",
    "kick", "mute", "trash", "toxic", "troll", "feed", "feeder", "int", "throw",
    "rank", "elo", "kill", "kys", "die", "fps", "lag", "ping", "server",
    "wot", "dota", "fortnite", "fn",

    # English / toxicity cues
    "you", "your", "you're", "u", "ur", "are", "is", "this", "that", "the",
    "and", "not", "dont", "don't", "fuck", "fucking", "fuk", "fck", "shit",
    "bitch", "ass", "asshole", "idiot", "stupid", "dumb", "moron", "loser",
    "suck", "sucks"
}

TOKEN_RE = re.compile(r"[a-z0-9']+", flags=re.IGNORECASE)


def get_tokens(text):
    return set(TOKEN_RE.findall(str(text).lower()))


def has_safety_token(text):
    return bool(get_tokens(text) & SAFETY_TOKENS)


# function to classify what to do with each Latin-script message
def latin_language_filter_status(text):
    text_str = str(text).strip()
    tokens = get_tokens(text_str)

    # too short - keep
    # language detection is unreliable on short gaming/chat messages
    if len(text_str) < 50 or len(tokens) < 6:
        return "keep_short"

    # possible gaming/chat/English false positive - keep
    if has_safety_token(text_str):
        return "keep_possible_gaming_or_mixed"

    lang = detector.detect_language_of(text_str)

    # ambiguous - keep
    if lang is None:
        return "keep_ambiguous"

    # English - keep
    if lang == Language.ENGLISH:
        return "keep_english"

    # confident Latin-script non-English - drop
    return f"drop_latin_nonenglish_{lang.name.lower()}"


# apply detection
x_train_en_lang = x_train_en.copy()
x_train_en_lang["lang_filter_status"] = x_train_en_lang["message"].apply(latin_language_filter_status)

# inspect groups
print("Language filter status counts:")
print(x_train_en_lang["lang_filter_status"].value_counts().head(30))


# check ambiguous cases
# these are messages where Lingua did not confidently choose a language
ambiguous_mask = x_train_en_lang["lang_filter_status"].eq("keep_ambiguous")

print(f"\nAmbiguous Latin-script language documents kept: {ambiguous_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nAmbiguous documents kept for now:\n",
        x_train_en_lang.loc[
            ambiguous_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among ambiguous rows:")
print(
    x_train_en_lang.loc[ambiguous_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# check possible gaming / mixed-language false positives
# these are messages that Lingua might classify as non-English, but contain gaming/chat/English cues
mixed_mask = x_train_en_lang["lang_filter_status"].eq("keep_possible_gaming_or_mixed")

print(f"\nPossible gaming or mixed-language documents kept: {mixed_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nPossible gaming/mixed documents kept for now:\n",
        x_train_en_lang.loc[
            mixed_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among possible gaming/mixed rows:")
print(
    x_train_en_lang.loc[mixed_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# drop only confident Latin-script non-English rows
drop_mask = x_train_en_lang["lang_filter_status"].str.startswith("drop_latin_nonenglish")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nConfident Latin-script non-English documents to drop:\n",
        x_train_en_lang.loc[
            drop_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print(f"\nHow many confident Latin-script non-English documents: {drop_mask.sum()}")


# label distribution sanity check
dropped_latin_nonenglish = x_train_en_lang.loc[drop_mask]

print("\nLabel distribution before Latin non-English drop:")
print(x_train_en["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after Latin non-English drop:")
print(
    x_train_en_lang.loc[~drop_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nLabel distribution among dropped rows:")
print(
    dropped_latin_nonenglish["label"]
    .value_counts(normalize=True)
    .sort_index()
)


# create dataset after Latin non-English drop
# keep ambiguous and mixed/gaming rows
x_train_lang_clean = (
    x_train_en_lang
    .loc[~drop_mask]
    .drop(columns=["lang_filter_status"])
    .reset_index(drop=True)
)

print(f"\nRows before Latin non-English drop: {len(x_train_en_lang)}")
print(f"Dropped {drop_mask.sum()} ({drop_mask.sum() / len(x_train_en_lang):.1%})")
print(f"Rows after Latin non-English drop: {len(x_train_lang_clean)}")

Language filter status counts:
lang_filter_status
keep_short                         38997
keep_possible_gaming_or_mixed        752
keep_english                          50
keep_ambiguous                        37
drop_latin_nonenglish_polish          25
drop_latin_nonenglish_german          19
drop_latin_nonenglish_hungarian        6
drop_latin_nonenglish_french           5
drop_latin_nonenglish_turkish          2
drop_latin_nonenglish_spanish          1
drop_latin_nonenglish_bosnian          1
drop_latin_nonenglish_romanian         1
drop_latin_nonenglish_finnish          1
Name: count, dtype: int64

Ambiguous Latin-script language documents kept: 37

Ambiguous documents kept for now:
                                                                                        message  \
1526                                        they have invis tiger i cant spot him on 50 meters
1942           rinoceronte ty huju zeby ci stara wyruchali w dupsko a potem to wylizała szmata
2149                            Im Spotted at B9! :o But I am wearing a mask! :) I am safe! ;)
2385                                  panzertank14 (Leopard 1), nem tudok lönni töled te buzi!
3157                              Enemy SPG <font color='#fe0e00'>WMBB (Bat.-Châtillon 155 58)
4741                                     Enemy SPG <font color='#fe7903'>PECHOLATA_65 (Hummel)
5496                 https://open.spotify.com/track/03RojRDRvvbFEPpabo3Aan?si=ef083469698742a4
7145                          hahahaha no blok demi hahahahaha wg best softver game retard mod
7629                                    just a useless pos who hs no clue how to play a medium
8433                                       jebać was cwele ulańca za darmo brawo mami synki :/
9532                        Enemy SPG <font color='#fe7903'>T_55_Ladelude (AMX 105 AM mle. 47)
11016                                 hab schon ??ber legt FV304... schaden.. ist schaden xDDD
11298  ConstantineDeLumberjack (FV215b 183), T'es tellement gros que tu bloque mon tir dégage!
11808                     que onda? bufearon las artys? porque pegan como padrastro alcoholico
14109                                  <font color='#f8f400'>TheAmiableReaper[BABNS] (T-34-85)
16596                        Enemy SPG <font color='#fe0e00'>gonzales_3 (Lorraine 155 mle. 50)
16970                               T??ss?? ei riitt??ny gun depressio, silti otti artikutia..
18616                           Im Spotted at B9! :o But I am wearing a mask! :) I am safe! ;)
19679                                   baaaaa...bagamias pula in mata....trage si tu odata...
21245                                      XD lynx jak bys sie nie pchał po dmg to by było git
21263                       Enemy SPG <font color='#fe7903'>Leopard1965 (Lorraine 155 mle. 50)
22461                           Im Spotted at K6! :o But I am wearing a mask! :) I am safe! ;)
23530                                     make more superfast 900 dmg per shot tanks wg please
23884                                     abys dostal doma par facek abys vedel, jak se chovat
24083                                      Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)
26880                        Enemy SPG <font color='#fe0e00'>gonzales_3 (Lorraine 155 mle. 50)
27122                                     sniper medium tank will try to snipe from a distance
28483    CURVA BLT JUS SUKA GALVOJAT KAD MAN IDOMU BLT 46M SITA CHUINEEEEEEEEEEEEEEEEEEEEEEEEE
28543                             good job medium campers , tier 4 camper idiots .lego players
31877                       FUICKING thanbks wg for all 23 clips of preprogrammed misses shots
32089                                   ty to VK 28.01.105 i was unable to co to my spot Sorry
32543                           I've gotten all city maps today so I was like &quot;FINE&quot;
33675                                  i was toptier on front i got only 1 tlowtier td support
34165                                      Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)
36521             BattleGreen (Skorpion G), T'es tellement gros que tu bloque mon tir d??gage!
39534                                  last 3 shots kinda vanished like a fart in a wind storm
39757                       daddy look, i got a clown car...i can sit in a bush in tha back...

       label lang_filter_status
1526     0.0     keep_ambiguous
1942     3.0     keep_ambiguous
2149     0.0     keep_ambiguous
2385     3.0     keep_ambiguous
3157     0.0     keep_ambiguous
4741     0.0     keep_ambiguous
5496     0.0     keep_ambiguous
7145     1.0     keep_ambiguous
7629     1.0     keep_ambiguous
8433     1.0     keep_ambiguous
9532     0.0     keep_ambiguous
11016    0.0     keep_ambiguous
11298    0.0     keep_ambiguous
11808    0.0     keep_ambiguous
14109    0.0     keep_ambiguous
16596    0.0     keep_ambiguous
16970    0.0     keep_ambiguous
18616    0.0     keep_ambiguous
19679    2.0     keep_ambiguous
21245    0.0     keep_ambiguous
21263    0.0     keep_ambiguous
22461    0.0     keep_ambiguous
23530    0.0     keep_ambiguous
23884    1.0     keep_ambiguous
24083    0.0     keep_ambiguous
26880    0.0     keep_ambiguous
27122    0.0     keep_ambiguous
28483    1.0     keep_ambiguous
28543    1.0     keep_ambiguous
31877    1.0     keep_ambiguous
32089    0.0     keep_ambiguous
32543    0.0     keep_ambiguous
33675    0.0     keep_ambiguous
34165    0.0     keep_ambiguous
36521    0.0     keep_ambiguous
39534    0.0     keep_ambiguous
39757    2.0     keep_ambiguous

Label distribution among ambiguous rows:
label
0.0    0.702703
1.0    0.189189
2.0    0.054054
3.0    0.054054
Name: proportion, dtype: float64

Possible gaming or mixed-language documents kept: 752

Possible gaming/mixed documents kept for now:
                                                                                                            message  \
32                                                           yeah man sorry i know you were about to kill that air
62                                   sorry if I blocked your shot... I didn't want you to die as you took the lead
104                                                             we cannot hit the T30 if he stays behind that rock
160                                            And? they are both 1 shots we are both 1 shots. It‘s a Draw anyways
254                      youd think the infinite monkeys idea would come into play considering how many youve sent
...                                                                                                            ...
39556                                      elc... i don't know your plan... maybe you want to go a littel forward?
39707                                                          MorrowTank (Leopard 1), you are blocking my target!
39708            next time watch more carefully on what is going around, since you are arty and can see everywhere
39827  fkin idiots..2 lights in same fkin space ..fkin retards..instead of taking middle..you absolute fkin morons
39868                                                  TO STAY IN ONE PLACE WHEN NOBODY WANT BUT CAN HELP YOU MOVE

       label             lang_filter_status
32       0.0  keep_possible_gaming_or_mixed
62       0.0  keep_possible_gaming_or_mixed
104      0.0  keep_possible_gaming_or_mixed
160      1.0  keep_possible_gaming_or_mixed
254      1.0  keep_possible_gaming_or_mixed
...      ...                            ...
39556    0.0  keep_possible_gaming_or_mixed
39707    0.0  keep_possible_gaming_or_mixed
39708    0.0  keep_possible_gaming_or_mixed
39827    1.0  keep_possible_gaming_or_mixed
39868    0.0  keep_possible_gaming_or_mixed

[752 rows x 3 columns]

Label distribution among possible gaming/mixed rows:
label
0.0    0.666223
1.0    0.212766
2.0    0.093085
3.0    0.021277
4.0    0.003989
5.0    0.002660
Name: proportion, dtype: float64

Confident Latin-script non-English documents to drop:
                                                                                                                                                          message  \
370                                                                                                           tu ecris ce que tu veux, dans la mesure du correct
559                                                                                          FASZYSTOWSKIE ŚWINIE WOTOWSKA WAGNEROWSKA BANDA WSPIERAJĄCA FASZYZM
598                                                                                                       mehetünk majd még gyakorlóba és ott megnézheted milyen
1753                                                                                               shut up froschschenkelfresser oder laber in englisch du pussy
1965                                                                                                son una mierda, tengo que defender porque casi nadie lo hace
2606                                       twoj stary debil ze sie nie spuscil na kupe lajn zeby ciebie nie splodzic ale pewnie twoja stara to kurwa alimenciara
2954                                                                                                  hat euhc euer vater zusehr das hrin aus dme arsch gevögelt
3214                                                                                                sympa les bataille de samedi soir, sur le twitch Pamboum :-)
3475                                                                                        kurwa kocham ta gre 80% pierwszych bitew arta = himel a ht malinowka
3792                                                                                                         Aufgeklärt bei Position G2. Etwas Hilfe währe nett!
4487                                                                                                         Aufgeklärt bei Position F2. Etwas Hilfe währe nett!
5281                                                                                                          herrlich gibnt es heute nur 10e matche für mich ..
5856                                                                                                         Aufgeklärt bei Position C3. Etwas Hilfe währe nett!
6048                                                             niech ten twoj kolega naiuczy sie grac kołowecem a nie wpiedala sie na kazdego a zas ma problem
6053                                                                             Wer Lust auf einen Clan hat, kann mich nach dem Gefecht anschreiben. Ü18 bitte.
6090                                                                                                         Aufgeklärt bei Position E3. Etwas Hilfe währe nett!
6262                                                           agyonbaszott buffolt szartartály mattilda a valóságban a világ valaha volt legszarabb tankja volt
6382                                                                                                     Nowo powstały klan NIPL rekrutacja otwarta,zero wymagań
6817                                                                                     WY KURWY JEABane slepe mam nadzieje ze kruwa kazdy was na raka zdechnie
7093                                                                                   za pocetak samo da jebem mater svi ljudima sto prave ovu retardiranu igru
7570                                                                           mam już pracę stałą. Od ręki mnie zatrudnili ze względu na znajomość francuskiego
7678                                                                                                      pierdolona cioto z ciezkiego w warcabi idz grac debilu
8088                                                                                              stul pysk, durniu, naotwartej mapie wystawiasz durny łeb artom
8290                                                                                         Danke Type das ich deinen Job gemacht habe... du dummer Flackhelfer
11416                                                                                na polibudzie sobie nie poradziłem na drugim roku, więc łatwiejsze wybrałem
12653                                                                                                     wer sich schon joergimaus nennt... ab zum CSD du vogel
13866                                                  Salut,clanul GLADIATORII asteapta jucatori,cine doreste,rog contactati-ma sau aplicati la clan,multumesc!
14001                                                                                                      abi 10 el oynad??m bu kadar ??erefsiz bir oyun olamaz
14827                                                                                                         a nie moja wina ze mnie pchasz zeby w arte trsafic
18288                                                                                  ja rozumie byc slabym graczem ale zeby miec 20k i 300 wn8 to juz przesada
19179                                                                                          wr a co to kurwa jest niedojebany kacapski obciagaczu ruskich faj
19562                                                  killyourself scheiss hurensöhne enrstahft killt euhc und eure famillie was ist verkehrt gelaufen bei euhc
19642               Les fr??res d'armes [L_F_A] recrutent.Clan francophone, nous cultivons un ??tat d'esprit ouvert.Pas d'obligations, de la bonne humeur,.me MP
19821                     man muss hier nur ein Jude, Kommunist, Slave, Alliierter, Pedophiler, Massenm??dersein und deutsche hassen, dann macht WG dein acc gut
22369                                                                                                      nyomornc rtetkes kurva anyátok remélem már megdölgött
22403                                 Bonjour ! Clan Fr. Nous recrutons&quot;AV424-LES TEMPLIERS DE FRANCE ET DE NAVARRE !!Discord et"casque de chantier » !!!!!
23392                                                                              ach, zdalne... pamiętam zdalną sesję na uczelni, bez problemu szło ściągać xd
23524                                                                                                        Aufgeklärt bei Position D3. Etwas Hilfe währe nett!
24368                                                                 FR ROCK recrute francophones, voir conditions sur http://eu.wargaming.net/clans/500071861/
25041                                                                                                        Aufgeklärt bei Position F2. Etwas Hilfe währe nett!
25092                                                                                                        Aufgeklärt bei Position F1. Etwas Hilfe währe nett!
25805                                                                                                        Aufgeklärt bei Position C3. Etwas Hilfe währe nett!
26614                                                                                siema opłaca sie dokupic stabe bo mam dosyłacz i wente oczywiscie fioletowe
26735                                                                                a jak jestes slepy i nie widzisz jak sie na kogos pchasz, to okulista czeka
26806                                                                                                        Aufgeklärt bei Position H1. Etwas Hilfe währe nett!
27172                                                                                                       ha zavar az 1es tier akkor mehetünk tier 8 ha akarod
27592                                                               jeszcze t54 zespotowany byl wczesniej wiec widac ze jedzie i chuj nawet jeden sie nie ruszyl
30117                                      majac takich graczy jak ty to i ma sie takie zjebane bitwy ze stoisz i chuja obisz ciapata kurwo z pod napleta putina
30130                                      salaklar arkanızda ben varım amk malları biraz düzgün oynasaydınız adamların anasını sikerdim 2700 hasarım var botlar
30420                                                                                                        no wlasnie stojac za mna gdzie ja trzymalem pozycje
31208                                                                                                     chce gtos grac w plutonie zeby zrobic misej eventowe??
31593                                                                        mit solchen spielern wie euch,blamiert man sich nur,peinlich,ich makert euch daf??r
31721                                                                              Szukasz klanu ? Zapraszamy do -AP- Po więcej info zapraszam priv po bitwie ;)
32060                                                                                               eka t???? oma samanlainen vaunu puski tohon samaan kohtaan..
32575                                                                          ich checkls nicht seit wann lässst man diese seite so offen seit ihr behindert???
34217                                                           ja pierdole jak sa tacy gracze jak ty to srednio rozwiniety szympans ma wiecej rozumu od ciebie'
35257                                                                                          MOCSKOSALJASFÉREGFASSZOPÓPATKÁNYCSICSKAKÖCSÖGBUZITETVESCSALÓJÁTÉK
35395  Hali! A MAATT kl??n akt??v j??t??kosokat keres. A WN8 nem sz??m??t. J?? t??rsas??g, k??telezetts??gek n??lk??l. Ha ??rdekel keress, k??szi. Sry for spam.
35534                                                                                      deszcze nie spokojne potargaly sad a ja musze tym zlomem dzisiaj grac
38443                                                                     ja to jeszcze 4 kalsa szkoly zostala ale w maku robie takze potencjał poza skale siega
39068                                       nie blokowałem aby sie zatrzymałem i stałem w miejscu a jak mnie pchałes to wciskałem W aby nie ruszyc sie z mijesca

       label               lang_filter_status
370      0.0     drop_latin_nonenglish_french
559      5.0     drop_latin_nonenglish_polish
598      0.0  drop_latin_nonenglish_hungarian
1753     1.0     drop_latin_nonenglish_german
1965     1.0    drop_latin_nonenglish_spanish
2606     3.0     drop_latin_nonenglish_polish
2954     3.0     drop_latin_nonenglish_german
3214     0.0     drop_latin_nonenglish_french
3475     0.0     drop_latin_nonenglish_polish
3792     0.0     drop_latin_nonenglish_german
4487     0.0     drop_latin_nonenglish_german
5281     0.0     drop_latin_nonenglish_german
5856     0.0     drop_latin_nonenglish_german
6048     0.0     drop_latin_nonenglish_polish
6053     0.0     drop_latin_nonenglish_german
6090     0.0     drop_latin_nonenglish_german
6262     2.0  drop_latin_nonenglish_hungarian
6382     0.0     drop_latin_nonenglish_polish
6817     0.0     drop_latin_nonenglish_polish
7093     2.0    drop_latin_nonenglish_bosnian
7570     0.0     drop_latin_nonenglish_polish
7678     1.0     drop_latin_nonenglish_polish
8088     1.0     drop_latin_nonenglish_polish
8290     1.0     drop_latin_nonenglish_german
11416    0.0     drop_latin_nonenglish_polish
12653    0.0     drop_latin_nonenglish_german
13866    0.0   drop_latin_nonenglish_romanian
14001    0.0    drop_latin_nonenglish_turkish
14827    0.0     drop_latin_nonenglish_polish
18288    0.0     drop_latin_nonenglish_polish
19179    3.0     drop_latin_nonenglish_polish
19562    4.0     drop_latin_nonenglish_german
19642    0.0     drop_latin_nonenglish_french
19821    3.0     drop_latin_nonenglish_german
22369    1.0  drop_latin_nonenglish_hungarian
22403    0.0     drop_latin_nonenglish_french
23392    0.0     drop_latin_nonenglish_polish
23524    0.0     drop_latin_nonenglish_german
24368    0.0     drop_latin_nonenglish_french
25041    0.0     drop_latin_nonenglish_german
25092    0.0     drop_latin_nonenglish_german
25805    0.0     drop_latin_nonenglish_german
26614    0.0     drop_latin_nonenglish_polish

In [12]:
# save to parquet
x_train_lang_clean.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_train.parquet", index=False)

# evaluate impact 
# baseline - before any cleaning
impact = eval_step("non_english_drop", {"WoT": PROJECT_ROOT / "data/processed_data/wot/x_train.parquet"}, impact)
impact

            step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
non_english_drop     WoT 39836    0.5027       0.8699        0.5943           0.4929          0.0097        0.0218              0.0

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,WoT,42960,0.4743,0.8646,0.5476,0.4626,0.0000,0.0000,0.0000
1,non_latin_drop,WoT,39897,0.4930,0.8699,0.5725,0.4929,0.0187,0.0249,0.0303
2,non_english_drop,WoT,39836,0.5027,0.8699,0.5943,0.4929,0.0097,0.0218,0.0000

Increase in metrics are within noise, however they are not negative.

In [13]:
# apply the same Latin-script language filter to the validation set for consistency
x_validation_en_lang = x_validation_en.copy()
x_validation_en_lang["lang_filter_status"] = x_validation_en_lang["message"].apply(latin_language_filter_status)

# inspect groups
print("Language filter status counts:")
print(x_validation_en_lang["lang_filter_status"].value_counts().head(30))


# check ambiguous cases
# these are messages where Lingua did not confidently choose a language
ambiguous_mask = x_validation_en_lang["lang_filter_status"].eq("keep_ambiguous")

print(f"\nAmbiguous Latin-script language documents kept: {ambiguous_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nAmbiguous documents kept for now:\n",
        x_validation_en_lang.loc[
            ambiguous_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among ambiguous rows:")
print(
    x_validation_en_lang.loc[ambiguous_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# check possible gaming / mixed-language false positives
# these are messages that Lingua might classify as non-English, but contain gaming/chat/English cues
mixed_mask = x_validation_en_lang["lang_filter_status"].eq("keep_possible_gaming_or_mixed")

print(f"\nPossible gaming or mixed-language documents kept: {mixed_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nPossible gaming/mixed documents kept for now:\n",
        x_validation_en_lang.loc[
            mixed_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among possible gaming/mixed rows:")
print(
    x_validation_en_lang.loc[mixed_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# drop only confident Latin-script non-English rows
drop_mask = x_validation_en_lang["lang_filter_status"].str.startswith("drop_latin_nonenglish")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nConfident Latin-script non-English documents to drop:\n",
        x_validation_en_lang.loc[
            drop_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print(f"\nHow many confident Latin-script non-English documents: {drop_mask.sum()}")


# label distribution sanity check
dropped_latin_nonenglish = x_validation_en_lang.loc[drop_mask]

print("\nLabel distribution before Latin non-English drop:")
print(x_validation_en["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after Latin non-English drop:")
print(
    x_validation_en_lang.loc[~drop_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nLabel distribution among dropped rows:")
print(
    dropped_latin_nonenglish["label"]
    .value_counts(normalize=True)
    .sort_index()
)


# create dataset after Latin non-English drop
# keep ambiguous and mixed/gaming rows
x_validation_lang_clean = (
    x_validation_en_lang
    .loc[~drop_mask]
    .drop(columns=["lang_filter_status"])
    .reset_index(drop=True)
)

print(f"\nRows before Latin non-English drop: {len(x_validation_en_lang)}")
print(f"Dropped {drop_mask.sum()} ({drop_mask.sum() / len(x_validation_en_lang):.1%})")
print(f"Rows after Latin non-English drop: {len(x_validation_lang_clean)}")
# save to parquet
x_validation_lang_clean.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_validation.parquet", index=False)

Language filter status counts:
lang_filter_status
keep_short                         9689
keep_possible_gaming_or_mixed       229
keep_english                         13
drop_latin_nonenglish_german          7
keep_ambiguous                        6
drop_latin_nonenglish_polish          4
drop_latin_nonenglish_hungarian       2
drop_latin_nonenglish_czech           2
drop_latin_nonenglish_french          1
drop_latin_nonenglish_turkish         1
Name: count, dtype: int64

Ambiguous Latin-script language documents kept: 6

Ambiguous documents kept for now:
                                                         message  label  \
2484   thx skorpio but no other help from these line A! campers    2.0
2592  i did after 1,3 k much too few for a super conqueror, stb    0.0
4649     pls mommy can I be a motherufcking T34 when i grow up!    1.0
6160   Enemy SPG <font color='#fe7903'>killerkirby99_2013 (M44)    0.0
7377        Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)    0.0
8052       S CONQ FULL WILDCAMPER'sss BOTTT GGAAYY2 MUZSIKK 2 X    1.0

     lang_filter_status
2484     keep_ambiguous
2592     keep_ambiguous
4649     keep_ambiguous
6160     keep_ambiguous
7377     keep_ambiguous
8052     keep_ambiguous

Label distribution among ambiguous rows:
label
0.0    0.500000
1.0    0.333333
2.0    0.166667
Name: proportion, dtype: float64

Possible gaming or mixed-language documents kept: 229

Possible gaming/mixed documents kept for now:
                                                                                                                                            message  \
24                                                                                         i would just lay down the throttle and dive in the lake
41                                                                                  okok, have all the german t10 heavys and wanted to swich it up
110                                                                     waste coming back to idoits like you so sad wg do shit to asshole like you
124                                                                                            lol 2nd upload... 4 oneshooter &amp; armored tds...
170                                                                                           ppl who rush are stupid there the ones who die first
173                                                                        4 fucking tds r camping behind base and do nothing.... f ur brains ....
209                                                                               why do my rounds looklike they are coming out under my gun n ow?
244                                                             the guy was doing his best with what he had to work with. Lets not get uppity here
290                                     Pretty sure 54 threw this by not killing the charioeteer, when it was the only tank in front of him...? GG
340                                                its literally 2 of us vs the entire enemy team while the rest of our heavies sit and do nothing
354                                                                                            MIGHT THINK ABOUT KILLING THAT SCOUT SOMETIME TODAY
429                                                                                       i think we just try to hold this since we are 3v5/6 here
444                                                                                         but dont think so I can see 8 enemies when reloaded :D
469                                   lol you bought a very high skill cap, situational tank and you‘re upset it‘s high skill cap and situational?
505                                                                                             VerteidiGER5 (KV-1SA), you are blocking my target!
527                                                      he was playing safe from min1! I guess this si the new trend, play alone, leave the team!
537                                                                                             get this map and the light always a disease animal
543                                                                                         Congradulations on being the loser with the most kills
578                                                                                            and we could carry this around but u refuse to play
679                                                                                           ok... says the one with three kills to all your none
695                                                                               ADSIZKRAL_01[SOPA] (Grille 15), you're blocking my line of fire!
707                                                                                           this tank is so bad does anyone know how to play iot
746                                                                               Black prince its almost like our heavy tanks did fucking nothing
779                                                                   Im just fucking laughing how fucking braindead useless pieces of shit exists
837                                                                                             LEOPARD U ARE THE BIGGEST RETARD SHIT IN THIS GAME
845                                                                                            e9 is typical sniping position that no one went lol
849                                                                              all trash talkers know where the uninstall button is go and do it
912                                                                               their bc 25 t ap understood this but you are too stupid to do so
961                                                                                        keivn12[-BCW-] (T-44), you‘re blocking my line of fire!
972                                                                                      yet you are shit talking someone for calling you retarded
975                                                                                         reportarty666 (Kpz 07 RH), you are blocking my target!
986                                                                                 i sure do love missing every single fucking shot for no reason
1019                                                                                        leopard... you're aimed at a rock... move and help out
1108                                                                                          what the **** are those two morons doing in our base
1147                                                                                     YOUR FAT MOUTH I DONT HAVE TYTO SEE WORTHLESS LEAF BLOWER
1175                                                                                        they have health and speed yet they sit back and watch
1217                                                      instead to kkep range so that they have their enemies betwen yellow and white circle....
1277                                                                                          Pawlack Tank player you are so stupid. go out of wot
1282                                                                              being BAD at the game is not bannable, you can't report the 279e
1304                                                                              u 2 tiers up idiot and are killed by the same of me my dear pro!
1307                                                                           fucking shitters all sitting in the corner of the map doing nothing
1315                                                                                        cap together &amp; if he come u have 2 chance to shoot
1386                                                         Enemy SPG Nojohhaidii (G.W. Tiger) just hit me and is now reloading for about 40.27s.
1438                                                                   Like I said matchmaking has been abysmal and the team worse then deplorable
1459  The world is full of you. You eat our food, you drink our water, and you suck in our air. Because of waste like you, there are constantly wa
1507                                                                                  rifis[HELA1] (Rinoceronte), you‘re blocking my line of fire!
1539                                                                                            Obj.430 you play like a GOAT!!! whhy you push me??
1621                                                                                    I have a 14s reload, I am not pushing in this glass cannon
1642                                                                                            fuck this... the Suicide is In and you Lot Lose...
1647                                                                    finally get a tune out of this tank, and half my own team are traitors lol
1706                                                                                          Wrap_around (Pz. 38 nA), you are blocking my target!
1763                                                                                           U CAN BUY TANK FOREST BUT U CANT BUY THE BRAIN :)XD
1800                                                   hey everyone, just a quick warning that i might be dealing with some lag during this match.
1893                                                              Enemy SPG ReborWolf (M53/M55) just hit me and is now reloading for about 40.27s.
1985                                                                    Enemy SPG VV68 (Hummel) just hit me and is now reloading for about 29.82s.
2011                                                                                      bc 1 person was a coward and couldnt kill 200hp tank lol
2051                                                              hmm...might be a decent game. Finally not loaded with a bunch of blue and purple
2402                                                                                         lights win the game or lose it, we got crap from ours
2430                                                                                       BombSitekv100 (UDES 15/16), you are blocking my target!
2431                                                                                      ive never played a tank as bad as this in my entire life
2433                                                                                 need to go for feeld mods...they are especialy good for us...
2469                                                    well yeah if you cant even reset the base when the enemy is on top of the hill i dont know
2483                                                                                    what if when u started people wanted to report u bc ur bad
2508                                                                                      btw i have the small gun so dont think i can do much dmg
2533                                                          Enemy SPG Turbo_Noo (105 leFH18B2) just hit me and is now reloading for about 8.92s.
2559                                                                                        Skuty_Bernard (HT No. VI), you are blocking my target!
2620                                                                     did you go to the hill with the VK and it's 2 degrees of gun rdepression?
2631                                                                                  dang...t50 did his job and I got killed...you the man T50 :)
2632                                                                                            lol, nugs is less than 2k battles and talking shit
2686                                                                                          three lights,, two of them dead, not a win potential
2720                                                                                            Vovan158 (AMX 13 105), you are blocking my target!
2742                                                                                            tell your mom what is wrong in game with you today
2801                                                                           can i please get on an aggressive team. These wusses are killing me
2813                                                                                    char are you go spoting something instead camping all game
2829                                                         dont be sad scorp, its allways same, ebr players can not passive scouting, they noobs
2842                                                                            like move your tank into the fight instead of sniping kind of help
2853                                                                                  SriSriRaviSchanka (Progetto 46), you are blocking my target!
2856                                                                  it had your name on it saying &quot;please sponser this starving child&quot;
2879                                                              time to drive for 2 min to get up hill to then get shot by arty for 3min and die
2913                                                                                           fun that i dont get a LT this battle to on the team
2919                                                                                            dont push guys, the heavies are coming right to us
2948                                                                                      f****** tank is slow enough just for them shoot me fu wg
2950                                                                        guys u won this just kill 1 and arty is still in the same place he was
2976                                                                                  fuuuking M103 standing in middle of hill and u dont spot him
3022                                                                                            to bad you guys didnt know about taking tracks off
3026                                                                       magic tanks buy WOT vanishing in front of you ... gess they are WOT pet
3032                                                                            you cannot hit fast even though your inter clip time is very short
3035                                                                                 PUTIN_MY_PRESIDENT (AMX ELC bis), you are blocking my target!
3248                                                                                        sbasab (UDES 14 5), you're Blocking my Shot, &gt;=O!!!
3264   MISTER CHAR futur...and you were also someone not offering structure or attacking while the enemy magazin tanks were reloading and the arty
3276                                                                                           yeah well. i got 2 shot by the caliban practically.
3376                                                                                            he exactly could cuz he shoot and me and didnt pen
3384                                                 whe everyone blocking me before taking position to spot, why should I spot for such a team???
3444                                                                                      not your fault for getting me shot while i was unspoted?
3640                                                                                         Desperado_72 (AMX 13 57), you are blocking my target!
3654                                                           Enemy SPG BEK_690 (G.W. Panther) just hit me and is now reloading for about 25.89s.
3660                                                                               i see a lot tier withou cammo, dont know wjy? its +3 or +4% for
3746                                                                    By pressuring that side, the T21 would stop the SU100 from helping the KV2
3763                                                                                     I am so glad, that you f disgusting assh are already dead
3798                                                                                        had the 62 and the bat pinned with the two of us there
3825                                                                                         useless scrub shoot them dont just ask for help scrub
3910                                                                                        look on mini map where the tanks are - don't cam on A9
3971                                                                                            they shoot you and you cant even fucking spot them
4000                                                                                       arty chaud is in the perfect position for their name :D
4059                                                                                       please to t34 85 blocked me and got my commander killed
4076                                                                                     lets take the Hill, we are way faster. go up, dont brake!
4146                                                                                           why the fuck is the scout in the middle of the city
4157                                                          a lot of fast lights but nobody moved to the center...great and nobody likes to help
4166                                   Sad to lose with 6 kills.. I never fired a shot.. cheap loss for me.. just never got a kill shot... to bad.
4172                                                               wtf team learnn play heavy camp in the corna this is your loise OMG play tetris
4327                                                         dont be sad scorp, its allways same, ebr players can not passive scouting, they noobs
4340                                                                                            Guide87 (M-II-Y), you‘re blocking my line of fire!
4504                                                                                        In order to lose games like this you must want to lose
4541                                                              Enemy SPG ReborWolf (M53/M55) just hit me and is now reloading for about 40.27s.
4606                                                                                           udes 16 you are colpletely a waste on that position
4616                                                                                         ONE OF THE MEDIUMS IN THE MID NEEDS TO COME OVER HERE
4633                                                                                i'm dead, i can rant all day, you are supposed to play and win
4638                                          arty i really wish you‘d have killed that goddamn M44 when i spotted it the first time, or the ShPTK
4715                                                                                            after they made us lose this one which was winning
4719                                                                                 idc of your dammage btw u are not in game for comment the end
4863                                           Enemy SPG TirantLoBlanc (Conqueror Gun Carriage) just hit me and is now reloading for about 44.11s.
5033                                                                                         pushing without counting the guns is how retards play
5041                                                                                       another wasted first victory xp bonus as fucking always
5126                                                                            you shold kill super hellcat in first klip but you move after shot
5213                                                           My issue is the four td‘s behind me which didn‘t think to position and be useful...

#### Duplicates

In [14]:
# look at dataset with duplicates 
x_train_dup = x_train_lang_clean[x_train_lang_clean.duplicated(subset="message", keep=False)].sort_values("message")
# look at some examples
x_train_dup.head(10)

       message  label
28859        !    0.0
4992         !    0.0
11388     !!!!    0.0
2807      !!!!    0.0
32052  #ERROR!    0.0
6079   #ERROR!    0.0
14464  #ERROR!    0.0
14400  #ERROR!    0.0
14397  #ERROR!    0.0
14345  #ERROR!    0.0

In [15]:
# top 100 duplicated messages
x_train_dup["message"].value_counts(ascending=False).head(100)

message
gg                   2556
lol                   354
nice                  312
gj                    257
cap                   162
                     ...
Im Spotted at F4!      22
Im Spotted at F3!      22
Im Spotted at G5!      21
Im Spotted at J8!      21
??                     21
Name: count, Length: 100, dtype: int64

Most of these duplicates are useful and important data to train or models for detecting toxicity. We need to check for same messages but different labels.

In [16]:
# Look for duplicates with same messages but different labels
conflicts = x_train_lang_clean.groupby("message")["label"].nunique()
conflicts = conflicts[conflicts > 1]

conflict_rows = x_train_lang_clean[x_train_lang_clean["message"].isin(conflicts.index)].sort_values("message")

# Check how large is the proportion of conflicting duplicates
conflict_pct = len(conflict_rows) / len(x_train_lang_clean) * 100
print(f"Proportion of messages with conflicting labels: {conflict_pct:.2f}%")
print(f"Number of messages with conflicting labels: {len(conflict_rows)}")

Proportion of messages with conflicting labels: 14.05%
Number of messages with conflicting labels: 5597

In [17]:
# check conflicting rows 
conflict_rows

                           message  label
15894                      #ERROR!    0.0
25435                      #ERROR!    0.0
21500                      #ERROR!    0.0
11950                      #ERROR!    0.0
11985                      #ERROR!    0.0
...                            ...    ...
35167                     you lost    2.0
21679                     you lost    0.0
8596                      you lost    1.0
2712   you wanna loose that right?    1.0
10242  you wanna loose that right?    2.0

[5597 rows x 2 columns]

These messages can not be used for analysis, since it is a problem of `annotation`. Using them will be equal to guessing. Duplicated rows account for 14% of the data, which is a huge loss but we can not use that.

In [18]:
# drop conflicting messages
x_train_dup = x_train_lang_clean[~x_train_lang_clean["message"].isin(conflicts.index)].reset_index(drop=True)
print(x_train_dup.shape)

(34239, 2)

In [19]:
# save again and evaluate 
x_train_dup.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_train.parquet", index=False)
impact = eval_step("duplicates_removal", {"WoT": PROJECT_ROOT / "data/processed_data/wot/x_train.parquet"}, impact)
impact

              step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
duplicates_removal     WoT 34239    0.4967       0.8667        0.5665           0.5028          -0.006       -0.0278           0.0099

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,WoT,42960,0.4743,0.8646,0.5476,0.4626,0.0000,0.0000,0.0000
1,non_latin_drop,WoT,39897,0.4930,0.8699,0.5725,0.4929,0.0187,0.0249,0.0303
2,non_english_drop,WoT,39836,0.5027,0.8699,0.5943,0.4929,0.0097,0.0218,0.0000
3,duplicates_removal,WoT,34239,0.4967,0.8667,0.5665,0.5028,-0.0060,-0.0278,0.0099

This did not work, our score started decreasing. Instead of dropping duplicated conflicting labels, we assign a majority label to each.

In [20]:
# majority label for similar words
majority_label = x_train_lang_clean.groupby("message")["label"].agg(lambda x: x.value_counts().index[0])

# cap at 20 occurrences per message — preserves frequency, prevents extreme repeats dominating
MAX_PER_MESSAGE = 20
x_train_deduped = (
    x_train_lang_clean
    .assign(label=lambda df: df["message"].map(majority_label))
    .groupby("message", group_keys=False)
    .apply(lambda g: g.head(MAX_PER_MESSAGE))
    .reset_index(drop=True)
)

# check same ex duplicates
x_train_deduped[x_train_deduped["message"].isin(conflicts.index)][["message", "label"]].head(20)

C:\Users\nyuss\AppData\Local\Temp\ipykernel_31676\984775230.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.head(MAX_PER_MESSAGE))

    message  label
12  #ERROR!    0.0
13  #ERROR!    0.0
14  #ERROR!    0.0
15  #ERROR!    0.0
16  #ERROR!    0.0
17  #ERROR!    0.0
18  #ERROR!    0.0
19  #ERROR!    0.0
20  #ERROR!    0.0
21  #ERROR!    0.0
22  #ERROR!    0.0
23  #ERROR!    0.0
24  #ERROR!    0.0
25  #ERROR!    0.0
26  #ERROR!    0.0
27  #ERROR!    0.0
28  #ERROR!    0.0
29  #ERROR!    0.0
30  #ERROR!    0.0
31  #ERROR!    0.0

In [21]:
# check the change
print(f"Before dedup: {len(x_train_lang_clean)}")
print(f"After dedup: {len(x_train_deduped)}")
dropped = len(x_train_lang_clean) - len(x_train_deduped)
print(f"Dropped: {dropped} ({dropped / len(x_train_lang_clean):.1%})")

Before dedup: 39836
After dedup: 33603
Dropped: 6233 (15.6%)

In [22]:
# save again and evaluate 
x_train_deduped.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_train.parquet", index=False)
impact = eval_step("duplicates_majority", {"WoT": PROJECT_ROOT / "data/processed_data/wot/x_train.parquet"}, impact)
impact

               step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
duplicates_majority     WoT 33603    0.5304       0.8584        0.6166           0.5226          0.0337        0.0501           0.0198

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,WoT,42960,0.4743,0.8646,0.5476,0.4626,0.0000,0.0000,0.0000
1,non_latin_drop,WoT,39897,0.4930,0.8699,0.5725,0.4929,0.0187,0.0249,0.0303
2,non_english_drop,WoT,39836,0.5027,0.8699,0.5943,0.4929,0.0097,0.0218,0.0000
3,duplicates_removal,WoT,34239,0.4967,0.8667,0.5665,0.5028,-0.0060,-0.0278,0.0099
4,duplicates_majority,WoT,33603,0.5304,0.8584,0.6166,0.5226,0.0337,0.0501,0.0198

Cap at 20 gave best f1_macro — higher than both no-dedup and full-dedup. Transform validation data the same way.

In [23]:
# transform validation data as well 
# majority label for similar words 
majority_label = x_validation_lang_clean.groupby("message")["label"].agg(lambda x: x.value_counts().index[0])

# drop duplicates and map majority label 
x_validation_deduped = x_validation_lang_clean.copy()
x_validation_deduped["label"] = x_validation_deduped["message"].map(majority_label)

# save again
x_validation_deduped.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_validation.parquet", index=False)

#### Data Artifacts

In [24]:
# #ERROR! entries
error_count = x_train_deduped["message"].str.contains(r"#ERROR!", regex=False, na=False).sum()
print(f"#ERROR! messages: {error_count}")

# HTML entities
html_mask = x_train_deduped["message"].str.contains(r"&\w+;", regex=True, na=False)
print(f"Messages with HTML entities: {html_mask.sum()}")
x_train_deduped[html_mask][["message", "label"]].head(10)

#ERROR! messages: 20
Messages with HTML entities: 110

                message  label
56            &gt;.&gt;    0.0
57               &gt;:O    0.0
58               &gt;=o    0.0
59  &lt;-- mostly stock    0.0
60                &lt;3    0.0
61                &lt;3    0.0
62                &lt;3    0.0
63                &lt;3    0.0
64                &lt;3    0.0
65                &lt;3    0.0

In [25]:
# artifact cleaning
# goal: remove generic technical artifacts, not game-specific phrases
# use wot_deduped as input from the previous preprocessing step

x_train_clean = x_train_deduped.copy()

# convert messages to string and fill missing values
x_train_clean["message"] = x_train_clean["message"].fillna("").astype(str)

# decode HTML entities inline
# example: &quot; -> ", &amp; -> &
x_train_clean["message"] = x_train_clean["message"].apply(html_lib.unescape)

# generic artifact patterns
# no game-specific hardcoding here
ERROR_RE = re.compile(r"#ERROR!", flags=re.IGNORECASE)
URL_RE = re.compile(r"https?://\S+|www\.\S+", flags=re.IGNORECASE)
HTML_TAG_RE = re.compile(r"<[^>]+>", flags=re.IGNORECASE)

# after html.unescape, most entities should disappear
# this catches remaining malformed/unresolved entities
HTML_ENTITY_RE = re.compile(r"&[a-zA-Z]+;|&#\d+;|&#x[0-9a-fA-F]+;")


# classify artifact reason for each row
def artifact_status(text):
    text = str(text)

    if ERROR_RE.search(text):
        return "drop_error"

    if URL_RE.search(text):
        return "drop_url"

    if HTML_TAG_RE.search(text):
        return "drop_html_tag"

    if HTML_ENTITY_RE.search(text):
        return "drop_unresolved_html_entity"

    return "keep"


# apply artifact detection
x_train_clean["artifact_status"] = x_train_clean["message"].apply(artifact_status)

# inspect artifact counts
print("Artifact status counts:")
print(x_train_clean["artifact_status"].value_counts())

# rows to drop
artifact_mask = x_train_clean["artifact_status"].ne("keep")

# inspect dropped artifacts
with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nArtifact rows to drop:\n",
        x_train_clean.loc[
            artifact_mask,
            ["message", "label", "artifact_status"]
        ]
    )

# label distribution sanity check
print("\nLabel distribution before artifact drop:")
print(x_train_deduped["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after artifact drop:")
print(
    x_train_clean.loc[~artifact_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nLabel distribution among dropped artifact rows:")
print(
    x_train_clean.loc[artifact_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

# create artifact-cleaned dataset
x_train_artifact_clean = (
    x_train_clean
    .loc[~artifact_mask]
    .drop(columns=["artifact_status"])
    .reset_index(drop=True)
)

print(f"\nRows before artifact drop: {len(x_train_deduped)}")
print(f"Dropped {artifact_mask.sum()} ({artifact_mask.sum() / len(x_train_deduped):.1%})")
print(f"Rows after artifact drop: {len(x_train_artifact_clean)}")

Artifact status counts:
artifact_status
keep             33563
drop_error          20
drop_html_tag       13
drop_url             7
Name: count, dtype: int64

Artifact rows to drop:
                                                                                                              message  \
12                                                                                                           #ERROR!
13                                                                                                           #ERROR!
14                                                                                                           #ERROR!
15                                                                                                           #ERROR!
16                                                                                                           #ERROR!
17                                                                                                           #ERROR!
18                                                                                                           #ERROR!
19                                                                                                           #ERROR!
20                                                                                                           #ERROR!
21                                                                                                           #ERROR!
22                                                                                                           #ERROR!
23                                                                                                           #ERROR!
24                                                                                                           #ERROR!
25                                                                                                           #ERROR!
26                                                                                                           #ERROR!
27                                                                                                           #ERROR!
28                                                                                                           #ERROR!
29                                                                                                           #ERROR!
30                                                                                                           #ERROR!
31                                                                                                           #ERROR!
82                                                                                                   <base64encoded>
1948                                                         <font color='#f8f400'>TheAmiableReaper[BABNS] (T-34-85)
1949                                                                         <font color='#fe7903'>Monk_Bonk (Luchs)
2245                                                   Awww... show me on the tank where the bad arty touched you...
2799                                                                    Enemy SPG <font color='#f8f400'>sp0ks (S-51)
2800                                                    Enemy SPG <font color='#fe0e00'>WMBB (Bat.-Châtillon 155 58)
2801                                               Enemy SPG <font color='#fe0e00'>gonzales_3 (Lorraine 155 mle. 50)
2802                                               Enemy SPG <font color='#fe0e00'>gonzales_3 (Lorraine 155 mle. 50)
2803                                                             Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)
2804                                                             Enemy SPG <font color='#fe7903'>EDELVEIS_UA (FV304)
2805                                              Enemy SPG <font color='#fe7903'>Leopard1965 (Lorraine 155 mle. 50)
2806                                                           Enemy SPG <font color='#fe7903'>PECHOLATA_65 (Hummel)
2807                                              Enemy SPG <font color='#fe7903'>T_55_Ladelude (AMX 105 AM mle. 47)
2808                                                                  Enemy SPG <font color='#fe7903'>pampos98 (M44)
17296                                      https://open.spotify.com/track/03RojRDRvvbFEPpabo3Aan?si=ef083469698742a4
17297  https://www.twitch.tv/malpa_gaming_ha_ha KONKURS NA ZLOTO I PREMIUM TANKS ..GIVEWAY FOR GOLD AND PREMIUM TANK
17298                                                                               https://www.twitch.tv/yung_xd ??
32458                                                                                     www.twitch.tv/vylizsikapsu
32459                                                                                     www.twitch.tv/vylizsikapsu
32460                                                                                                www.xvideos.com

       label artifact_status
12       0.0      drop_error
13       0.0      drop_error
14       0.0      drop_error
15       0.0      drop_error
16       0.0      drop_error
17       0.0      drop_error
18       0.0      drop_error
19       0.0      drop_error
20       0.0      drop_error
21       0.0      drop_error
22       0.0      drop_error
23       0.0      drop_error
24       0.0      drop_error
25       0.0      drop_error
26       0.0      drop_error
27       0.0      drop_error
28       0.0      drop_error
29       0.0      drop_error
30       0.0      drop_error
31       0.0      drop_error
82       0.0   drop_html_tag
1948     0.0   drop_html_tag
1949     0.0   drop_html_tag
2245     1.0        drop_url
2799     0.0   drop_html_tag
2800     0.0   drop_html_tag
2801     0.0   drop_html_tag
2802     0.0   drop_html_tag
2803     0.0   drop_html_tag
2804     0.0   drop_html_tag
2805     0.0   drop_html_tag
2806     0.0   drop_html_tag
2807     0.0   drop_html_tag
2808     0.0   drop_html_tag
17296    0.0        drop_url
17297    0.0        drop_url
17298    0.0        drop_url
32458    0.0        drop_url
32459    0.0        drop_url
32460    0.0        drop_url

Label distribution before artifact drop:
label
0.0    0.788114
1.0    0.156504
2.0    0.046752
3.0    0.006309
4.0    0.001607
5.0    0.000714
Name: proportion, dtype: float64

Label distribution after artifact drop:
label
0.0    0.787891
1.0    0.156661
2.0    0.046807
3.0    0.006316
4.0    0.001609
5.0    0.000715
Name: proportion, dtype: float64

Label distribution among dropped artifact rows:
label
0.0    0.975
1.0    0.025
Name: proportion, dtype: float64

Rows before artifact drop: 33603
Dropped 40 (0.1%)
Rows after artifact drop: 33563

In [26]:
# save again and evaluate 
x_train_artifact_clean.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_train.parquet", index=False)
# baseline - before any cleaning
impact = eval_step("artifact_removal", {"WoT": PROJECT_ROOT / "data/processed_data/wot/x_train.parquet"}, impact)
impact

            step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
artifact_removal     WoT 33563    0.5293       0.8591        0.6138           0.5236         -0.0011       -0.0028            0.001

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,WoT,42960,0.4743,0.8646,0.5476,0.4626,0.0000,0.0000,0.0000
1,non_latin_drop,WoT,39897,0.4930,0.8699,0.5725,0.4929,0.0187,0.0249,0.0303
2,non_english_drop,WoT,39836,0.5027,0.8699,0.5943,0.4929,0.0097,0.0218,0.0000
3,duplicates_removal,WoT,34239,0.4967,0.8667,0.5665,0.5028,-0.0060,-0.0278,0.0099
4,duplicates_majority,WoT,33603,0.5304,0.8584,0.6166,0.5226,0.0337,0.0501,0.0198
5,artifact_removal,WoT,33563,0.5293,0.8591,0.6138,0.5236,-0.0011,-0.0028,0.0010

In [27]:
# apply the same artifact cleaning to validation set for consistency
x_validation_clean = x_validation_lang_clean.copy()

x_validation_clean["message"] = x_validation_clean["message"].fillna("").astype(str)
x_validation_clean["message"] = x_validation_clean["message"].apply(html_lib.unescape)

x_validation_clean["artifact_status"] = x_validation_clean["message"].apply(artifact_status)

x_validation_artifact_clean = (
    x_validation_clean[x_validation_clean["artifact_status"] == "keep"]
    .drop(columns=["artifact_status"])
    .reset_index(drop=True)
)

# save 
x_validation_artifact_clean.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_validation.parquet", index=False)

#### Mislabeled data

In [28]:
# few top rows of the data
x_train_artifact_clean.head(10)

                                             message  label
0                                                  !    0.0
1                                                  !    0.0
2                                              ! CAP    0.0
3                                               !!!!    0.0
4                                               !!!!    0.0
5                                             !!!!!!    0.0
6                       !Siema kto PL Wn8 (300) IQ 6    0.0
7  "If you can‘t take a joke, you shouldn‘t be pl...    1.0
8                            "deals too much damage"    0.0
9                              "drives premium tank"    0.0

In [29]:
# class distribution check
print("Label distribution after cleaning:")
print(x_train_artifact_clean["label"].value_counts(normalize=True).sort_index())
print(x_train_artifact_clean["label"].value_counts(normalize=False).sort_index())

Label distribution after cleaning:
label
0.0    0.787891
1.0    0.156661
2.0    0.046807
3.0    0.006316
4.0    0.001609
5.0    0.000715
Name: proportion, dtype: float64
label
0.0    26444
1.0     5258
2.0     1571
3.0      212
4.0       54
5.0       24
Name: count, dtype: int64

We might have mislabeled toxicity data that was classified as non-toxic or opposite. We need to detect and fix that as well.

In [30]:
from cleanlab.filter import find_label_issues
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_predict, StratifiedKFold
import numpy as np

# exclude messages under 3 chars — no signal, cleanlab guesses randomly on them
cl_mask = x_train_artifact_clean["message"].str.len() >= 3
cl_df = x_train_artifact_clean[cl_mask].reset_index(drop=True)

X = cl_df["message"].values
y = cl_df["label"].astype(int).values

# stratified cv with shuffle — avoids ordering bias in folds
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=7524)

# lightweight pipeline to generate calibrated out-of-fold probabilities
# class_weight="balanced" — needed with imbalanced data so minority class errors are detected
# LR required (not SVC) — cleanlab needs predict_proba, not decision_function
pipe = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_df=0.95,
                              sublinear_tf=True, norm="l2",
                              analyzer="word", tokenizer=tokenize, token_pattern=None)),
    ("clf", LogisticRegression(max_iter=2000, random_state=7524, class_weight="balanced")),
])

# each sample predicted by model that never saw it during training
oof_probs = cross_val_predict(pipe, X, y, cv=cv, method="predict_proba", n_jobs=-1)

# normalized_margin more robust than self_confidence on imbalanced data —
# only flags rows where model is confident another class is correct, not just uncertain
issue_idx = find_label_issues(
    labels=y,
    pred_probs=oof_probs,
    return_indices_ranked_by="normalized_margin",
)

predicted = oof_probs[issue_idx].argmax(axis=1)
given = y[issue_idx]

# only trust 0 - {1,2} boundary crossings —
# class 3/4/5 too rare (< 1%) for reliable OOF predictions, causes kill/die false positives
boundary_mask = (
    ((given == 0) & np.isin(predicted, [1, 2]))
    | (np.isin(given, [1, 2]) & (predicted == 0))
)
issue_idx = issue_idx[boundary_mask]

print(f"Suspected mislabeled: {len(issue_idx)} ({len(issue_idx)/len(y):.1%})")

# inspect top 50 — compare original label vs what model predicted
print(cl_df.iloc[issue_idx[:50]][["message", "label"]].assign(
    predicted=oof_probs[issue_idx[:50]].argmax(axis=1)
))

# map issue positions in cl_df back to x_train_artifact_clean original index
original_idx = x_train_artifact_clean[cl_mask].index[issue_idx]

Suspected mislabeled: 2162 (6.7%)
                           message  label  predicted
18370                     just bot    0.0          1
7730                and an afk bot    0.0          1
28316                      top bot    0.0          1
2005                           Bot    0.0          1
18396        just come help idiots    0.0          1
30942      wtf i win this and loss    0.0          2
28348             top tier top bot    0.0          1
28165                       to bot    0.0          1
9124                 bot peregrine    0.0          1
2004                           Bot    0.0          1
5901               S5 was a bot :/    0.0          1
6502     This Tiger gotta be a bot    0.0          1
13403                  gg bot team    0.0          1
203                          *bots    0.0          1
15808               help your bots    0.0          1
26456        stupid retard campers    0.0          1
12209                    fckg bots    0.0          1
28284                too many bots    0.0          1
10252     cmon man when ur spotted    1.0          0
21038               next lt idiots    0.0          1
15637       heavys bot and chıcken    0.0          1
24377                  retard team    0.0          1
9105                     bot Wt mk    0.0          1
13571               gg retard team    0.0          1
20666                  move morons    0.0          1
175                  ****** morons    0.0          1
19821        loset game noobs team    0.0          1
7432            all one sidee lose    0.0          2
11216               dont lose this    0.0          2
11215                dont lose pls    0.0          2
27348    thats why you always lose    0.0          2
22855                   or we lose    0.0          2
15509              he made us lose    0.0          2
7935                  another lose    0.0          2
23326                pls dont lose    0.0          2
22078                 now its lose    0.0          2
19806                     lose now    0.0          2
19399     lights mega campers bots    0.0          1
13022       fucking useless morons    0.0          1
24441                  rigged lose    0.0          2
18077                   its a loss    0.0          2
21035                   next loss?    0.0          2
28739     u go there u are useless    0.0          1
28116                 time to lose    0.0          2
29710     we still can lose it omg    0.0          2
18528       just waint and we lose    0.0          2
30500  why play, gonna lose anyway    0.0          2
13379        gg again lose team ..    0.0          2
7934                  another lose    0.0          2
28347             top tier td bots    0.0          1

In [31]:
# drop suspected mislabeled — safer than relabeling with own OOF predictions
# cleanlab paper recommends pruning over relabeling to avoid feedback loop
x_train_artifact_clean1 = x_train_artifact_clean.drop(index=original_idx).reset_index(drop=True)
print(f"Dropped {len(original_idx)} suspected mislabeled rows ({len(original_idx)/len(x_train_artifact_clean):.1%})")

Dropped 2162 suspected mislabeled rows (6.4%)

Cleanlab flagged suspected mislabeled rows using out-of-fold predictions — each sample scored
by a model that never saw it during training. Only 0↔{1,2} boundary crossings are kept:
cases where the model is confident a non-toxic message should be toxic or vice versa.

Flagged rows are **dropped** rather than relabeled. Relabeling with the same model's OOF
predictions creates a feedback loop — the model cleans the data toward its own biases,
then trains on that data. Dropping removes the uncertain examples without introducing
model-generated labels into the training set (Northcutt et al., 2021).

In [32]:
# save again and evaluate 
x_train_artifact_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_train.parquet", index=False)
impact = eval_step("cleanlab_relabeling", {"WoT": PROJECT_ROOT / "data/processed_data/wot/x_train.parquet"}, impact)
impact

               step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
cleanlab_relabeling     WoT 31401    0.5758       0.9069        0.6496           0.5829          0.0465        0.0358           0.0593

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,WoT,42960,0.4743,0.8646,0.5476,0.4626,0.0000,0.0000,0.0000
1,non_latin_drop,WoT,39897,0.4930,0.8699,0.5725,0.4929,0.0187,0.0249,0.0303
2,non_english_drop,WoT,39836,0.5027,0.8699,0.5943,0.4929,0.0097,0.0218,0.0000
3,duplicates_removal,WoT,34239,0.4967,0.8667,0.5665,0.5028,-0.0060,-0.0278,0.0099
4,duplicates_majority,WoT,33603,0.5304,0.8584,0.6166,0.5226,0.0337,0.0501,0.0198
5,artifact_removal,WoT,33563,0.5293,0.8591,0.6138,0.5236,-0.0011,-0.0028,0.0010
6,cleanlab_relabeling,WoT,31401,0.5758,0.9069,0.6496,0.5829,0.0465,0.0358,0.0593

Gains could be inflated if the model memorizes its own training signal.
Verify with LinearSVC as an independent second model.

In [33]:
from sklearn.svm import LinearSVC
# impact 
impact = eval_step("cleanlab_relabeling_svc", {"WoT": PROJECT_ROOT / "data/processed_data/wot/x_train.parquet"}, impact, 
                                  clf=LinearSVC(max_iter=2000, random_state=7524, 
                                                class_weight = "balanced"))
impact

                   step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
cleanlab_relabeling_svc     WoT 31401    0.6136       0.9183        0.6024           0.6542          0.0378       -0.0472           0.0713

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,WoT,42960,0.4743,0.8646,0.5476,0.4626,0.0000,0.0000,0.0000
1,non_latin_drop,WoT,39897,0.4930,0.8699,0.5725,0.4929,0.0187,0.0249,0.0303
2,non_english_drop,WoT,39836,0.5027,0.8699,0.5943,0.4929,0.0097,0.0218,0.0000
3,duplicates_removal,WoT,34239,0.4967,0.8667,0.5665,0.5028,-0.0060,-0.0278,0.0099
4,duplicates_majority,WoT,33603,0.5304,0.8584,0.6166,0.5226,0.0337,0.0501,0.0198
5,artifact_removal,WoT,33563,0.5293,0.8591,0.6138,0.5236,-0.0011,-0.0028,0.0010
6,cleanlab_relabeling,WoT,31401,0.5758,0.9069,0.6496,0.5829,0.0465,0.0358,0.0593
7,cleanlab_relabeling_svc,WoT,31401,0.6136,0.9183,0.6024,0.6542,0.0378,-0.0472,0.0713

Score gains hold under both LR and LinearSVC. The cleaning is real — label corrections reflect genuine annotation noise, not model self-confirmation.

In [34]:
# fit on full train
pipe.fit(x_train_artifact_clean1["message"], x_train_artifact_clean1["label"])
val_probs = pipe.predict_proba(x_validation_artifact_clean["message"])

# find suspicious val labels — no circularity, model never saw val
val_issues = find_label_issues(
    labels=x_validation_artifact_clean["label"].astype(int).values,
    pred_probs=val_probs,
    return_indices_ranked_by="normalized_margin"
)

val_predicted = val_probs[val_issues].argmax(axis=1)
val_given = x_validation_artifact_clean["label"].astype(int).values[val_issues]

boundary_mask = (
    ((val_given == 0) & np.isin(val_predicted, [1, 2, 3]))
    | (np.isin(val_given, [1, 2, 3]) & (val_predicted == 0))
)
val_issues_filtered = val_issues[boundary_mask]

print(f"Suspected val mislabeled: {len(val_issues_filtered)} ({len(val_issues_filtered)/len(x_validation_artifact_clean):.1%})")

# inspect top 50
print(x_validation_artifact_clean.iloc[val_issues_filtered[:50]][["message", "label"]].assign(
    predicted=val_probs[val_issues_filtered[:50]].argmax(axis=1)
))

Suspected val mislabeled: 652 (6.6%)
                                    message  label  predicted
6345                                 idiots    0.0          1
1263                     damn idiots noone?    0.0          1
8629                                    bot    0.0          1
6319                              its a bot    0.0          1
6191                       top tier top bot    0.0          1
6151                       was that a bot??    0.0          1
9511                                    bot    0.0          1
414                             t1heavy bot    0.0          1
295                                     bot    0.0          1
3560                                    bot    0.0          1
3481                              me bot...    0.0          1
7463                                    bot    0.0          1
2002                         help your bots    0.0          1
2014                                go bots    0.0          1
669                          haftoo be bots    0.0          1
2891                       tem full of bots    0.0          1
9644                                   bots    0.0          1
8798                                   lose    0.0          2
1270                                or lose    0.0          2
4097                                   lose    0.0          2
4834                                we lose    0.0          2
2984                     Not my bad if lose    0.0          2
5046                   consider this a loss    0.0          2
8899                                   loss    0.0          2
1167                    here ocmes the loss    0.0          2
7850                              next loss    0.0          2
5143                        nice loss cobra    0.0          2
5024                             heavys bot    0.0          1
7154                    so am i.. im a noob    0.0          1
859                               damn noob    0.0          1
5181                              lol moron    0.0          1
5958                              good spot    1.0          0
9753                         get out of cap    1.0          0
4573                                    cap    1.0          0
3742                                    cap    2.0          0
1849                           cap or loose    2.0          0
4588                medslll spot mid idiots    0.0          1
7218     if you play to lose you never lose    0.0          2
1436     Chieftain reported for AFK/BOT too    0.0          1
2851  shoot if you hate the match - fucking    0.0          2
9240           EBR 105 reported for AFK/BOT    0.0          1
8206                                 polish    0.0          3
7329                           PUSH YOU ***    1.0          0
4499                           I am useless    0.0          1
4105                          Useless tiger    0.0          1
6746                                    ffs    0.0          2
7177                                    ffs    0.0          2
396                                 campers    0.0          1
6002   pls reported all panther m10 afk bot    0.0          1
8406                  wtf i have full hp xD    0.0          2

Cleanlab estimated ~6.7% annotation noise in the validation set using a model trained
on cleaned training data. Clear annotation errors exist: "bot", "idiots", "moron"
labeled as non-toxic (class 0) are genuine annotator mistakes.

**Why val labels are left unchanged:**

Dropping or relabeling val rows based on a train-fitted model is circular — the model
decides what to remove from its own test set, then gets evaluated on the cleaner result.
This inflates metrics without reflecting real improvement.

Val metrics are slightly pessimistic due to annotation noise. This is the honest
evaluation of model performance on real-world noisy data.

#### Final verification

In [35]:
# basic data checks for train and validation sets after cleaning and relabeling
print("Final training set shape:", x_train_artifact_clean1.shape)
print("Final validation set shape:", x_validation_artifact_clean.shape)
print("\nFinal training set label distribution:")
print(x_train_artifact_clean1["label"].value_counts(normalize=True).sort_index())
print("\nFinal validation set label distribution:")
print(x_validation_artifact_clean["label"].value_counts(normalize=True).sort_index())

Final training set shape: (31401, 2)
Final validation set shape: (9899, 2)

Final training set label distribution:
label
0.0    0.794306
1.0    0.154167
2.0    0.042292
3.0    0.006751
4.0    0.001720
5.0    0.000764
Name: proportion, dtype: float64

Final validation set label distribution:
label
0.0    0.813213
1.0    0.136276
2.0    0.043540
3.0    0.004950
4.0    0.001515
5.0    0.000505
Name: proportion, dtype: float64

In [36]:
# save to parquet for easier loading in future steps
# train
x_train_artifact_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_train.parquet", index=False)
# validation
x_validation_artifact_clean.to_parquet(PROJECT_ROOT / "data/processed_data/wot/x_validation.parquet", index=False)
# save preprocessing ablation results
impact.to_csv(PROJECT_ROOT / "data/results/cleaning_ablation_wot.csv", index=False)
print("Saved WoT cleaning ablation CSV")

Saved WoT cleaning ablation CSV

## Dota

**Dota**
| Class | Label |
|---|---|
| 0 | Other (non-toxic) |
| 1 | Ego |
| 2 | Aggression |
| 3 | Impolite |

#### Inspect each split

In [37]:
# import data
train = pd.read_csv(DATA_DIR_DOTA / "CONDA_train.csv")
val = pd.read_csv(DATA_DIR_DOTA / "CONDA_valid.csv")

# inspect each split
for name, df in [("train", train), ("val", val)]:
    print(f"--- {name} ---")
    print(f"Shape: {df.shape}\n")
    print(f"Columns: {list(df.columns)}\n")
    print(f"First few rows of the data:\n{df.head(3)}\n")

--- train ---
Shape: (26921, 10)

Columns: ['Id', 'matchId', 'conversationId', 'utterance', 'chatTime', 'playerSlot', 'playerId', 'intentClass', 'slotClasses', 'slotTokens']

First few rows of the data:
      Id  matchId  conversationId utterance  chatTime  playerSlot  \
0  11263      697            3193      wow!        76           0
1  13741      843            3809       WTF      1563           5
2  22125     1412            6199   wpe wpe      2853           1

                  playerId intentClass slotClasses          slotTokens
0  ANTS IN MY EYES JOHNSON           O          O            wow (O),
1                      M.k           O          T            WTF (T),
2              Acqua Ragia           O        O O   wpe (O), wpe (O),

--- val ---
Shape: (8974, 10)

Columns: ['Id', 'matchId', 'conversationId', 'utterance', 'chatTime', 'playerSlot', 'playerId', 'intentClass', 'slotClasses', 'slotTokens']

First few rows of the data:
      Id  matchId  conversationId                 utterance  chatTime  \
0   6911      456            1987                        GG      3031
1   1512      132             509                        gg      2887
2  43138     2905           12306  GG [SEPA] nice late game      2783

   playerSlot                         playerId intentClass    slotClasses  \
0           9                               OG           O             S
1           9                             Xion           O             S
2           1  Im  good but my team is so  bad           O  S SEPA O O O

                                          slotTokens
0                                           GG (S),
1                                           gg (S),
2  GG (S), [SEPA] (SEPA), nice (O), late (O), gam...

#### Clean, merge and standardise

In [38]:
# map intentClass to numeric label consistent with WoT schema
label_map = {'O': 0, 'E': 1, 'A': 2, 'I': 3}

# add split column and map labels
train["split"] = "train"
val["split"]   = "val"

# merge train + val (no test split in CONDA)
dota = pd.concat([train, val], ignore_index=True)

# keep only relevant columns and rename to match WoT schema
dota = dota[["Id", "utterance", "intentClass", "split"]].rename(columns={
    "Id": "index",
    "utterance":   "message",
    "intentClass": "label",
})

# map string labels to numeric
dota["label"] = dota["label"].map(label_map)

# drop nulls in message (7 train + 1 val)
dota = dota.dropna(subset=["message"]).reset_index(drop=True)

# shape 
print(f"Merged shape: {dota.shape}\n")
print(f"First few rows of the data:\n{dota.head(3)}\n")
print("\nInformation about the dataset:\n")
dota.info()

Merged shape: (35887, 4)

First few rows of the data:
   index  message  label  split
0  11263     wow!      0  train
1  13741      WTF      0  train
2  22125  wpe wpe      0  train


Information about the dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    35887 non-null  int64
 1   message  35887 non-null  object
 2   label    35887 non-null  int64
 3   split    35887 non-null  object
dtypes: int64(2), object(2)
memory usage: 1.1+ MB

In [39]:
# X and Y
X = dota["message"]
y = dota["label"]

# split the data into our train and test 
x_train, x_validation, y_train, y_validation = train_test_split(X, y, test_size=0.2, random_state=seed, 
                                             shuffle = True, stratify=y)

# distributions for each split 
print("Distribution of labels in the training set normalized and not-normalized:")
print(y_train.value_counts())
print(y_train.value_counts(normalize=True))
print("\nDistribution of labels in the validation set normalized and not-normalized:")
print(y_validation.value_counts())
print(y_validation.value_counts(normalize=True))

# save both datasets as one parquet file each, with message and label columns,
# for easier processing in the next steps
x_train = pd.DataFrame({"message": x_train, "label": y_train})
x_validation = pd.DataFrame({"message": x_validation, "label": y_validation})
x_train.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_train.parquet", index=False)
x_validation.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_validation.parquet", index=False)

Distribution of labels in the training set normalized and not-normalized:
label
0    21282
1     3769
2     1839
3     1819
Name: count, dtype: int64
label
0    0.741301
1    0.131283
2    0.064057
3    0.063360
Name: proportion, dtype: float64

Distribution of labels in the validation set normalized and not-normalized:
label
0    5321
1     942
2     460
3     455
Name: count, dtype: int64
label
0    0.741293
1    0.131234
2    0.064085
3    0.063388
Name: proportion, dtype: float64

In [40]:
# do baseline evaluation before any cleaning
impact = None
impact = eval_step("baseline", {"DOTA": PROJECT_ROOT / "data/processed_data/dota/x_train.parquet"}, impact)

    step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
baseline    DOTA 28709    0.7204        0.851        0.7544           0.7013             0.0           0.0              0.0

Only `utterance`, `intentClass`, `Id`, and `split` are kept = the remaining columns (matchId, conversationId, chatTime, playerSlot, playerId, slotClasses, slotTokens) carry no linguistic content relevant to toxicity detection. Labels are mapped to integers matching the WoT schema where 0 = non-toxic. Null utterances are dropped - they carry no text signal.

#### Non-english language

Since we are going to model classifier on english data, it is important for us to detect non-english cases as many as we can.

In [41]:
# covers all major non-Latin scripts
NON_LATIN_SCRIPT = re.compile(
    r"[\u0400-\u04FF"   # Cyrillic
    r"\u4E00-\u9FFF"    # CJK unified ideographs
    r"\u3400-\u4DBF"    # CJK extension A
    r"\uF900-\uFAFF"    # CJK compatibility ideographs
    r"\u0600-\u06FF"    # Arabic
    r"\u0590-\u05FF"    # Hebrew
    r"\u3040-\u30FF"    # Japanese (Hiragana + Katakana)
    r"\uAC00-\uD7AF"    # Korean (Hangul syllables)
    r"\u1100-\u11FF"    # Korean (Hangul Jamo)
    r"\u0E00-\u0E7F"    # Thai
    r"\u0900-\u097F"    # Devanagari (Hindi)
    r"\u0980-\u09FF"    # Bengali
    r"\u0370-\u03FF"    # Greek
    r"\u10A0-\u10FF"    # Georgian
    r"\u0530-\u058F"    # Armenian
    r"\u1000-\u109F"    # Myanmar
    r"\u1780-\u17FF]"   # Khmer
)

# drop any message containing even 1 non-Latin script char
print(f"Non-english documents:\n{x_train[x_train['message'].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)}\n")

before = len(x_train)
x_train_en = x_train[~x_train["message"].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)
print(f"Dropped {before - len(x_train_en)} ({(before - len(x_train_en))/before:.1%})")
print("Label distribution before:")
print(x_train["label"].value_counts(normalize=True).sort_index(), "\n")

print("\nLabel distribution after:")
print(x_train_en["label"].value_counts(normalize=True).sort_index(), "\n")
print(f"Rows after the drop: {x_train_en.shape[0]}")
# save new step again
x_train_en.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_train.parquet", index=False)

Non-english documents:
                                     message  label
0                                        Νοο      0
1                                        戒了吧      0
2                                          ツ      0
3                                         ำผ      0
4   dochu....양학....... [SEPA] 일본...재패니즈몽키...      0
5                        s [SEPA] v [SEPA] ツ      0
6                                          ื      0
7                                         ทำ      0
8                                      คนไทย      0
9                                      ใจยเน      0
10                              ไย [SEPA] wp      0
11                                 ¯\_(ツ)_/¯      0
12      sure go mid with bh [SEPA] ¯\_(ツ)_/¯      0
13                                 ¯\_(ツ)_/¯      0
14                           noob [SEPA] กาก      1
15                              เเ [SEPA] gg      0
16                                       กาก      0

Dropped 17 (0.1%)
Label distribution before:
label
0    0.741301
1    0.131283
2    0.064057
3    0.063360
Name: proportion, dtype: float64


Label distribution after:
label
0    0.741182
1    0.131326
2    0.064095
3    0.063397
Name: proportion, dtype: float64

Rows after the drop: 28692

In [42]:
# save and evaluate non-Latin drop
impact = eval_step("non_latin_drop", {"DOTA": PROJECT_ROOT / "data/processed_data/dota/x_train.parquet"}, impact)
impact

          step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
non_latin_drop    DOTA 28692    0.7225       0.8518        0.7556            0.704          0.0021        0.0012           0.0027

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,DOTA,28709,0.7204,0.8510,0.7544,0.7013,0.0000,0.0000,0.0000
1,non_latin_drop,DOTA,28692,0.7225,0.8518,0.7556,0.7040,0.0021,0.0012,0.0027

In [43]:
# transform that on the validation set as well, to be consistent with the training data.
# drop any message containing even 1 non-Latin script char
print(f"Non-english documents:\n{x_validation[x_validation['message'].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)}\n")

# changes 
before = len(x_validation)
x_validation_en = x_validation[~x_validation["message"].str.contains(NON_LATIN_SCRIPT, regex=True, na=False)].reset_index(drop=True)
print(f"Dropped {before - len(x_validation_en)} ({(before - len(x_validation_en))/before:.1%})")
print("Label distribution before:")
print(x_validation["label"].value_counts(normalize=True).sort_index(), "\n")

print("\nLabel distribution after:")
print(x_validation_en["label"].value_counts(normalize=True).sort_index(), "\n")
print(f"Rows after the drop: {x_validation_en.shape[0]}")
# save new step again
x_validation_en.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_validation.parquet", index=False)

Non-english documents:
      message  label
0  ညသ တေမိ  ၊      0

Dropped 1 (0.0%)
Label distribution before:
label
0    0.741293
1    0.131234
2    0.064085
3    0.063388
Name: proportion, dtype: float64


Label distribution after:
label
0    0.741257
1    0.131253
2    0.064094
3    0.063397
Name: proportion, dtype: float64

Rows after the drop: 7177

Decreases are minor and more likely to be noise.

In [44]:
from lingua import Language, LanguageDetectorBuilder

# detecting Latin-script but likely non-English messages

# use all Latin-script languages supported by Lingua
# English must stay inside the detector, otherwise English text gets forced into another language
LATIN_LANGUAGES = list(Language.all_with_latin_script())

# detector for Latin-script language detection
# minimum_relative_distance: if top languages are too close, Lingua returns None instead of guessing
detector = (
    LanguageDetectorBuilder
    .from_languages(*LATIN_LANGUAGES)
    .with_minimum_relative_distance(0.25)
    .build()
)

# safety tokens: if these appear, keep the message because it may be gaming/chat English or mixed slang
SAFETY_TOKENS = {
    # gaming / chat
    "gg", "ez", "wp", "gl", "hf", "glhf", "afk", "brb", "lol", "lmao", "lmfao",
    "omg", "wtf", "stfu", "noob", "n00b", "bot", "team", "report", "ban",
    "kick", "mute", "trash", "toxic", "troll", "feed", "feeder", "int", "throw",
    "rank", "elo", "kill", "kys", "die", "fps", "lag", "ping", "server",
    "wot", "dota", "fortnite", "fn",

    # English / toxicity cues
    "you", "your", "you're", "u", "ur", "are", "is", "this", "that", "the",
    "and", "not", "dont", "don't", "fuck", "fucking", "fuk", "fck", "shit",
    "bitch", "ass", "asshole", "idiot", "stupid", "dumb", "moron", "loser",
    "suck", "sucks"
}

TOKEN_RE = re.compile(r"[a-z0-9']+", flags=re.IGNORECASE)


def get_tokens(text):
    return set(TOKEN_RE.findall(str(text).lower()))


def has_safety_token(text):
    return bool(get_tokens(text) & SAFETY_TOKENS)


# function to classify what to do with each Latin-script message
def latin_language_filter_status(text):
    text_str = str(text).strip()
    tokens = get_tokens(text_str)

    # too short - keep
    # language detection is unreliable on short gaming/chat messages
    if len(text_str) < 50 or len(tokens) < 6:
        return "keep_short"

    # possible gaming/chat/English false positive - keep
    if has_safety_token(text_str):
        return "keep_possible_gaming_or_mixed"

    lang = detector.detect_language_of(text_str)

    # ambiguous - keep
    if lang is None:
        return "keep_ambiguous"

    # English - keep
    if lang == Language.ENGLISH:
        return "keep_english"

    # confident Latin-script non-English - drop
    return f"drop_latin_nonenglish_{lang.name.lower()}"


# apply detection
x_train_en_lang = x_train_en.copy()
x_train_en_lang["lang_filter_status"] = x_train_en_lang["message"].apply(latin_language_filter_status)

# inspect groups
print("Language filter status counts:")
print(x_train_en_lang["lang_filter_status"].value_counts().head(30))


# check ambiguous cases
# these are messages where Lingua did not confidently choose a language
ambiguous_mask = x_train_en_lang["lang_filter_status"].eq("keep_ambiguous")

print(f"\nAmbiguous Latin-script language documents kept: {ambiguous_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nAmbiguous documents kept for now:\n",
        x_train_en_lang.loc[
            ambiguous_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among ambiguous rows:")
print(
    x_train_en_lang.loc[ambiguous_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# check possible gaming / mixed-language false positives
# these are messages that Lingua might classify as non-English, but contain gaming/chat/English cues
mixed_mask = x_train_en_lang["lang_filter_status"].eq("keep_possible_gaming_or_mixed")

print(f"\nPossible gaming or mixed-language documents kept: {mixed_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nPossible gaming/mixed documents kept for now:\n",
        x_train_en_lang.loc[
            mixed_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among possible gaming/mixed rows:")
print(
    x_train_en_lang.loc[mixed_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# drop only confident Latin-script non-English rows
drop_mask = x_train_en_lang["lang_filter_status"].str.startswith("drop_latin_nonenglish")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nConfident Latin-script non-English documents to drop:\n",
        x_train_en_lang.loc[
            drop_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print(f"\nHow many confident Latin-script non-English documents: {drop_mask.sum()}")


# label distribution sanity check
dropped_latin_nonenglish = x_train_en_lang.loc[drop_mask]

print("\nLabel distribution before Latin non-English drop:")
print(x_train_en["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after Latin non-English drop:")
print(
    x_train_en_lang.loc[~drop_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nLabel distribution among dropped rows:")
print(
    dropped_latin_nonenglish["label"]
    .value_counts(normalize=True)
    .sort_index()
)


# create dataset after Latin non-English drop
# keep ambiguous and mixed/gaming rows
x_train_lang_clean = (
    x_train_en_lang
    .loc[~drop_mask]
    .drop(columns=["lang_filter_status"])
    .reset_index(drop=True)
)

print(f"\nRows before Latin non-English drop: {len(x_train_en)}")
print(f"Dropped {drop_mask.sum()} ({drop_mask.sum() / len(x_train_en):.1%})")
print(f"Rows after Latin non-English drop: {len(x_train_lang_clean)}")

Language filter status counts:
lang_filter_status
keep_short                          26765
keep_possible_gaming_or_mixed        1652
keep_ambiguous                        153
keep_english                          109
drop_latin_nonenglish_tagalog           5
drop_latin_nonenglish_portuguese        4
drop_latin_nonenglish_spanish           3
drop_latin_nonenglish_sotho             1
Name: count, dtype: int64

Ambiguous Latin-script language documents kept: 153

Ambiguous documents kept for now:
                                                                                                                                                                                    message  \
52                                                                                                                                we stack [SEPA] his comp crash [SEPA] pls wait rebooting
244                                                                                                                     +++++++ [SEPA] Invo jungle [SEPA] Best jungle [SEPA] Go finish now
262                                                                                                            SOS UN ASCO PUDGE TE REPORTO  [SEPA] NO PODES JUGAR ASI EN RANKED [SEPA] :V
321                                                                                                                                    delay [SEPA] 20 sec [SEPA] plz [SEPA] rdy [SEPA] ty
571                                                                                                                                     just jug carry so hard [SEPA] he farms like a boss
663                                                                                                             LOLOLOLOLL [SEPA] come back wisp [SEPA] ya fucken dog [SEPA] hahahahhahaha
793                                                                                                                               i have viper premuted [SEPA] he say anything XD [SEPA] ?
949                                                                                                                GRET [SEPA] JUST [SEPA] spam [SEPA] ursa [SEPA] everysingle [SEPA] game
1119                                                                                                                           he 63 sec [SEPA] go? [SEPA] maybe? [SEPA] computer restart?
1290                                                                                                                               fuark [SEPA] only one who didnt lose tower in lane hehe
1367                                                                .qw3kje kowqnheui49jqwmke yqakmsd fvbr2uwieoakf8u49gjirufjnghyju3iuwjfmg h4ijuwiksdfuyiMuyijamjy879ialnbyhabhgl;gnholb
1849                                                                                                                          1 KITER [SEPA] + 1 JUNGLE [SEPA] 1 PUDGE OFF [SEPA] AUTOLOSE
1907                                                                                                          okay 5 man mid [SEPA] 5v5 lets go [SEPA] whoever wins [SEPA] optjer concedes
2012                                                                                                     1 2 3 4 5 6 7 8 9 10 11 12 13  14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
2043                                                                                                                         my wr [SEPA] went blink instead of midas [SEPA] nice blink wr
2053                                                                                                                          smh [SEPA] faithless one [SEPA] fuckig ngiga [SEPA] pl nigga
2239                                                                                                                         siege creepz plz [SEPA] wow so much gold  [SEPA] cant believe
2459                                                                                                                               so scare to lose??/ [SEPA] alrd 4 v 5 still dunwan wait
2595                                                                                                                    5K4 BOYZ [SEPA] 1-16 [SEPA] 4-12 [SEPA] SAME PARTY for a reason eh
2889                                                                                                                         let's wait [SEPA] buy back to dead? [SEPA] when Jugg got MKB?
3140                                                                                                            free rosh [SEPA] free top [SEPA] free mid [SEPA] look at slark [SEPA] ))))
3486                                                                                                                       so dank [SEPA] xd [SEPA] 'hes online' [SEPA] online in hell men
3789                                                                                                                                   dunno just to gob smacked [SEPA] by slark [SEPA] ya
4008                                                                                                                                   WIN [SEPA] RAKI NE DAYT WIN [SEPA] ))) [SEPA] NA PA
4239                                                                                                                              we had a 33 last hits at 33 minutes lone druid last time
4473                                                                                                                             nah [SEPA] wollongong [SEPA] south of sydney [SEPA] dapto
4559                                                                                                                                 what a [SEPA] clever gho :D [SEPA] 29-11 [SEPA] 29-1*
5271                                                                                                                               WE LOST SAFELANE [SEPA] FOR SURE [SEPA] WE FVCKING LOST
5315                                                                                                                                  y so slow PA [SEPA] hahaha [SEPA] wait PA i will mkb
5972                                                                                                          wai [SEPA] i cant move [SEPA] Help [SEPA] i cant move my hero [SEPA] help me
6198                                                                                                   mom [SEPA] manta [SEPA] 35m ins [SEPA] Safelaen [SEPA] mazing [SEPA] b ought acount
6205                                                                                                                                    nice [SEPA] Care [SEPA] b [SEPA] sf  [SEPA] coming
6368                                                                                                                             ? [SEPA] 179 goldi [SEPA] so slardara [SEPA] na freefarme
6468                                                                                                                                Looks ok to me bro [SEPA] Mirana off [SEPA] Sven carry
6701                                                                                                                  ggwp [SEPA] end please [SEPA] emd ! [SEPA] end ! [SEPA] wasting time
6893                                                                                                                        + [SEPA] wr 3 slota [SEPA] 39 minut [SEPA] solo mid [SEPA] )))
7013                                                                                 last 20 sec [SEPA] 19 [SEPA] 18 [SEPA] 17 [SEPA] 16 [SEPA] 15 [SEPA] 14 [SEPA] 13 [SEPA] 12 [SEPA] 11
7335                                                                                                          hahahahaha [SEPA] 2v5 [SEPA] hahaha [SEPA] yeah [SEPA] they win [SEPA] hahah
7456                                                                                                                         sad [SEPA] SAD [SEPA] VERY [SEPA] End fast. [SEPA] Fuckingmmr
7725                                                                                                                                  wak kok lawannya cupu bgt ya [SEPA] sorry wrong chat
7873                                                                                                                                  i am 22 13 [SEPA] reprot pudge [SEPA] ty [SEPA] 1 11
8247                                                                                                                                   a bit [SEPA] high ground right now so yes, i'm hihg
8574                                                                                                               loooooolll [SEPA] fcukin retared mid [SEPA] fail mid 35 min only orchid
8851                                                                                                                                   hey 1 [SEPA] i'm a peruvian :s [SEPA] but nice kind
9259                                                                                                                                    :( [SEPA] my flesh spoils [SEPA] but im a robot...
9623                                                                                                                             he didnt lose [SEPA] mid [SEPA] i lost mid [SEPA] s ohard
9633                                                  znaete [SEPA] pered tem ka kriki slil gem [SEPA] on napisal [SEPA] *ja umeju igratj na riki s gemom* [SEPA] *chtobi ne potreatj ego*
9666                                                                                                                                  1 0 0 [SEPA] 15 mib [SEPA] min* [SEPA] fine [SEPA] 
9895                                                                                                                                void [SEPA] talk? [SEPA] plzzz [SEPA] tower [SEPA] top
10192                                                                                                                         good luck to all ^_^ [SEPA] hi or high??? im high hahahahaha
10460                                                                                                                                   no# [SEPA] no [SEPA] YES [SEPA] i died a happy man
10468                                                                                                                         get my divine [SEPA] yie  [SEPA] divine [SEPA] qop so strong
10572                                                                                                      fight with 3 ussles hero  [SEPA] bastard [SEPA] 1000 hp mid carry [SEPA] 900 hp
10636                                                                                                                 jippers trippers. [SEPA] its fine  [SEPA] we were just having fun ;)
10776                                                                                                                            pudge_pick{ [SEPA] If cm_pick(); yes [SEPA] If false; yes
10963                                                                                                                        ***N I K I T A*** DOWN !!!  [SEPA] ***N I K I T A*** DOWN !!!
11228                                                                                                                         5200 = RO [SEPA] 5150 = radiance [SEPA] still build radiance
11509                                                                                                         easy mid [SEPA] easy life [SEPA] look at my denies [SEPA] easy mid easy life
11619                                                                                                                       I fingered a heterosexual [SEPA] how it feels ? [SEPA] brood ?
12058                                                                                                             GIVE ME [SEPA] YEAH [SEPA] ALL CARRIES [SEPA] HAHAHA [SEPA] GGWP Guys :)
12412                                                                                                              3 min [SEPA] pls [SEPA] connection [SEPA] problem [SEPA] reset computer
12669                                                                                                                              like [SEPA] flashy plays won't give wr farm [SEPA] nice
12767                                                                                                                             mid retards [SEPA] r s o unbeliaveblay  bad lma [SEPA] O
13049                                                                        TAS AS BAD AS SF [SEPA] WHY CNT I GET A COMPETNENT CORE [SEPA] ONE GAME [SEPA] thank god [SEPA] he abanbdoned
13091                                                                                                                                  k [SEPA] casual 5 man own woods [SEPA] real 5k game
13317                                                                                                rofl [SEPA] ai have aeg [SEPA] ( [SEPA] he use [SEPA] doom [SEPA] on aego [SEPA] rofl
13553                                                                                                                      easy 1k [SEPA] 1k gold [SEPA] 2k lost in a row [SEPA] dead crow
13962                                                                                                                        hit freeand me againt wr [SEPA] see [SEPA] hahhaa [SEPA] why?
14071                                                                                                              é lixo [SEPA] fiz oq pud [SEPA] nucna vi um aa [SEPA] joga tanto cotnra
14376                                                                                                                             While he afkd in my lane [SEPA] using Q to get last hits
15598                                                                                 oh goddddddddddddddddddddddddddddddd [SEPA] hes gotta have a buddy [SEPA] or he cant hook [SEPA] rip
15702                                                                                                                            no bf [SEPA] 26 min [SEPA] :D [SEPA] CDEC [SEPA] AGRESSIF
16051                                                                                                          make him play low prio [SEPA] hard to get out of low prio now [SEPA] hahaha
16087                                                                                                                               sladar tell me [SEPA] he rage quit [SEPA] end game plz
16110                                                                                                                                  I gotta pick slardar, slardar owning my teams today
16393                                                                                                                        i want too [SEPA] slark items [SEPA] =) [SEPA] finish im done
16439                                                                                                                               CUZ MIDDLE RETARD FOR ME [SEPA] NO GANK [SEPA] NO HELP
16492                                                                                                                               Atlas na bobo tanginmao [SEPA] pa cute [SEPA] HAHAHAHA
16501                                                                                                                                 brain dog [SEPA] random :)) [SEPA] i know  [SEPA] 4k
16853                                                                                                                                 i never died solo to am in lane [SEPA] Eveeeerrrrrrr
17052                                                                                                                       go vse [SEPA] poocheredi [SEPA] a to sam [SEPA] voker [SEPA] 0
17073                                                                                                               he`s don`t so important [SEPA] guys [SEPA] d0 [SEPA] :D [SEPA] be true
17107                                                                                                                            15 level hahaha nice build haha [SEPA] no carry buld haha
17167                                                                                                                                 29 [SEPA] 28 [SEPA] 27 [SEPA] 26 [SEPA] 25 [SEPA] 24
17496                                                                                                                        wow [SEPA] qop pickers [SEPA] what a hard hero [SEPA] to play
17580                                                                                                                             sniper lost game for them [SEPA] gyro sange yasha 13 min
17640                                                                                                   noobs [SEPA] EZZZZZZZZZZZZZZ [SEPA] MUITO FACIL [SEPA] 3 ruim mid [SEPA] 3 bad mid
18052                                                                                                                                  haha [SEPA] sad game [SEPA] sad player [SEPA] muted
18117                                  OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [SEPA] OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [SEPA] OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog
18281                                                                                                                              dat injoker make's sence [SEPA] autism ? [SEPA] englioh
18577                                                                                                                       40 MIN BM  DRUM [SEPA] LETS FLAME INVOKER [SEPA] mother fucker
18607                                                                                                                       thats like saying [SEPA] i rekt a ranged creep [SEPA] 10 times
18676                                                                                                                      weooh [SEPA] GOD kahh. [SEPA] deads on arrivall .. [SEPA] weooh
19001                                                                                                               btw [SEPA] dnt get reaped [SEPA] scepter liao [SEPA] 30 sec added time
19480                                                                                                                       lvl 1 qop  [SEPA] i win' [SEPA] ehehehehee [SEPA] all ogre now
19700                                                                          cant win nid with shtorm  [SEPA] yea [SEPA] cant ult  [SEPA] or buy wards [SEPA] mili herto  [SEPA] on line
20089                                                                                                                     SHACKLESHOT pros ahahahaha xD [SEPA] COMEND WR PLEASE AHAHAAH XD
20512                                                                                                                            run sf [SEPA] run son [SEPA] quick [SEPA] run [SEPA] lawl
20606                                                                                                                              nah [SEPA] i actuially tp'ed in  [SEPA] alone [SEPA] :/
20631                                                                                                                          porra perdi 400 de mmr [SEPA] nessa semana [SEPA] kkkkkkkkk
21056                                                                                                                         typical sb :s [SEPA] i wanna see 1 good sf [SEPA] in my life
21138                                                                                                                            veryyy needed [SEPA] jugg has downs [SEPA] same with riki
21428                                                                                                                              ofc [SEPA] russian scum [SEPA] with last pick [SEPA] wk

In [45]:
# save to parquet
x_train_lang_clean.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_train.parquet", index=False)

# evaluate impact 
impact = eval_step("non_english_drop", {"DOTA": PROJECT_ROOT / "data/processed_data/dota/x_train.parquet"}, impact)
impact

            step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
non_english_drop    DOTA 28679     0.718       0.8492        0.7533            0.698         -0.0045       -0.0023           -0.006

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,DOTA,28709,0.7204,0.8510,0.7544,0.7013,0.0000,0.0000,0.0000
1,non_latin_drop,DOTA,28692,0.7225,0.8518,0.7556,0.7040,0.0021,0.0012,0.0027
2,non_english_drop,DOTA,28679,0.7180,0.8492,0.7533,0.6980,-0.0045,-0.0023,-0.0060

In [46]:
# apply the same Latin-script language filter to the validation set for consistency
x_validation_en_lang = x_validation_en.copy()
x_validation_en_lang["lang_filter_status"] = x_validation_en_lang["message"].apply(latin_language_filter_status)

# inspect groups
print("Language filter status counts:")
print(x_validation_en_lang["lang_filter_status"].value_counts().head(30))


# check ambiguous cases
# these are messages where Lingua did not confidently choose a language
ambiguous_mask = x_validation_en_lang["lang_filter_status"].eq("keep_ambiguous")

print(f"\nAmbiguous Latin-script language documents kept: {ambiguous_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nAmbiguous documents kept for now:\n",
        x_validation_en_lang.loc[
            ambiguous_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among ambiguous rows:")
print(
    x_validation_en_lang.loc[ambiguous_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# check possible gaming / mixed-language false positives
# these are messages that Lingua might classify as non-English, but contain gaming/chat/English cues
mixed_mask = x_validation_en_lang["lang_filter_status"].eq("keep_possible_gaming_or_mixed")

print(f"\nPossible gaming or mixed-language documents kept: {mixed_mask.sum()}")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nPossible gaming/mixed documents kept for now:\n",
        x_validation_en_lang.loc[
            mixed_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print("\nLabel distribution among possible gaming/mixed rows:")
print(
    x_validation_en_lang.loc[mixed_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)


# drop only confident Latin-script non-English rows
drop_mask = x_validation_en_lang["lang_filter_status"].str.startswith("drop_latin_nonenglish")

with pd.option_context("display.max_rows", 300, "display.max_colwidth", 180):
    print(
        "\nConfident Latin-script non-English documents to drop:\n",
        x_validation_en_lang.loc[
            drop_mask,
            ["message", "label", "lang_filter_status"]
        ]
    )

print(f"\nHow many confident Latin-script non-English documents: {drop_mask.sum()}")


# label distribution sanity check
dropped_latin_nonenglish = x_validation_en_lang.loc[drop_mask]

print("\nLabel distribution before Latin non-English drop:")
print(x_validation_en["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after Latin non-English drop:")
print(
    x_validation_en_lang.loc[~drop_mask, "label"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nLabel distribution among dropped rows:")
print(
    dropped_latin_nonenglish["label"]
    .value_counts(normalize=True)
    .sort_index()
)


# create dataset after Latin non-English drop
# keep ambiguous and mixed/gaming rows
x_validation_lang_clean = (
    x_validation_en_lang
    .loc[~drop_mask]
    .drop(columns=["lang_filter_status"])
    .reset_index(drop=True)
)

print(f"\nRows before Latin non-English drop: {len(x_validation_en_lang)}")
print(f"Dropped {drop_mask.sum()} ({drop_mask.sum() / len(x_validation_en_lang):.1%})")
print(f"Rows after Latin non-English drop: {len(x_validation_lang_clean)}")
# save to parquet
x_validation_lang_clean.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_validation.parquet", index=False)

Language filter status counts:
lang_filter_status
keep_short                          6749
keep_possible_gaming_or_mixed        367
keep_ambiguous                        38
keep_english                          20
drop_latin_nonenglish_portuguese       2
drop_latin_nonenglish_tagalog          1
Name: count, dtype: int64

Ambiguous Latin-script language documents kept: 38

Ambiguous documents kept for now:
                                                                                                       message  \
292                                                   whole game [SEPA] 0 [SEPA] léti [SEPA] he thinsk he did
310                     zzz [SEPA] worst game ever had [SEPA] invoker gets away 1 hp [SEPA] ta get away 1 hit
845                                                       one [SEPA] lothar [SEPA] my mid [SEPA] arcane boots
935          below 3k mmr [SEPA] 'omg, he has invis' [SEPA] 'omg, I dunno where to ward, he roams ! [SEPA] XD
1116                                             Why [SEPA] ok [SEPA] reported [SEPA] feeding? [SEPA] or what
1258                                               AMAZING [SEPA] SO PRO [SEPA] commend wr pls [SEPA] idolaku
1710  wait [SEPA] 1 min [SEPA] ga bagay nasad [SEPA] wait lang jud [SEPA] please [SEPA] respect [SEPA] hahaha
1853            23 min [SEPA] qop no agha [SEPA] slark just got sb [SEPA] fun times as starving pos 6 support
2052                                                  HAHA LINA STILL ACT LIKE A PRO [SEPA] WTGF [SEPA] SO NC
2102                                                dive [SEPA] I got my ul [SEPA] jug [SEPA] dive [SEPA] jug
2264                                                      ggwp [SEPA] maiden jungla co midas [SEPA] best pick
2412                                            hahahaha [SEPA] fail dual [SEPA] :) [SEPA] sad [SEPA] poor LC
3122                                ff [SEPA] pls [SEPA] best supp ever [SEPA] no qward [SEPA] luna free farm
3261                                        recotnra  izi ese mid [SEPA] reporten sf pelase [SEPA] muy mierda
3453                                                       wait a bit? [SEPA] how its a bit [SEPA] like coin?
3690              rubic carry [SEPA] last pick [SEPA] olo [SEPA] kod of time [SEPA] kid [SEPA] of [SEPA] time
3699                   silencer [SEPA] motrher [SEPA] wjore [SEPA] whore [SEPA] nice gem [SEPA] son of a slut
3851                                                 how many tis navi won? [SEPA] how many tis eu teams won?
4068                                                   mga tsambahero [SEPA] heee [SEPA] mga tanga [SEPA] hoy
4176                                                      would have won by 5 mins [SEPA] if it werent for pl
4244                                                    go help am cm [SEPA] clinkz doesnt need any more help
4348                                                     come blood please [SEPA] haaha [SEPA] i need food :(
4609                                            DEF [SEPA] hahahaha [SEPA] lols [SEPA] aim me im just support
4650                                 void 25 mins 0 ulti dropped [SEPA] ggwp [SEPA] alche mid = invo freefarm
4754     ebaniy daun [SEPA] shas bi v 4k pati mmchike kontr pikat storma [SEPA] sin blyadi [SEPA] bedzmozgliy
5067                                                     qop [SEPA] please [SEPA] i thoiught wer were friends
5214                                                 OK; I'LL GO SMOKE, WE'LL ALL BE A MAN DOWN [SEPA] aight?
5232                            i cant change it [SEPA] my last 10 games i had like 4 feeders, dunno whats up
5387                                                     SEc please [SEPA] Srg  [SEPA] SUTRALIAN ITNERNET WOO
5440                                      Tipo [SEPA] daj ja 2 skill [SEPA] On bi ushel [SEPA] iz 2 sek stuna
5843                                               hahaha [SEPA] im only 1 there no one came :( [SEPA] hahaha
6056                                     ES [SEPA] JUST AFKING [SEPA] IN LANE [SEPA] FUCKED ME UP [SEPA] HARD
6124                                                play with me pudge [SEPA] ahahaha [SEPA] es sali ka sakin
6188                    see? [SEPA] slardar too pro [SEPA] he can 1v1 me [SEPA] waiting for someone to add me
6302                                          come on doom [SEPA] let me 1v1 him [SEPA] he had his fair aegis
6360                                      wew [SEPA] if we fail guys commend me ha [SEPA] if we fail [SEPA] ?
6380                                                maybe slark isnt useless [SEPA] maybe hes just a fuckhead
7007                                                   spectre from england but cant even talk english so sad

      label lang_filter_status
292       0     keep_ambiguous
310       0     keep_ambiguous
845       0     keep_ambiguous
935       0     keep_ambiguous
1116      0     keep_ambiguous
1258      0     keep_ambiguous
1710      2     keep_ambiguous
1853      0     keep_ambiguous
2052      0     keep_ambiguous
2102      0     keep_ambiguous
2264      0     keep_ambiguous
2412      1     keep_ambiguous
3122      0     keep_ambiguous
3261      3     keep_ambiguous
3453      0     keep_ambiguous
3690      0     keep_ambiguous
3699      1     keep_ambiguous
3851      0     keep_ambiguous
4068      0     keep_ambiguous
4176      0     keep_ambiguous
4244      0     keep_ambiguous
4348      0     keep_ambiguous
4609      0     keep_ambiguous
4650      3     keep_ambiguous
4754      0     keep_ambiguous
5067      0     keep_ambiguous
5214      0     keep_ambiguous
5232      0     keep_ambiguous
5387      0     keep_ambiguous
5440      0     keep_ambiguous
5843      0     keep_ambiguous
6056      1     keep_ambiguous
6124      0     keep_ambiguous
6188      0     keep_ambiguous
6302      0     keep_ambiguous
6360      0     keep_ambiguous
6380      1     keep_ambiguous
7007      0     keep_ambiguous

Label distribution among ambiguous rows:
label
0    0.815789
1    0.105263
2    0.026316
3    0.052632
Name: proportion, dtype: float64

Possible gaming or mixed-language documents kept: 367

Possible gaming/mixed documents kept for now:
                                                                                    message  \
17                      yeah fuck this random scum huskar [SEPA] report the fuck outta him
25      why try to edge people on [SEPA] are you that ignored by your parents [SEPA] o boi
31                                     pudge smoke in 1k mmr [SEPA] are you a fuckimg joke
64                    WORST ALCHEMIST BUILD IVE EVER SEEN [SEPA] report this alcehmist plz
79             no [SEPA] you got it [SEPA] why do you think i was half hp after that fight
...                                                                                    ...
7120                       am dat pussyh [SEPA] farm all game for that ? [SEPA] or russian
7123                                    fuck [SEPA] this [SEPA] fucking [SEPA] unity media
7126  jew [SEPA] im going after u [SEPA] riki [SEPA] ur dead when i get my fish chode on u
7129                         fucking complete shit cunts [SEPA] 338 mana fuck you silencer
7162                                2 core lanes [SEPA] lost like shit [SEPA] lal game rly

      label             lang_filter_status
17        1  keep_possible_gaming_or_mixed
25        0  keep_possible_gaming_or_mixed
31        1  keep_possible_gaming_or_mixed
64        1  keep_possible_gaming_or_mixed
79        0  keep_possible_gaming_or_mixed
...     ...                            ...
7120      1  keep_possible_gaming_or_mixed
7123      1  keep_possible_gaming_or_mixed
7126      1  keep_possible_gaming_or_mixed
7129      1  keep_possible_gaming_or_mixed
7162      1  keep_possible_gaming_or_mixed

[367 rows x 3 columns]

Label distribution among possible gaming/mixed rows:
label
0    0.427793
1    0.425068
2    0.070845
3    0.076294
Name: proportion, dtype: float64

Confident Latin-script non-English documents to drop:
                                                                                                                                                                                   message  \
2630  OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [SEPA] OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [SEPA] OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [SEPA] OSfrog LE BALANCED F...
3164                                                                                                                        reporta [SEPA] esse sf [SEPA] figueiredo [SEPA] filho da puta
4349                                                                                                                                reporta [SEPA] pro ibama [SEPA] fdp sacrifica animais

      label                lang_filter_status
2630      0     drop_latin_nonenglish_tagalog
3164      2  drop_latin_nonenglish_portuguese
4349      2  drop_latin_nonenglish_portuguese

How many confident Latin-script non-English documents: 3

Label distribution before Latin non-English drop:
label
0    0.741257
1    0.131253
2    0.064094
3    0.063397
Name: proportion, dtype: float64

Label distribution after Latin non-English drop:
label
0    0.741427
1    0.131307
2    0.063842
3    0.063423
Name: proportion, dtype: float64

Label distribution among dropped rows:
label
0    0.333333
2    0.666667
Name: proportion, dtype: float64

Rows before Latin non-English drop: 7177
Dropped 3 (0.0%)
Rows after Latin non-English drop: 7174

#### Duplicates

In [47]:
# look at dataset with duplicates 
x_train_dup = x_train_lang_clean[x_train_lang_clean.duplicated(subset="message", keep=False)].sort_values("message")
# look at some examples
x_train_dup.head(10)

      message  label
20785       !      0
18064       !      0
22928       !      0
25502       !      0
23352       !      0
6331        !      0
12366    !!!!      0
4446     !!!!      0
13881  #NAME?      0
1962   #NAME?      0

In [48]:
# top 100 duplicated messages
x_train_dup["message"].value_counts(ascending=False).head(100)

message
gg        1145
lol        559
?          346
ggwp       298
haha       277
          ...
why         14
yea         14
OMG         13
..          13
fuck u      13
Name: count, Length: 100, dtype: int64

In [49]:
# Look for duplicates with same messages but different labels
conflicts = x_train_lang_clean.groupby("message")["label"].nunique()
conflicts = conflicts[conflicts > 1]

conflict_rows = x_train_lang_clean[x_train_lang_clean["message"].isin(conflicts.index)].sort_values("message")

# Check how large is the proportion of conflicting duplicates
conflict_pct = len(conflict_rows) / len(x_train_lang_clean) * 100
print(f"Proportion of messages with conflicting labels: {conflict_pct:.2f}%")
print(f"Number of messages with conflicting labels: {len(conflict_rows)}")

Proportion of messages with conflicting labels: 10.99%
Number of messages with conflicting labels: 3153

In [50]:
# check conflicting rows
conflict_rows

      message  label
20812       )      0
16958       )      0
22886       )      0
11905       )      0
12214       )      0
...       ...    ...
1558       zz      0
21168      zz      0
7184       zz      2
13082      zz      0
7801       zz      0

[3153 rows x 2 columns]

Same as WoT - annotation noise. Dropping would lose training signal. Assign majority label instead.

In [51]:
# majority label for similar words
majority_label = x_train_lang_clean.groupby("message")["label"].agg(lambda x: x.value_counts().index[0])

# cap at 20 occurrences per message — preserves frequency, prevents extreme repeats dominating
MAX_PER_MESSAGE = 20
x_train_deduped = (
    x_train_lang_clean
    .assign(label=lambda df: df["message"].map(majority_label))
    .groupby("message", group_keys=False)
    .apply(lambda g: g.head(MAX_PER_MESSAGE))
    .reset_index(drop=True)
)

# check same ex duplicates
x_train_deduped[x_train_deduped["message"].isin(conflicts.index)][["message", "label"]].head(20)

    message  label
97        )      0
98        )      0
99        )      0
100       )      0
101       )      0
102       )      0
103       )      0
104       )      0
105       )      0
106       )      0
107       )      0
108       )      0
109       )      0
110       )      0
111       )      0
112       )      0
113       )      0
114       )      0
115       )      0
116       )      0

In [52]:
# check the change
print(f"Before dedup: {len(x_train_lang_clean)}")
print(f"After dedup: {len(x_train_deduped)}")
dropped = len(x_train_lang_clean) - len(x_train_deduped)
print(f"Dropped: {dropped} ({dropped / len(x_train_lang_clean):.1%})")

Before dedup: 28679
After dedup: 24116
Dropped: 4563 (15.9%)

In [53]:
# save again and evaluate
x_train_deduped.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_train.parquet", index=False)
impact = eval_step("duplicates_majority", {"DOTA": PROJECT_ROOT / "data/processed_data/dota/x_train.parquet"}, impact)
impact

               step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
duplicates_majority    DOTA 24116    0.7143       0.8353        0.7427           0.6986         -0.0037       -0.0106           0.0006

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,DOTA,28709,0.7204,0.8510,0.7544,0.7013,0.0000,0.0000,0.0000
1,non_latin_drop,DOTA,28692,0.7225,0.8518,0.7556,0.7040,0.0021,0.0012,0.0027
2,non_english_drop,DOTA,28679,0.7180,0.8492,0.7533,0.6980,-0.0045,-0.0023,-0.0060
3,duplicates_majority,DOTA,24116,0.7143,0.8353,0.7427,0.6986,-0.0037,-0.0106,0.0006

Cap at 20 applied same as WoT. Transform validation data the same way.

In [54]:
# transform validation data as well 
# majority label for similar words 
majority_label = x_validation_lang_clean.groupby("message")["label"].agg(lambda x: x.value_counts().index[0])

# drop duplicates and map majority label 
x_validation_deduped = x_validation_lang_clean.copy()
x_validation_deduped["label"] = x_validation_deduped["message"].map(majority_label)

# save again
x_validation_deduped.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_validation.parquet", index=False)

#### Data Artifacts

In [55]:
# artifact cleaning for Dota — input: x_train_deduped (after language filter and dedup)
x_train_clean = x_train_deduped.copy()

# convert messages to string and fill missing values
x_train_clean["message"] = x_train_clean["message"].fillna("").astype(str)

# strip [SEPA] conversation separator — data collection artifact, no linguistic value
x_train_clean["message"] = x_train_clean["message"].str.replace(r"\s*\[SEPA\]\s*", " ", regex=True).str.strip()
print(f"[SEPA] remaining after strip: {x_train_clean['message'].str.contains(r'[SEPA]', regex=False).sum()}")

# generic artifact patterns
URL_RE          = re.compile(r"https?://\S+|www\.\S+", flags=re.IGNORECASE)
HTML_ENTITY_RE  = re.compile(r"&[a-zA-Z]+;|&#\d+;|&#x[0-9a-fA-F]+;")
KEYBOARD_MASH_RE = re.compile(r"\S{20,}")


def artifact_status(text):
    text = str(text)
    if URL_RE.search(text):
        return "drop_url"
    if HTML_ENTITY_RE.search(text):
        return "drop_html_entity"
    if KEYBOARD_MASH_RE.search(text):
        return "drop_keyboard_mash"
    return "keep"


# apply artifact detection
x_train_clean["artifact_status"] = x_train_clean["message"].apply(artifact_status)

print("Artifact status counts:")
print(x_train_clean["artifact_status"].value_counts())

# rows to drop
artifact_mask = x_train_clean["artifact_status"].ne("keep")

# inspect dropped artifacts
with pd.option_context("display.max_rows", 50, "display.max_colwidth", 120):
    print("\nArtifact rows to drop:")
    print(x_train_clean.loc[artifact_mask, ["message", "label", "artifact_status"]])

# label distribution sanity check
print("\nLabel distribution before artifact drop:")
print(x_train_deduped["label"].value_counts(normalize=True).sort_index())

print("\nLabel distribution after artifact drop:")
print(x_train_clean.loc[~artifact_mask, "label"].value_counts(normalize=True).sort_index())

# create artifact-cleaned dataset
x_train_artifact_clean = (
    x_train_clean
    .loc[~artifact_mask]
    .drop(columns=["artifact_status"])
    .reset_index(drop=True)
)

print(f"\nRows before artifact drop: {len(x_train_deduped)}")
print(f"Dropped {artifact_mask.sum()} ({artifact_mask.sum() / len(x_train_deduped):.1%})")
print(f"Rows after artifact drop: {len(x_train_artifact_clean)}")

[SEPA] remaining after strip: 0
Artifact status counts:
artifact_status
keep                  24029
drop_keyboard_mash       80
drop_url                  7
Name: count, dtype: int64

Artifact rows to drop:
                                                                                                                       message  \
14                  !!!!!!!!!!!!!!!!!!!!!!!!!!!!! our PA is dead man we won't do stuff and things that would require a dead WK
39                                                                                                       #concernedstudent1950
161                                                                                                       ))))))))))))))))))))
162                                                                   )))))))))))))))))))))))))))))) hello, gays, how are you?
163                                                                                                  ))))))))))000000000000000
...                                                                                                                        ...
23014                                                                                         www.leagueoflegends.com/register
23015  www.leagueoflegends.com/register www.leagueoflegends.com/register www.leagueoflegends.com/register www.leagueoflegen...
23094                                                                                  xddddddddddddddddddddddddd ahgahahahaha
23543  yessssssssssssssssss do it i mena invo won ur game looool why not look pa late game look invo late game we 9 here kn...
23961                                                                                zzzzzzzzzzzzzzzzzzzz welcome to 2hr dota2

       label     artifact_status
14         0  drop_keyboard_mash
39         0  drop_keyboard_mash
161        0  drop_keyboard_mash
162        1  drop_keyboard_mash
163        0  drop_keyboard_mash
...      ...                 ...
23014      0            drop_url
23015      0            drop_url
23094      0  drop_keyboard_mash
23543      0  drop_keyboard_mash
23961      0  drop_keyboard_mash

[87 rows x 3 columns]

Label distribution before artifact drop:
label
0    0.708078
1    0.155291
2    0.073810
3    0.062821
Name: proportion, dtype: float64

Label distribution after artifact drop:
label
0    0.707770
1    0.155396
2    0.074036
3    0.062799
Name: proportion, dtype: float64

Rows before artifact drop: 24116
Dropped 87 (0.4%)
Rows after artifact drop: 24029

In [56]:
# save and evaluate
x_train_artifact_clean.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_train.parquet", index=False)
impact = eval_step("artifact_drop", {"DOTA": PROJECT_ROOT / "data/processed_data/dota/x_train.parquet"}, impact)
impact

         step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
artifact_drop    DOTA 24029    0.7301       0.8493        0.7457             0.72          0.0158         0.003           0.0214

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,DOTA,28709,0.7204,0.8510,0.7544,0.7013,0.0000,0.0000,0.0000
1,non_latin_drop,DOTA,28692,0.7225,0.8518,0.7556,0.7040,0.0021,0.0012,0.0027
2,non_english_drop,DOTA,28679,0.7180,0.8492,0.7533,0.6980,-0.0045,-0.0023,-0.0060
3,duplicates_majority,DOTA,24116,0.7143,0.8353,0.7427,0.6986,-0.0037,-0.0106,0.0006
4,artifact_drop,DOTA,24029,0.7301,0.8493,0.7457,0.7200,0.0158,0.0030,0.0214

In [57]:
# apply same artifact cleaning to validation — same functions, no train info used
x_validation_clean = x_validation_deduped.copy()
x_validation_clean["message"] = x_validation_clean["message"].fillna("").astype(str)

# strip [SEPA]
x_validation_clean["message"] = x_validation_clean["message"].str.replace(r"\s*\[SEPA\]\s*", " ", regex=True).str.strip()

x_validation_clean["artifact_status"] = x_validation_clean["message"].apply(artifact_status)
artifact_mask_val = x_validation_clean["artifact_status"].ne("keep")

print(f"Val artifact rows to drop: {artifact_mask_val.sum()}")

x_validation_artifact_clean = (
    x_validation_clean
    .loc[~artifact_mask_val]
    .drop(columns=["artifact_status"])
    .reset_index(drop=True)
)

print(f"Val rows after artifact drop: {len(x_validation_artifact_clean)}")

Val artifact rows to drop: 17
Val rows after artifact drop: 7157

#### Mislabeled data

In [58]:
# few top rows of the data
x_train_artifact_clean.head(10)

                                       message  label
0                                         = =?      0
1  THAT LAST PICK SPEC'' LIKE U KNOW SHIT ROFL      1
2                                            !      0
3                                            !      0
4                                            !      0
5                                            !      0
6                                            !      0
7                                            !      0
8                                ! min more Rc      2
9                                           !!      0

In [59]:
# class distribution check
print("Label distribution after cleaning:")
print(x_train_artifact_clean["label"].value_counts(normalize=True).sort_index())
print(x_train_artifact_clean["label"].value_counts(normalize=False).sort_index())

Label distribution after cleaning:
label
0    0.707770
1    0.155396
2    0.074036
3    0.062799
Name: proportion, dtype: float64
label
0    17007
1     3734
2     1779
3     1509
Name: count, dtype: int64

We might have mislabeled toxicity data that was classified as non-toxic or opposite. We need to detect and fix that as well.

In [60]:
from cleanlab.filter import find_label_issues
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_predict, StratifiedKFold
import numpy as np

# exclude messages under 3 chars — no signal, cleanlab guesses randomly on them
cl_mask = x_train_artifact_clean["message"].str.len() >= 3
cl_df = x_train_artifact_clean[cl_mask].reset_index(drop=True)

X = cl_df["message"].values
y = cl_df["label"].astype(int).values

# stratified cv with shuffle — avoids ordering bias in folds
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=7524)

# lightweight pipeline to generate calibrated out-of-fold probabilities
# class_weight="balanced" — needed with imbalanced data so minority class errors are detected
# LR required (not SVC) — cleanlab needs predict_proba, not decision_function
pipe = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_df=0.95,
                              sublinear_tf=True, norm="l2",
                              analyzer="word", tokenizer=tokenize, token_pattern=None)),
    ("clf", LogisticRegression(max_iter=2000, random_state=7524, class_weight="balanced")),
])

# each sample predicted by model that never saw it during training
oof_probs = cross_val_predict(pipe, X, y, cv=cv, method="predict_proba", n_jobs=-1)

# normalized_margin more robust than self_confidence on imbalanced data —
# only flags rows where model is confident another class is correct, not just uncertain
issue_idx = find_label_issues(
    labels=y,
    pred_probs=oof_probs,
    return_indices_ranked_by="normalized_margin",
)

predicted = oof_probs[issue_idx].argmax(axis=1)
given = y[issue_idx]

# all classes can be added
boundary_mask = (
    ((given == 0) & np.isin(predicted, [1, 2, 3]))
    | (np.isin(given, [1, 2, 3]) & (predicted == 0))
)
issue_idx = issue_idx[boundary_mask]

print(f"Suspected mislabeled: {len(issue_idx)} ({len(issue_idx)/len(y):.1%})")

# inspect top 50 — compare original label vs what model predicted
print(cl_df.iloc[issue_idx[:50]][["message", "label"]].assign(
    predicted=oof_probs[issue_idx[:50]].argmax(axis=1)
))

# map issue positions in cl_df back to x_train_artifact_clean original index
original_idx = x_train_artifact_clean[cl_mask].index[issue_idx]

Suspected mislabeled: 1723 (7.6%)
                                                 message  label  predicted
3626                                               NOOB!      0          1
12491                                            im noob      0          1
1881                                                 EZ)      0          3
8528                                                 ez&      0          3
1896                                                 EZ^      0          3
15674                                            oh shit      0          1
5543                                alive? what the fuck      0          1
4793                             WP GG fuck rustards LOL      0          1
2297                                        GG fuck this      0          1
2077                                               FUCK!      0          1
13132                                just what the fuck?      0          1
5796                            and you can fuck off too      0          1
20411                                we dont give a fuck      0          1
2262                                   GG FUCK THIS GAME      0          1
8964                                            fuck lag      0          1
3085                                     Intense as fuck      0          1
15724                                       oh what fuck      0          1
3304                                            LOL FUCK      0          1
10942         has predicted their team will win! oh fuck      0          1
21095              why the fuck you lion you always lion      0          1
18921                                the fucking keybord      0          1
4173                              SHUT UP FUCKING NOOB !      0          1
15831                                     okay fuck shit      0          1
2135                                   Fuck fucking zeus      0          1
9493                                      gg ez ez blat'      0          3
8354                                       ez hook ez ff      0          3
9120                                   fuck your english      0          1
8368                                     ez kill ez life      0          3
4607                                         Very stupid      0          1
12346  if everyone just fucking calms the fuck down a...      0          1
16972                                 report my team pls      0          2
12656               invoker what the fuck are u playing?      0          1
21345                    wow really? we wait for TA fuck      0          1
12828                     its not good game fuck you all      0          1
3954                                   REPORT BARAT GGWP      0          2
14399                               mirana please report      0          2
21076                                        why report?      0          2
12451              im confsued now, who should i report?      0          2
1053             =)) ez mid next time pick veng not alch      0          3
2921   I WILL ALWAYS SUCK HIS DICK AS LONG AS BARA WA...      0          1
6878                         come on man fuck you rubick      0          1
4779        WOW ss youre shit dont know how you lost mid      0          1
11387                                           hey FUCK      0          1
13387                           lc thejm pls sladar noob      0          1
1684                                     DONT BE MAD KID      0          3
2773                       HOLY SHIT HOW CAN DOOM SO BAD      0          1
8732    finally its over the suffering fucking gook team      0          1
6189                                        bg noob team      0          1
8196                                               ez WR      0          3
19783  u realize u are so fucking braindamaged when t...      0          1

In [61]:
# drop suspected mislabeled — safer than relabeling with own OOF predictions
# cleanlab paper recommends pruning over relabeling to avoid feedback loop
x_train_artifact_clean1 = x_train_artifact_clean.drop(index=original_idx).reset_index(drop=True)
print(f"Dropped {len(original_idx)} suspected mislabeled rows ({len(original_idx)/len(x_train_artifact_clean):.1%})")

Dropped 1723 suspected mislabeled rows (7.2%)

In [62]:
# save again and evaluate 
x_train_artifact_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_train.parquet", index=False)
impact = eval_step("cleanlab_relabeling", {"DOTA": PROJECT_ROOT / "data/processed_data/dota/x_train.parquet"}, impact)
impact

               step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
cleanlab_relabeling    DOTA 22306    0.8273       0.9161        0.8263            0.832          0.0972        0.0806            0.112

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,DOTA,28709,0.7204,0.8510,0.7544,0.7013,0.0000,0.0000,0.0000
1,non_latin_drop,DOTA,28692,0.7225,0.8518,0.7556,0.7040,0.0021,0.0012,0.0027
2,non_english_drop,DOTA,28679,0.7180,0.8492,0.7533,0.6980,-0.0045,-0.0023,-0.0060
3,duplicates_majority,DOTA,24116,0.7143,0.8353,0.7427,0.6986,-0.0037,-0.0106,0.0006
4,artifact_drop,DOTA,24029,0.7301,0.8493,0.7457,0.7200,0.0158,0.0030,0.0214
5,cleanlab_relabeling,DOTA,22306,0.8273,0.9161,0.8263,0.8320,0.0972,0.0806,0.1120

Gains could be inflated if the model memorizes its own training signal.
Verify with LinearSVC as an independent second model.

In [63]:
from sklearn.svm import LinearSVC
# impact 
impact = eval_step("cleanlab_relabeling_svc", {"DOTA": PROJECT_ROOT / "data/processed_data/dota/x_train.parquet"}, impact, 
                                  clf=LinearSVC(max_iter=2000, random_state=7524, 
                                                class_weight = "balanced"))
impact

                   step dataset  rows  f1_macro  f1_weighted  recall_macro  precision_macro  f1_macro_delta  recall_delta  precision_delta
cleanlab_relabeling_svc    DOTA 22306    0.8477       0.9286         0.824           0.8785          0.0204       -0.0023           0.0465

,step,dataset,rows,f1_macro,f1_weighted,recall_macro,precision_macro,f1_macro_delta,recall_delta,precision_delta
0,baseline,DOTA,28709,0.7204,0.8510,0.7544,0.7013,0.0000,0.0000,0.0000
1,non_latin_drop,DOTA,28692,0.7225,0.8518,0.7556,0.7040,0.0021,0.0012,0.0027
2,non_english_drop,DOTA,28679,0.7180,0.8492,0.7533,0.6980,-0.0045,-0.0023,-0.0060
3,duplicates_majority,DOTA,24116,0.7143,0.8353,0.7427,0.6986,-0.0037,-0.0106,0.0006
4,artifact_drop,DOTA,24029,0.7301,0.8493,0.7457,0.7200,0.0158,0.0030,0.0214
5,cleanlab_relabeling,DOTA,22306,0.8273,0.9161,0.8263,0.8320,0.0972,0.0806,0.1120
6,cleanlab_relabeling_svc,DOTA,22306,0.8477,0.9286,0.8240,0.8785,0.0204,-0.0023,0.0465

Score gains hold under both LR and LinearSVC. The cleaning is real — label corrections reflect genuine annotation noise, not model self-confirmation.

In [64]:
# fit on full train
pipe.fit(x_train_artifact_clean1["message"], x_train_artifact_clean1["label"])
val_probs = pipe.predict_proba(x_validation_artifact_clean["message"])

# find suspicious val labels — no circularity, model never saw val
val_issues = find_label_issues(
    labels=x_validation_artifact_clean["label"].astype(int).values,
    pred_probs=val_probs,
    return_indices_ranked_by="normalized_margin"
)

val_predicted = val_probs[val_issues].argmax(axis=1)
val_given = x_validation_artifact_clean["label"].astype(int).values[val_issues]

boundary_mask = (
    ((val_given == 0) & np.isin(val_predicted, [1, 2, 3]))
    | (np.isin(val_given, [1, 2, 3]) & (val_predicted == 0))
)
val_issues_filtered = val_issues[boundary_mask]

print(f"Suspected val mislabeled: {len(val_issues_filtered)} ({len(val_issues_filtered)/len(x_validation_artifact_clean):.1%})")

# inspect top 50
print(x_validation_artifact_clean.iloc[val_issues_filtered[:50]][["message", "label"]].assign(
    predicted=val_probs[val_issues_filtered[:50]].argmax(axis=1)
))

Suspected val mislabeled: 529 (7.4%)
                                                message  label  predicted
6904                                      fuck off zeus      0          1
5135                                      WHAT THE FUCK      0          1
3285                                       spectre noob      0          1
3374                       see that shit is just spooky      0          1
1102                                        LOL fucking      0          1
6926                          good game fuck that pudge      0          1
3515                            no wp alche WP? fuck no      0          1
6139                                       so long fuck      0          1
6729                           Very well fucking played      0          1
499        has nuthing to do with how shit tiny is lmao      0          1
2001                                           gg w[ ez      0          3
4202                                    fuck im lagging      0          1
6431                                                G G      0          2
1470                                            LOL G)G      0          2
1289  pls just report them so that you dont get them...      0          2
6688                           talk to much shit you do      0          1
1580     no yalll mid yalll noob y didnt u go help tiny      0          1
411                                   gg wp noob sf too      0          1
4584                                      why u mad kid      0          3
3243                                               Stfu      0          1
2709                     didn't like my cow joke? fuck.      0          1
6105                                 i kill you so easy      0          3
1721                           gl hf YF[EZ CGHFIBDFTNCZ      0          3
141                                             easy gg      0          3
553                                           easy sven      0          3
3156                                      easy farmlane      0          3
6457                                            so easy      0          3
635                                                Easy      0          3
1078                                 ez jungle you mean      0          3
2501          are you stupid troll?waiting for nothing?      0          1
5424                                             .... 0      0          3
5418                                                 0%      0          3
811                                             0,( =,(      0          3
6716                                             0 here      0          3
6155                                   just 2 noobs top      0          1
6754                                 ? i am not russian      0          1
1710                                         END PLEASE      2          0
5243                                            end afk      2          0
6990                          free mmr fuck that 37 mmr      0          1
2618                        talk when not done noob mid      0          1
5810                                           your mom      0          1
5879                                           your mom      0          1
5368                           counterpicker get fucked      0          1
1330                                           g voltis      0          2
3195                                                mad      0          3
776                                         so you mad?      0          3
3574                                              ? mad      0          3
5575                                            ? mad ?      0          3
4850                                     dont be mad ns      0          3
4092                   holy shit they r not coming back      0          1

## Validation Label Quality — Inspection Only

Cleanlab estimated ~6.7% annotation noise in the validation set using a model trained
on cleaned training data. Clear annotation errors exist: "bot", "idiots", "moron"
labeled as non-toxic (class 0) are genuine annotator mistakes.

**Why val labels are left unchanged:**

Dropping or relabeling val rows based on a train-fitted model is circular — the model
decides what to remove from its own test set, then gets evaluated on the cleaner result.
This inflates metrics without reflecting real improvement.

Val metrics are slightly pessimistic due to annotation noise. This is the honest
evaluation of model performance on real-world noisy data.

#### Final verification

In [65]:
# basic data checks for train and validation sets after cleaning and relabeling
print("Final training set shape:", x_train_artifact_clean1.shape)
print("Final validation set shape:", x_validation_artifact_clean.shape)
print("\nFinal training set label distribution:")
print(x_train_artifact_clean1["label"].value_counts(normalize=True).sort_index())
print("\nFinal validation set label distribution:")
print(x_validation_artifact_clean["label"].value_counts(normalize=True).sort_index())

Final training set shape: (22306, 2)
Final validation set shape: (7157, 2)

Final training set label distribution:
label
0    0.716713
1    0.157715
2    0.066260
3    0.059311
Name: proportion, dtype: float64

Final validation set label distribution:
label
0    0.740673
1    0.131340
2    0.064832
3    0.063155
Name: proportion, dtype: float64

In [66]:
# save to parquet for easier loading in future steps
# train
x_train_artifact_clean1.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_train.parquet", index=False)
# validation
x_validation_artifact_clean.to_parquet(PROJECT_ROOT / "data/processed_data/dota/x_validation.parquet", index=False)

In [67]:
# save preprocessing ablation results
impact.to_csv(PROJECT_ROOT / "data/results/cleaning_ablation_dota.csv", index=False)
print("Saved Dota cleaning ablation CSV")

Saved Dota cleaning ablation CSV