# Gaming Toxicity Detection

**Authors:** Beibarys Nyussupov, Ruby Ngo, Paola Calle, Jett Forward

In [1]:
# libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path 
import re 

# reproducibility
seed = 7524
np.random.seed(seed)

# project root (notebooks/gaming/ - notebooks/ - project root)
PROJECT_ROOT = Path().resolve().parent.parent

In [2]:
# data directories
DATA_DIR_WOT  = PROJECT_ROOT / "data/raw_data/world_of_tanks/"
DATA_DIR_DOTA = PROJECT_ROOT / "data/raw_data/dota/"

## World of Tanks

**World of Tanks**
| Class | Terminology |
|---|---|
| 0 | Non-Toxic |
| 1 | Insults and Flaming |
| 2 | Other Offensive Texts |
| 3 | Hate and Harassment |
| 4 | Threats |
| 5 | Extremism |

#### Inspect each split

In [3]:
# import data 
train = pd.read_csv(DATA_DIR_WOT / "train.csv")
val = pd.read_csv(DATA_DIR_WOT / "val.csv")

# test dataset 
test_text = pd.read_csv(DATA_DIR_WOT /  "test_index_text.csv")
test_label = pd.read_csv(DATA_DIR_WOT / "test_index_label.csv")

# check the data 
for name, df in [("train", train), ("val", val), ("test_text", test_text), ("test_label", test_label)]:
    print(f"--- {name} ---")
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print(f"First few rows of the dataset:\n{df.head(3)}")
    print()

--- train ---
Shape: (42959, 3)
Columns: ['index', 'message', 'label']
First few rows of the dataset:
   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0

--- val ---
Shape: (5367, 3)
Columns: ['index', 'message', 'label']
First few rows of the dataset:
   index       message  label
0  31697  e50 is there    0.0
1  52311   this scouts    0.0
2   2775       i guess    0.0

--- test_text ---
Shape: (5375, 2)
Columns: ['index', 'message']
First few rows of the dataset:
   index         message
0  17775  aim you monkey
1  28228   Pz kill artys
2  19888             ggs

--- test_label ---
Shape: (5375, 2)
Columns: ['index', 'label']
First few rows of the dataset:
   index  label
0  17775    2.0
1  28228    0.0
2  19888    0.0

The test set is stored in two separate files - text and labels indexed by the same `index` column. Train and val are already complete. We need to join the test files on `index` before merging everything.

#### Reconstruct test split and merge all

In [4]:
# merge test text and labels
test = test_text.merge(test_label, on="index", how="inner")

# concatenate all data
wot = pd.concat([train, val, test], ignore_index=True)

print(f"Test join shape: {test.shape}\n")
print(f"Merged shape: {wot.shape}\n")
print(f"First few rows of the data:\n{wot.head(3)}\n")
print(f"Information about the data: {wot.info()}")

Test join shape: (5375, 3)

Merged shape: (53701, 3)

First few rows of the data:
   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53701 entries, 0 to 53700
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    53701 non-null  int64
 1   message  53701 non-null  object
 2   label    53701 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ MB
Information about the data: None

The test join uses `inner` - any index present in only one file would be silently dropped. If test shape after join is smaller than either file's length, there is an alignment issue in the original data.

#### Non-english language

Since we are going to model classifier on english data, it is important for us to detect non-english cases as many as we can.

In [5]:
# detecting Non-lating language first

# covers Cyrillic, CJK, Arabic, Hebrew, Thai, etc.
NON_LATIN_SCRIPT = re.compile(
    r"[\u0400-\u04FF"   # Cyrillic
    r"\u4E00-\u9FFF"    # CJK
    r"\u0600-\u06FF"    # Arabic
    r"\u0590-\u05FF"    # Hebrew
    r"\u3040-\u30FF"    # Japanese
    r"\u0E00-\u0E7F]"   # Thai
)

# function to detect non-lantin language 
def is_non_latin_script(text):
    # flag if >20% chars are non-Latin script
    chars = [c for c in str(text) if not c.isspace()]
    hits = sum(1 for c in chars if NON_LATIN_SCRIPT.match(c))
    return len(chars) > 0 and hits / len(chars) > 0.2

# non english wot 
print(f"Non-english documents:\n{wot[wot["message"].apply(is_non_latin_script)].reset_index(drop=True)}\n")
# drop such cases 
# length before drop 
before = len(wot)
wot_en = wot[~wot["message"].apply(is_non_latin_script)].reset_index(drop=True)
print(f"Dropped {before - len(wot_en)} ({(before-len(wot_en))/before:.1%})")
print(f"Rows after the drop: {wot_en.shape[0]}")

Non-english documents:
      index                message  label
0     13087          ще злийте )))    1.0
1     31917       перший бій, сток    0.0
2     40395                ФОКУСЯТ    0.0
3     54412  елка спасибо тебе ...    0.0
4      5457                 уроди!    0.0
...     ...                    ...    ...
3732   5453                 я кину    0.0
3733   5456                светите    0.0
3734  13081       в чём притензия?    0.0
3735   7331      вот и подкруточки    0.0
3736  50128  тут танки стоят уебак    0.0

[3737 rows x 3 columns]

Dropped 3737 (7.0%)
Rows after the drop: 49964

In [7]:
from lingua import Language, LanguageDetectorBuilder

# detector to find latin but non-english documents 
detector = (LanguageDetectorBuilder 
    # detect all other languages using latin
    .from_all_languages_with_latin_script()
    # if top-2 languages are within 25% confidence of each other - do not drop 
    .with_minimum_relative_distance(0.25)
    .build())

# function to detect such documents 
def is_latin_non_english(text):
    if len(str(text).strip()) < 30:
        return False  # too short - keep
    lang = detector.detect_language_of(str(text))
    return lang is not None and lang != Language.ENGLISH

# such documents 
mask = wot_en["message"].apply(is_latin_non_english)
with pd.option_context("display.max_rows", 800):
    print(f"Non-english documents:\n{wot_en[mask]}\n")
    print(f"How many documents with non-english text:{wot_en[mask].shape[0]}")

Non-english documents:
       index                                            message  label
364    14038                    Menj már nemm kapsz spotot.....    0.0
494    29761          no ayudaste a nadie shptk ahora no llores    1.0
573     7353                  3 dingi od pierdolonych papier??w    2.0
683    35518                Etwas Hilfe bei D4 wäre schon nett!    0.0
779     6397        Hilfe! Ich werde gleich auf A3 verpr??gelt!    0.0
908     6395        Hilfe! Ich werde gleich auf C1 verpr??gelt!    0.0
958     1934  jeszcze t54 zespotowany byl wczesniej wiec wid...    0.0
1110    7645                     how many dmg arty? 2k? XDDDDDD    0.0
1111   51836                   LOSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS    0.0
1185    1984                   5x ep... mehr muss man net sagen    0.0
1374    6449  Hali! A MAATT kl??n akt??v j??t??kosokat keres...    0.0
1426   30904                  ooo polaczek, no jakby inaczej XD    0.0
1528    5943  tu ecris ce que tu veux, dans la mesure du cor...    0.0
1696   26683  Den Sinn von Funk erkannt, aber kein TS? Nutz ...    0.0
2003   33391  ich checkls nicht seit wann lässst man diese s...    3.0
2033   44040                Kann mir wer bei C2 zur Hand gehen!    0.0
2121    3989     amikor arrol e helyr??l m??r el is mozdultam..    0.0
3073   51396  Aufgeklärt bei Position E3. Etwas Hilfe währe ...    0.0
3202   21011  aahahhahahahsahahsahsyhsahnahsedbnfsdsbnfsfssh...    0.0
3384   24140            sry ulozim si replay a mozme pokracovat    0.0
3653   31989  Danke Type das ich deinen Job gemacht habe... ...    1.0
3708   49558  no wlasnie stojac za mna gdzie ja trzymalem po...    0.0
3713   44045                  Du siehst mich, Ich seh Dich! F2!    0.0
3792   32334                     HAHAHAAAAAA:::NEXT KINDER TEAM    1.0
4022   51394  Aufgeklärt bei Position D3. Etwas Hilfe währe ...    0.0
4065    2261  Les fr??res d'armes [L_F_A] recrutent.Clan fra...    0.0
4192   51835  FASZYSTOWSKIE ŚWINIE WOTOWSKA WAGNEROWSKA BAND...    5.0
4955   33305                     ihr seid so schlecht ihr wixxa    1.0
5083   11094  meine sch??sse prallen ab und ich platze nach ...    0.0
5108   47390                Etwas Hilfe bei E7 wäre schon nett!    0.0
5184   10263   tylko is-3a jest dobry reszta to jebane ??cierwo    1.0
5448   27984                    ich schmeiß dir die Brügel raus    1.0
5459   47483  3k damage für die katz weil unser team verkack...    2.0
5697   17614  shut up froschschenkelfresser oder laber in en...    1.0
6033    9386   gggggggggggggggggggggggggggggggggggggggggggggggg    0.0
6094   14709   szerinted rosszabb lesz ez mint a tog vagy jobb?    0.0
6237   13269  Wir die Grizzly's suchen noch aktive deutsche ...    0.0
6459   54201  FFFFFFFFFFFFUUUUUUUUUCKING ARTYYYYYYYYYYYYYYYY...    1.0
6563   46888               progetto are you ******* ***********    0.0
6607   52151  und die 6 camper kraulen sich wie immer die ei...    1.0
6735   50811          össze vissza vagyok borúlva tess sgítssss    0.0
6750   35299                Etwas Hilfe bei H5 wäre schon nett!    0.0
6857   13862  protože jsem dostával do neviditelnýho gsoru a...    0.0
6949    1985                    bananen gibts nur f??r nen sieg    3.0
6962   30955                 nie pisz do mnie po rusku ty kurwo    3.0
7016   48113  scheiss camper idioten löscht das game und geh...    1.0
7044    2530      nigerians are anglaise colonie...non francais    0.0
7168   10262                 a my kurwa takie boty mamy ze szok    2.0
7252   30166  Die Puma Community ist nun soweit auch den 2. ...    0.0
7302   33481            report chojowi smacie na warapcku is wg    1.0
7853   24719  nevím jak můžete hrát tuto hru tak pojebaně vy...    1.0
7871   38487                  e 100 wycofaj bo mi kamo ściągasz    0.0
7925   35519                Etwas Hilfe bei E3 wäre schon nett!    0.0
8168    1662  waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...    0.0
8305   26049  stul pysk, durniu, naotwartej mapie wystawiasz...    1.0
8451   18360  Szukasz klanu ? Zapraszamy do -AP- Po więcej i...    0.0
8462   33078       Viel Glück an alle! (Good luck to everyone!)    0.0
8626   39783                  bewegt euch doch mal ein bisschen    0.0
8630    6011                    Lippu haltuun k??mpp??ys loppuu    0.0
8789   32266   Kann es sein das ich Dumm bin oder so, bin offen    1.0
8818   14361  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...    0.0
9051   51745                   od mojej strony jedzie kv4 uwaga    0.0
9363   27972  twoja stara ma parkinsona e tak sie bujasz tym...    1.0
9666   33524  nur wixxer in die dreck können und nicht aufra...    0.0
9692   11782  ach, zdalne... pamiętam zdalną sesję na uczeln...    0.0
9774   52848  mindenre alkalmatlan volt az angolok ingyen ad...    0.0
10083  49554                popłacz tam sie kurwa jeszcze hahaa    2.0
10141  43747  mit so einem Team geht man auch gerne durch di...    2.0
10871  34731            WWWWWWWWWDWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    0.0
10874  41748                  una scimmia mi ha spottato in D7!    0.0
10958  51731  deszcze nie spokojne potargaly sad a ja musze ...    0.0
11355  39375      ez game ez win T95 bedzie jechało pyr pyr pyr    0.0
11964  10515  leckt mich doch am ar... nutzt irgendwer die k...    0.0
12177  44031                  Du siehst mich, Ich seh Dich! D2!    0.0
12452  35005  zawsze w lato pod dyskoteką ze straganem stoi pan    0.0
12494  44041                Kann mir wer bei C2 zur Hand gehen!    0.0
12732  35520                Etwas Hilfe bei F3 wäre schon nett!    0.0
12890  17615  jawohl herr hauptman , eat wurst and kartofeln...    3.0
12920  47391                Etwas Hilfe bei F7 wäre schon nett!    0.0
12968  32888                 JOO TÄMÄ KÄÄNTYY JÄRKEVÄN NOPEASTI    0.0
13255  53297                    tol je tak složitý použít mozek    1.0
13459  31829  ich liebe es wie wot einen nur noch verarscht ...    1.0
13542   3357  man muss hier nur ein Jude, Kommunist, Slave, ...    3.0
13735  18631  hp vida solo no tenian que dejarlo pasar inutiles    0.0
13873  49550  no nie twoja bo ja chujowo podjechalem ale poz...    0.0
14122  49557  ja pierdole jak sa tacy gracze jak ty to sredn...    1.0
14563  11788      obecnie piszę pracę dyplomową, w lutym obrona    0.0
14714  51824    bedziesz kurwa morde zacieszal za 2 godziny max    0.0
15165  12179  usta ben 60tp kasıyorum 8 seviyedeyim 9u alınc...    1.0
15229   8115                  Du siehst mich, Ich seh Dich! E3!    0.0
15264  45286  Du reportest die Gegner ungerne alleine oder f...    0.0
15334  49542  ten jeo kolega gra lepiej od Ciebie i nie wpie...    0.0
15581  21946        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa    0.0
15825  37767  bráško gratuluju... menší throw teď ke konci.....    0.0
15968  51891  meinst du jetzt chess algeimein oder den clan ...    0.0
16144  18552                kurwa chuje nie gioncie jak wszmaty    1.0
16434  54627  Szia! Épp streamelek twitchen,ugorj be, örömme...    0.0
16603   7732                   ten ji-ro to jaki?? nowy czo??g?    0.0
16635  49545  a nie moja wina ze mnie pchasz zeby w arte trs...    0.0
17048  27800  nyomornc rtetkes kurva anyátok remélem már meg...    1.0
17050  20645                 skąd masz taki zajebisty rower co?    0.0
17257   4091  abi 10 el oynad??m bu kadar ??erefsiz bir oyun...    0.0
17462  12290           kolejna lanie ale to normalka w wocie :)    0.0
17644  33462  nee, wird ja immer schlimmer mit den Luschen d...    1.0
17723  13088                NAHUI POSHLA HUESOSKA BLEA IOBANAEA    2.0
17758   6536                     i kurwa nastepne zjebane cioty    0.0
17761   1943         JA BYM ICH POZABIJAL ALE SAM NIC NIEZROBIE    0.0
18023  30916                   dobra, dziękuję ci za rady XDDDD    0.0
18271  20915         HHHHHHHHHHHHEEEEEEEEEEEEEEEYYYYYYYYYYYYYYY    0.0
19121  20641        dzieki takim debilom przegrywa cala druzyna    1.0
19193   6450  aaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww...    0.0
19231  27962                  zamknij morde jebany rski smieciu    1.0
19256  38953  die wünsche ich dir auch, dann hörst vielleich...    0.0
19304  49549             popłacz sie najlepiej i idz do mamusie    2.0
19514  18936   unfassbar sieben Gefecht davon Sechs mal LOWTIER    0.0
19963  35514                Etwas Hilfe bei C7 wäre schon nett!    0.0
20116   6398        Hilfe! Ich werde gleich auf A3 verpr??gelt!    0.0
20280   4092                  hep mi mallar bize denk gelir amk    0.0
20326  16898  siema opłaca sie dokupic stabe bo mam dosyłacz...    0.0
20365  36686                   sam se musze podświetlać masakra    0.0
20368  41746                  una scimmia mi ha spottato in G1!    0.0
20428  32265   Kann es sein das ich Dumm bin oder so, bin offen    1.0
20518  33379                ihr dreckigen schweine kanaken pack    1.0
20577  14714  ha zavar az 1es tier akkor mehetünk tier 8 ha ...    0.0
20890  43257                  Emil...bist du ein bisschen dumm?    2.0
20958  44034                  Du siehst mich, Ich seh Dich! D2!    0.0
21148  47397                Etwas Hilfe bei K0 wäre schon nett!    0.0
21229  27140              gleich raus mit solchen Schwachköpfen    1.0
21273  17234  son una mierda, tengo que defender porque casi...    1.0
21395  51400  Aufgeklärt bei Position F1. Etwas Hilfe währe ...    0.0
21686  30446  qrwa flanki nie potrafia obstawic pierdolone gady    1.0
22155   7878  za pocetak samo da jebem mater svi ljudima sto...    2.0
22278  35516                Etwas Hilfe bei B5 wäre schon nett!    0.0
22307  16518    emil yerime geçersen sana boru anahtarı sokarım    0.0
22320  50186  Nowo powstały klan NIPL rekrutacja otwarta,zer...    0.0
22336   4037    EinfachSmon (IS-4), you are blocking my target!    0.0
22431  30917   jak wy to kurwa wygracie to ja pierdolnę fikołka    1.0
22478  30299  KEWNFKJNkwjsnfeijnijwNKBFBwebbubgvgvvvgvvyvuvV...    0.0
22705  26349  sag mal du dämlicher scout idiot?? Schießt du ...    1.0
22788  41745                  una scimmia mi ha spottato in G1!    0.0
23034  49541  niech ten twoj kolega naiuczy sie grac kołowec...    0.0
23104  51393  Aufgeklärt bei Position D3. Etwas Hilfe währe ...    0.0
23260  41749                  una scimmia mi ha spottato in B5!    0.0
23375   7354       od lajta i kurwa 2 boki ci????kich czo??g??w    1.0
23914   3988             kil??ttem r?? 5 m??sodpercre ki l??...    0.0
23947  11787  na polibudzie sobie nie poradziłem na drugim r...    0.0
24063  26247                  ein freundliches Hallo an alle...    0.0
24231  51398  Aufgeklärt bei Position F2. Etwas Hilfe währe ...    0.0
24294   6396        Hilfe! Ich werde gleich auf B1 verpr??gelt!    0.0
24677  14715                    rontja a statot a kicsi tier :D    0.0
24908  25111  Tros_winner (Mäuschen), you‘re blocking my lin...    0.0
24972  14793  Salut,clanul GLADIATORII asteapta jucatori,cin...    0.0
25041  11792  ja to jeszcze 4 kalsa szkoly zostala ale w mak...    0.0
25067  49556  nie blokowałem aby sie zatrzymałem i stałem w ...    0.0
25099  15570            regler en defaite par le serveur nul :(    0.0
25234  52723               tyy głupi huju 703 wypierdalaj nobie    3.0
25664  17612  mais c'est reparti l'arty sur wot , ils ont fa...    0.0
25766  33711                 gg keiner fährt rechts ihr idioten    1.0
25927  16345         Hilfe! ich werde auf J4 gleich verprügelt!    0.0
25956  30035    gorev vari ne guzel oluru burda yalan oldu yine    0.0
26262  15798    WEHATSPOŐ JEDjipoáőtegijpkolnőémádhgéjkonmsfmál    0.0
26422   2525                 flanc l'ouest camarade communistes    3.0
26684  46683              reıs burdaydılar en son bana sıkarken    0.0
26822  16346         Hilfe! ich werde auf J4 gleich verprügelt!    0.0
26823  38482  kurwa kocham ta gre 80% pierwszych bitew arta ...    0.0
26972  31168                     e wezma cie do lepszego klanu?    0.0
27111  11095       deshalb gaaanz hinten bleiben oder versenken    0.0
27201  17601                    go og ogogo go og ogo go go ooo    0.0
27215  32916  ruszki681212 (05.05.2023 0:51:45) kurd meg a r...    3.0
27503   8550                 fressed vesela ihre schuhe rotwein    0.0
27603  38510           l2p schweinepanzer 2 und rucksacktourist    0.0
27948   2402               Ja grindivaunu, ei parasta tykki??..    0.0
27963   5167              asdfjkoa seughfiuagfeiuygaseiyuafweg]    0.0
28053   9546        Hilfe! Ich werde gleich auf C4 verpr??gelt!    0.0
28256  51392  Aufgeklärt bei Position C3. Etwas Hilfe währe ...    0.0
28266  18165         senin gibi oruspu cocuklari yuzunden oldum    1.0
28479  35517                Etwas Hilfe bei C4 wäre schon nett!    0.0
28549  18287         nicht gut abschilessen &gt;&lt; roflkopter    0.0
28592  35278  herrlich gibnt es heute nur 10e matche für mic...    0.0
29167  35521                Etwas Hilfe bei F2 wäre schon nett!    0.0
29214  51401  Aufgeklärt bei Position G2. Etwas Hilfe währe ...    0.0
29727  32264   Kann es sein das ich Dumm bin oder so, bin offen    1.0
30024  46074                     alter was seid ihr fürn haufen    1.0
30481  31777          e25 unser held :) echt gut gespielt junge    0.0
30734  35345    skurwielcu jebany znojda cie w realu i rozjebia    0.0
30761  14716                     szerintem pont hogy nem rontja    0.0
30908  47202  WY KURWY JEABane slepe mam nadzieje ze kruwa k...    0.0
31732  23994              az artiknak ti lesztek a kedvencei :D    0.0
31955  47398                Etwas Hilfe bei J0 wäre schon nett!    0.0
32069  45849            rusz ta pizde kurwa is potuj szmaciarzu    1.0
32208   6392        Hilfe! Ich werde gleich auf J7 verpr??gelt!    0.0
32214  39206  artyyyyyyyyyyyyyyyyyyyyyyyyyyyy!!!!!!!!!!!!!!!...    0.0
32292   9538        Hilfe! Ich werde gleich auf G1 verpr??gelt!    0.0
32600  49560               ale kij z tym powodzenia w nastepnym    0.0
32650  27968  wr a co to kurwa jest niedojebany kacapski obc...    3.0
32763  19125                    kiedy masz takie kurwy nie myte    3.0
32787   8114                  Du siehst mich, Ich seh Dich! D3!    0.0
32902  53243  Bonjour ! Clan Fr. Nous recrutons&quot;AV424-L...    0.0
33299  17216  fast alle auf einer Seite kann nicht funktioni...    0.0
33441  51402  Aufgeklärt bei Position H1. Etwas Hilfe währe ...    0.0
33446  33626             full life mäusschen.. MOVE YOUR ASS!!!    1.0
33524   1137  FR ROCK recrute francophones, voir conditions ...    0.0
33901  51399  Aufgeklärt bei Position F2. Etwas Hilfe währe ...    0.0
33920  20639  pierdolona cioto z ciezkiego w warcabi idz gra...    1.0
34147   4904             Das hab ich so uch npoch nicht gesehen    0.0
34636   2541                     except our communiste espagnol    3.0
34866   9535        Hilfe! Ich werde gleich auf G1 verpr??gelt!    0.0
35341  41269                   Heilige Einfachheit, bewege dich    0.0
35391  19986      jak cos do mnie mowisz to wyjmij chuja z buzi    1.0
35702   5483     man zieh den finger aus deinem arsch und fahre    1.0
35730  16257  wer sich schon joergimaus nennt... ab zum CSD ...    0.0
36231   2485             ihr arschgefickten dummen schei?? bots    1.0
36272  27969  majac takich graczy jak ty to i ma sie takie z...    3.0
36853  10942  POOOOUHHHHHHHHHHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAA...    0.0
36994  54186  salaklar arkanızda ben varım amk malları biraz...    0.0
37055  36277     há mennyi megmondó ember van itt is hihetetlen    0.0
37309   9542        Hilfe! Ich werde gleich auf E1 verpr??gelt!    0.0
37365   4239  no kurwa jebana, nie mia??o jakiej mapy poloso...    0.0
37676  11645       nie do???? ??e pizda na topie to jescze zjeb    1.0
38148  33298                   tepe kurwy ruchane w dupe szmaty    3.0
39239  44044                Kann mir wer bei C2 zur Hand gehen!    0.0
39306  30168  Die Puma Community ist nun soweit auch den 2. ...    0.0
39352  27964  twoj stary debil ze sie nie spuscil na kupe la...    3.0
39578   4105     sah dannach aus als w??rdest du hilfe brauchen    0.0
39657   2202  ja rozumie byc slabym graczem ale zeby miec 20...    0.0
39853   8120                  Du siehst mich, Ich seh Dich! F2!    0.0
39872  30905                  a ty to kurwa kto? Książe persji?    3.0
39919  52847  agyonbaszott buffolt szartartály mattilda a va...    2.0
39944   5518  rsdvsdrzhsdtubdtfujbdtfbjsdtjdrtjbdrtjdrbrtfuj...    0.0
40020   6394        Hilfe! Ich werde gleich auf C1 verpr??gelt!    0.0
40199  44029                Kann mir wer bei C2 zur Hand gehen!    0.0
40237  11793  mam już pracę stałą. Od ręki mnie zatrudnili z...    0.0
40277  14208                 hát ez nem igazán sikerült barátom    0.0
40279  47395                Etwas Hilfe bei K0 wäre schon nett!    0.0
40322  25883  GG GUYS HIDE HARXDER ;L.OKLKLIKOOLLKOOLLOOLOKK...    0.0
40500  33319      ei tuu mittää tästä hommasta tälläi selvinpäi    1.0
40627  33510             ihr arschgefickten dummnen scheiß bots    1.0
40897  12326            schon wieder zuviele hohlkörper im team    0.0
41354  28551              EN NATUURLIJK TARGETARTY MIJ WEER GVD    0.0
41443  30906             przyjechales pchac pizde i sie prujesz    1.0
41536  30914  a jak jestes slepy i nie widzisz jak sie na ko...    1.0
41551  44032                Kann mir wer bei C3 zur Hand gehen!    0.0
41592  47394                Etwas Hilfe bei K8 wäre schon nett!    0.0
41697  11797                no ładny, lecz pisownię ma powaloną    0.0
41702  32263   Kann es sein das ich Dumm bin oder so, bin offen    1.0
41867  32823    a jak niewiadomo o co chodzi to chodzi o kutasa    1.0
42105   2400  eka t???? oma samanlainen vaunu puski tohon sa...    0.0
42508  51391  Aufgeklärt bei Position C3. Etwas Hilfe währe ...    0.0
42546  51736           odbic to ci moge buta na ryju jak chcesz    2.0
42556  48002                   alles nur noch clowns am spielen    0.0
42991  48981  MOCSKOSALJASFÉREGFASSZOPÓPATKÁNYCSICSKAKÖCSÖGB...    3.0
43009  44047                  Du siehst mich, Ich seh Dich! G3!    0.0
43064  11447  ja spierdalam na kolacje bede afk grajcie z 5 ...    0.0
43130  12293                  takie cuda tylko w wocie hahaha:)    0.0
43174  18285  na die bringen dem team wenigstens mehr liebe ...    0.0
43396  28370  Wer Lust auf einen Clan hat, kann mich nach de...    0.0
43425  16348         Hilfe! ich werde auf J4 gleich verprügelt!    0.0
44021  43957  killyourself scheiss hurensöhne enrstahft kill...    4.0
44076  16352         Hilfe! ich werde auf E3 gleich verprügelt!    0.0
44091  16355         Hilfe! ich werde auf B7 gleich verprügelt!    0.0
44550  34680                junge unterstüzung und nicht campen    0.0
44564   7701  was f??r deppen auf meiner seite warum lasst i...    0.0
44600  38380  VerteidiGER5 (KV-1SA), you are blocking my tar...    0.0
44758  44036                  Du siehst mich, Ich seh Dich! D2!    0.0
45153  32262   Kann es sein das ich Dumm bin oder so, bin offen    1.0
45610   8116                  Du siehst mich, Ich seh Dich! E3!    0.0
45685  43247  ich weiss nicht wie man sich so dumm aufteilen...    2.0
45906   8410           no chlopie na tej arcie robisz robote :D    0.0
45929   8732             dont expect a super unicum to auto aim    0.0
45999  18161                   amina kodugumun oruspu çocuklari    2.0
46103  33791         und wieder ein dämliches Arschlochteam !!!    1.0
46164  21141  GRILLLE CROOOSOOSOSOSOSOS ANNDND YOOUUUUU SSLL...    1.0
46188  35515                Etwas Hilfe bei B6 wäre schon nett!    0.0
46358  10881  mit solchen spielern wie euch,blamiert man sic...    0.0
46399   6988                jajajaj estamos tiudos de este lado    0.0
47102  36833  sympa les bataille de samedi soir, sur le twit...    0.0
47201   9539        Hilfe! Ich werde gleich auf G1 verpr??gelt!    0.0
47333  16354         Hilfe! ich werde auf C3 gleich verprügelt!    0.0
47379  44575     reportarlo? jajaja que done los organos jajaja    0.0
47431  28549  Dit is trouwens waarom ik nooit anders dan ran...    0.0

Only 294 rows. Let's drop that as well.

In [8]:
# dataset update
wot_en = wot_en[~mask].reset_index(drop = True)
# length after the drop 
print(f"Length after the drop:{wot_en.shape[0]}")

Length after the drop:49670

#### Mislabeled data

In [9]:
# few top rows of the data
wot_en.head(5)

   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0
3  25964                      3 gunmark    0.0
4  28643                            lol    0.0

We might have mislabeled toxicity data that was classified as non-toxic or opposite. We need to detect and fix that as well.

In [12]:
from cleanlab.filter import find_label_issues
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_val_predict

# splits 
X = wot_en["message"].values
y = wot_en["label"].astype(int).values

# simple pipeline 
pipe = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=1, max_df=0.95,
                               sublinear_tf=True, norm="l2")),
    ("clf", LogisticRegression(max_iter=1000, random_state=7524)),
])

# out-of-fold predicted probabilities (needs predict_proba - LR not LinearSVC)
oof_probs = cross_val_predict(pipe, X, y, cv=5, method="predict_proba", n_jobs=-1)

# find label issues
issue_idx = find_label_issues(
    labels=y,
    pred_probs=oof_probs,
    return_indices_ranked_by="self_confidence",  # worst first
)

print(f"Suspected mislabeled: {len(issue_idx)} ({len(issue_idx)/len(y):.1%})")

# inspect top offenders
wot_en.iloc[issue_idx[:50]][["message", "label"]].assign(
    predicted=oof_probs[issue_idx[:50]].argmax(axis=1)
)

Suspected mislabeled: 2511 (5.1%)

                                                 message  label  predicted
44060                                     idiot campersw    0.0          1
42775                                              idiot    0.0          1
40041                                              idiot    0.0          1
42189                                              idiot    0.0          1
28059                                              idiot    0.0          1
25302                                              idiot    0.0          1
10128                                      cromvel idiot    0.0          1
13752                                              idiot    0.0          1
12624                                              idiot    0.0          1
37867                                              idiot    0.0          1
47904                             fucking useless morons    0.0          1
42829                                     3 autista noob    3.0          1
45081                        holocaust ist ne nice Sache    5.0          0
31208                         stupid son of drug addicts    5.0          1
20712                                           i'm noob    0.0          1
17328                                              idiot    2.0          1
13481                                               noob    0.0          1
40657                                   fucking hopeless    0.0          1
28590                                       Fucking mesh    0.0          1
7030                                      destroy rossia    5.0          0
34272                                            caliban    5.0          0
13451                                               nais    5.0          0
43109                                              fuck]    0.0          2
11051  MIGHT THINK ABOUT KILLING THAT SCOUT SOMETIME ...    4.0          0
16165                                      fucking moron    0.0          1
43841                                             idiots    0.0          1
42782                                             idiots    0.0          1
43795                                             IDIOTS    0.0          1
11261                                                bot    0.0          1
14438                                                bot    0.0          1
13080                                                bot    0.0          1
15578                                                bot    0.0          1
21638                                                bot    0.0          1
24809                                                bot    0.0          1
20335                                               bot?    0.0          1
32184                                      we can kill u    4.0          0
46267                    i will put thereplay in youtube    4.0          0
2208                                        go spot nig*    3.0          0
19674                               IS ig naz1 sh1t ;)xd    5.0          0
28957                                             idiots    0.0          1
22971                                             idiots    0.0          1
10173                                            go kyss    4.0          0
20855  hey skoda you whont bananan??? fucking moneky ...    3.0          1
24155                                        *** useless    0.0          1
21601                      szmato oby si rodzina zdechla    4.0          0
4728                                                 bot    0.0          1
5736                                                 bot    0.0          1
31176                                                Bot    0.0          1
30268                                                bot    0.0          1
37567                                        t1heavy bot    0.0          1

This is noisy. We need to detect those that were not classified toxic while toxic

In [13]:
predicted = oof_probs.argmax(axis=1)

# only flag: labeled non-toxic, model confidently says toxic
non_toxic_mislabeled = (
    (y == 0) &                          # labeled non-toxic
    (predicted != 0) &                  # model says toxic
    (oof_probs.max(axis=1) > 0.60)      # let's explore for any confidence 
)

# filter and sort to flagged 
flagged = wot_en[non_toxic_mislabeled][["message", "label"]].copy()
flagged["predicted"] = predicted[non_toxic_mislabeled]
flagged["confidence"] = oof_probs.max(axis=1)[non_toxic_mislabeled]
flagged = flagged.sort_values("confidence", ascending=False)

with pd.option_context("display.max_rows", 595):
    print(f"Suspected 0 - toxic mislabels: {len(flagged)}")
    print(flagged.head(594))

Suspected 0 - toxic mislabels: 459
                                                 message  label  predicted  \
44060                                     idiot campersw    0.0          1
42775                                              idiot    0.0          1
42189                                              idiot    0.0          1
40041                                              idiot    0.0          1
13752                                              idiot    0.0          1
10128                                      cromvel idiot    0.0          1
12624                                              idiot    0.0          1
28059                                              idiot    0.0          1
25302                                              idiot    0.0          1
37867                                              idiot    0.0          1
14438                                                bot    0.0          1
11261                                                bot    0.0          1
13080                                                bot    0.0          1
15578                                                bot    0.0          1
21638                                                bot    0.0          1
24809                                                bot    0.0          1
20335                                               bot?    0.0          1
20712                                           i'm noob    0.0          1
30268                                                bot    0.0          1
37567                                        t1heavy bot    0.0          1
31176                                                Bot    0.0          1
5736                                                 bot    0.0          1
4728                                                 bot    0.0          1
13481                                               noob    0.0          1
41583                                                bot    0.0          1
45619                                                bot    0.0          1
42782                                             idiots    0.0          1
43795                                             IDIOTS    0.0          1
43841                                             idiots    0.0          1
28957                                             idiots    0.0          1
22971                                             idiots    0.0          1
13586                                             idiots    0.0          1
85                                                idiots    0.0          1
3878                                              idiots    0.0          1
47904                             fucking useless morons    0.0          1
15488                                             retard    0.0          1
11181                                             retard    0.0          1
32062                              stupid retard campers    0.0          1
24155                                        *** useless    0.0          1
12879                                     you idiot meds    0.0          1
37928                                        bot players    0.0          1
4912                                       ****** morons    0.0          1
26010                                      idiot heavies    0.0          1
1882                                           noob team    0.0          1
43367                                             stupid    0.0          1
16165                                      fucking moron    0.0          1
10586                                              noobs    0.0          1
45454                                              noobs    0.0          1
17563                                               bots    0.0          1
18622                                               BOTS    0.0          1
12653                                               bots    0.0          1
45905                                   FU idiot unskill    0.0          1
29731                                              noobs    0.0          1
31637                                      Useless tiger    0.0          1
46718                                               bots    0.0          1
46964                                              *bots    0.0          1
7168                                           fkin bots    0.0          1
11734                                           idiot Wt    0.0          1
16893                                    S5 was a bot :/    0.0          1
9696                                                bots    0.0          1
2748                                                bots    0.0          1
19869                               amx you stupid idiot    0.0          1
32528                                               bots    0.0          1
44469                                          IS-2 Bot?    0.0          1
6730                                             retards    0.0          1
1154                                           3 retards    0.0          1
1250                                            bot team    0.0          1
12595                                         idiot cent    0.0          1
21045                                        total idiot    0.0          1
9824                                         stupid team    0.0          1
39189                                           ts idiot    0.0          1
32611                                          me bot...    0.0          1
28000                                fucking retard team    0.0          1
44314                                           hi idiot    0.0          1
35666                            raly??? fucking WG cunt    0.0          1
34072                               FUCKING BLIND IDIOTS    0.0          1
30528                                         stupid dog    0.0          1
13103                          are you all retarded?????    0.0          1
28215                                            bot die    0.0          1
48053                                     monti bot move    0.0          1
35220                                          lol moron    0.0          1
39672                                         heavys bot    0.0          1
43118                                          \noob 121    0.0          1
12986                                          UNINSTALL    0.0          1
43167                                               lose    0.0          2
40162                                               lose    0.0          2
40258                                               lose    0.0          2
38567                                    are you stupid?    0.0          1
37303                                fuking useless botr    0.0          1
2144                                           damn noob    0.0          1
15860                                          coward...    0.0          1
44200                                        arty retard    0.0          1
20701                                     FU ALL CAMPERS    0.0          1
45896                     You are retards I am INvizible    0.0          1
38863                                       fuck you RNG    0.0          1
46508                                       I am useless    0.0          1
44253                                      stupid heavys    0.0          1
34063                                           f camper    0.0          1
4724                                           its a bot    0.0          1
32833                                      parking idiot    0.0          1
28697                                        move morons    0.0          1
20776                                                 fu    0.0          1
27447                                                 fu    0.0          1
11788                                   was that a bot??    0.0          1
18100                                      bot peregrine    0.0          1
32625                                         retard amx    0.0          1
32000                               camper piece of crao    0.0          1
45751                                       idioten team    0.0          1
39249              *repoet all fu cu ki ng heavys camper    0.0          1
21125                             Mozgasd a beled camper    0.0          1
29487                                             camper    0.0          1
9308                                          *** camper    0.0          1
42492                                     haftoo be bots    0.0          1
21037                                        its useless    0.0          1
1024                                      useless lights    0.0          1
9150                                    tem full of bots    0.0          1
7345                                              m6-bot    0.0          1
13107                                                 FU    0.0          1
22007                                      su move idiot    0.0          1
25202                                         coward 55a    0.0          1
6399                     how died that idiot camper -44?    0.0          1
26436                                          omg noobs    0.0          1
38388                                             fk you    0.0          1
4685                                    you suck deadman    0.0          1
37422                                        next idiots    0.0          1
16745                                     next shit team    0.0          1
31294                                          fuck team    0.0          1
14688                                         FU campers    0.0          1
29623                                        is useless?    0.0          1
23997                                     vk full hp bot    0.0          1
1306                                                lose    0.0          2
44801                                     leo report bot    0.0          1
14968                                            Fu meds    0.0          1
20233                                                kid    0.0          1
9221                                        fucking aids    0.0          1
41324                              loset game noobs team    0.0          1
13607                                 but ppl are stupid    0.0          1
17912                                 damn idiots noone?    0.0          1
31563                                        move idiots    0.0          1
45340                                              debil    0.0          1
48794                                              debil    0.0          1
26423                                      wolverine bot    0.0          1
31101                                     fuckign camper    0.0          1
27859                                       jebany debil    0.0          1
25217                                      idiot hellcat    0.0          1
28767                                        THNX IDIOTS    0.0          1
7833                                            move bot    0.0          1
42625                               nicalo idiot and all    0.0          1
5766                                                 ffs    0.0          2
8801                                                 ffs    0.0          2
8918                                                 ffs    0.0          2
4451                                                 ffs    0.0          2
18825                                            704 bot    0.0          1
18320                                             brain!    0.0          1
36161                                   fucking imbecils    0.0          1
13893                                        gg bot team    0.0          1
47783              FY WG not hitting somthing MORON GAME    0.0          1
11896                                        stupid e100    0.0          1
31678                                                 fu    0.0          1
40657                                   fucking hopeless    0.0          1
46656                                         idiot 4005    0.0          1
14390                                            kv5 bot    0.0          1
18715                             char mle idiot press x    0.0          1
2766                                      jj play idiots    0.0          1
32366                                            go bots    0.0          1
23636                                   fuckin bot in bc    0.0          1
27304                                                wtf    0.0          2
21280                                               WTF?    0.0          2
26806                                                wtf    0.0          2
21306                                                wtf    0.0          2
22986                                                wtf    0.0          2
28184                                                wtf    0.0          2
22623                                                wtf    0.0          2
20951                                              wtf a    0.0          2
20957                                               wtf?    0.0          2
20273                                                wtf    0.0          2
26275                                                WTF    0.0          2
26195                                                wtf    0.0          2
20272                                                wtf    0.0          2
25889                                                wtf    0.0          2
24262                                                WTF    0.0          2
24419                                                wtf    0.0          2
24440                                                wtf    0.0          2
25553                                                wtf    0.0          2
25162                                                wtf    0.0          2
22155                                                wtf    0.0          2
32821                                       \fucking art    0.0          1
10500                                            T30 bot    0.0          1
33865                                Thunderbolt useless    0.0          1
33121                                        shut up bot    0.0          1
39444                 you mentioning your autobiography?    0.0          1
12078                              all Bastard camper A3    0.0          1
11044                                           viva bot    0.0          1
20315                                               lose    0.0          2
28654                               DAMN i HATE THIS MAP    0.0          2
34324                                are you so stupid ?    0.0          1
24685                                            gg bots    0.0          1
25935                          our scout is patetic noob    0.0          1
15250                                        play tetris    0.0          1
21439                                    Mooove your ass    0.0          1
35231                                           assholes    0.0          1
25946                                     next lt idiots    0.0          1
11993                                                ffs    0.0          2
7460                                              to bot    0.0          1
34248                                                ffs    0.0          2
41546                                             i suck    0.0          1
37007                                            bot amx    0.0          1
9465                                             yea bot    0.0          1
9294                                           112 = bot    0.0          1
12674                                  i collect lose :D    0.0          2
29806                                       wz big idiot    0.0          1
21450                                         stupid med    0.0          1
45552                                            bot bbq    0.0          1
33773                             heavys bot and chıcken    0.0          1
15060                                                fkn    0.0          1
24431                                       shit campers    0.0          1
49103                                                ffs    0.0          2
39730                                                ffs    0.0          2
44382                                                ffs    0.0          2
28649                                                ffs    0.0          2
20275                                                ffs    0.0          2
34369                       next red losers team - 9 red    0.0          1
22428                                            FCK YOU    0.0          1
39331                           lights mega campers bots    0.0          1
4240                                                 wtf    0.0          2
1954                                                 wtf    0.0          2
3015                                                 wtf    0.0          2
3003                                                 wtf    0.0          2
4795                                          lnacen wtf    0.0          2
6823                                                 wtf    0.0          2
6839                                                 WTF    0.0          2
7856                                                 wtf    0.0          2
1560                                                 wtf    0.0          2
721                                                 wtf?    0.0          2
38104                                           trash lt    0.0          1
37554                                       another lose    0.0          2
39194                                       another lose    0.0          2
30237                                             wtf...    0.0          2
39613                                               wtf?    0.0          2
32319                                                wtf    0.0          2
33422                                                wtf    0.0          2
30112                                                wtf    0.0          2
32896                                                wtf    0.0          2
36723                                                wtf    0.0          2
10044                                           at trash    0.0          1
15584                                  report T9 for bot    0.0          1
28590                                       Fucking mesh    0.0          1
49287                                            campers    0.0          1
7350                                         retard team    0.0          1
11367                                                wtf    0.0          2
19727                                                WTF    0.0          2
13943                                        wtf 1 shooz    0.0          2
12492                                                wtf    0.0          2
14553                                                wtf    0.0          2
10883                                                wtf    0.0          2
10510                                                wtf    0.0          2
48215                                                wtf    0.0          2
45933                                                wtf    0.0          2
46272                                                wtf    0.0          2
44974                                                wtf    0.0          2
39755                                                WTF    0.0          2
46595                                                wtf    0.0          2
42990                                                wtf    0.0          2
46803                                                wtf    0.0          2
41859                                                wtf    0.0          2

Most of them are mislabeled. Let's drop those

In [14]:
wot_en = wot_en[~non_toxic_mislabeled].reset_index(drop = True)
print(f"Length after update:{wot_en.shape[0]}")

Length after update:49211

#### Final verification

In [15]:
# basic data checks
print("=== Shape ===")
print(wot_en.shape)

print("\n=== Nulls ===")
print(wot_en.isnull().sum())

print("\n=== Duplicate messages ===")
print(wot_en.duplicated(subset="message").sum())

print("\n=== Overall label distribution ===")
counts = wot_en["label"].value_counts().sort_index()
pct = wot_en["label"].value_counts(normalize=True).sort_index().mul(100).round(1)
print(pd.DataFrame({"count": counts, "pct%": pct}))

=== Shape ===
(49211, 3)

=== Nulls ===
index      0
message    0
label      0
dtype: int64

=== Duplicate messages ===
18040

=== Overall label distribution ===
       count  pct%
label
0.0    39950  81.2
1.0     6739  13.7
2.0     2177   4.4
3.0      252   0.5
4.0       66   0.1
5.0       27   0.1

We do not have any null values, however we got 18k duplicate messages.

We will explore duplicate rows and other issues in EDA. For now, let's save merged dataset to a parquet.

In [16]:
# save to parquet for easier loading in future steps
wot_en.to_parquet(PROJECT_ROOT / "data/processed_data/wot/wot.parquet", index=False)

## Dota

**Dota**
| Class | Label |
|---|---|
| 0 | Other (non-toxic) |
| 1 | Ego |
| 2 | Aggression |
| 3 | Impolite |

#### Inspect each split

In [17]:
# import data
train = pd.read_csv(DATA_DIR_DOTA / "CONDA_train.csv")
val = pd.read_csv(DATA_DIR_DOTA / "CONDA_valid.csv")

# inspect each split
for name, df in [("train", train), ("val", val)]:
    print(f"--- {name} ---")
    print(f"Shape: {df.shape}\n")
    print(f"Columns: {list(df.columns)}\n")
    print(f"First few rows of the data:\n{df.head(3)}\n")

--- train ---
Shape: (26921, 10)

Columns: ['Id', 'matchId', 'conversationId', 'utterance', 'chatTime', 'playerSlot', 'playerId', 'intentClass', 'slotClasses', 'slotTokens']

First few rows of the data:
      Id  matchId  conversationId utterance  chatTime  playerSlot  \
0  11263      697            3193      wow!        76           0
1  13741      843            3809       WTF      1563           5
2  22125     1412            6199   wpe wpe      2853           1

                  playerId intentClass slotClasses          slotTokens
0  ANTS IN MY EYES JOHNSON           O          O            wow (O),
1                      M.k           O          T            WTF (T),
2              Acqua Ragia           O        O O   wpe (O), wpe (O),

--- val ---
Shape: (8974, 10)

Columns: ['Id', 'matchId', 'conversationId', 'utterance', 'chatTime', 'playerSlot', 'playerId', 'intentClass', 'slotClasses', 'slotTokens']

First few rows of the data:
      Id  matchId  conversationId                 utterance  chatTime  \
0   6911      456            1987                        GG      3031
1   1512      132             509                        gg      2887
2  43138     2905           12306  GG [SEPA] nice late game      2783

   playerSlot                         playerId intentClass    slotClasses  \
0           9                               OG           O             S
1           9                             Xion           O             S
2           1  Im  good but my team is so  bad           O  S SEPA O O O

                                          slotTokens
0                                           GG (S),
1                                           gg (S),
2  GG (S), [SEPA] (SEPA), nice (O), late (O), gam...

#### Clean, merge and standardise

In [18]:
# map intentClass to numeric label consistent with WoT schema
label_map = {'O': 0, 'E': 1, 'A': 2, 'I': 3}

# add split column and map labels
train["split"] = "train"
val["split"]   = "val"

# merge train + val (no test split in CONDA)
dota = pd.concat([train, val], ignore_index=True)

# keep only relevant columns and rename to match WoT schema
dota = dota[["Id", "utterance", "intentClass", "split"]].rename(columns={
    "Id": "index",
    "utterance":   "message",
    "intentClass": "label",
})

# map string labels to numeric
dota["label"] = dota["label"].map(label_map)

# drop nulls in message (7 train + 1 val)
dota = dota.dropna(subset=["message"]).reset_index(drop=True)

# shape 
print(f"Merged shape: {dota.shape}\n")
print(f"First few rows of the data:\n{dota.head(3)}\n")
print("\nInformation about the dataset:\n")
dota.info()

Merged shape: (35887, 4)

First few rows of the data:
   index  message  label  split
0  11263     wow!      0  train
1  13741      WTF      0  train
2  22125  wpe wpe      0  train


Information about the dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   index    35887 non-null  int64
 1   message  35887 non-null  object
 2   label    35887 non-null  int64
 3   split    35887 non-null  object
dtypes: int64(2), object(2)
memory usage: 1.1+ MB

Only `utterance`, `intentClass`, `Id`, and `split` are kept = the remaining columns (matchId, conversationId, chatTime, playerSlot, playerId, slotClasses, slotTokens) carry no linguistic content relevant to toxicity detection. Labels are mapped to integers matching the WoT schema where 0 = non-toxic. Null utterances are dropped - they carry no text signal.

#### Non-english language

Since we are going to model classifier on english data, it is important for us to detect non-english cases as many as we can.

In [19]:
# detecting Non-latin language first - same regex as WoT
dota_en_mask = dota["message"].apply(is_non_latin_script)
print(f"Non-english documents: {dota[dota_en_mask].reset_index(drop=True)}")

# drop such cases
before = len(dota)
dota_en = dota[~dota_en_mask].reset_index(drop=True)
print(f"Dropped {before - len(dota_en)} ({(before - len(dota_en))/before:.1%})")
print(f"Rows after the drop: {dota_en.shape[0]}")

Non-english documents:    index          message  label  split
0  36141  noob [SEPA] กาก      1  train
1  19064            ใจยเน      0  train
2   8391                ツ      0  train
3  27048                ื      0  train
4  37396               ำผ      0  train
5  41950              กาก      0    val
6  19066            คนไทย      0    val
7  32824               ทำ      0    val
8  33829              戒了吧      0    val
Dropped 9 (0.0%)
Rows after the drop: 35878

In [21]:
# detect latin but non-english documents - same detector as WoT
mask_d = dota_en["message"].apply(is_latin_non_english)
with pd.option_context("display.max_rows", 800):
    print(f"Non-english documents:{dota_en[mask_d]}")
    print(f"How many documents with non-english text: {dota_en[mask_d].shape[0]}")

Non-english documents:       index                                            message  label  split
1189   38131  reporta [SEPA] pro ibama [SEPA] fdp sacrifica ...      2  train
1196   40006  its in the bag  [SEPA] los q no tienen plata [...      0  train
1594   27145  vcs sao lixos [SEPA] n fode [SEPA] acha q fez ...      0  train
2394   38352  pukingina ka [SEPA] kangkong lancer [SEPA] goo...      0  train
4138     466  REPORT MI TEAM [SEPA] REPORT TODO MI TEAM BURR...      2  train
5765   12964                   LOOOOOOOOOL [SEPA] RECOMIENDENME      0  train
6387   37068                   oyoyoyoyoyoyoy wombo combo......      0  train
6472   25399  pro farmer [SEPA] orge farmt mehr als jeder bauer      0  train
6866   42190  very [SEPA] report a los 4 les puede tocar est...      2  train
6942   41505                 ez [SEPA] ez [SEPA] ez [SEPA] ezwp      3  train
8741   34169  POTANG INA KAYO [SEPA] BIGYAN NIYO NAMAN AKO N...      0  train
9141   33088  OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [...      0  train
9248    3484                    eZAASASAAS! [SEPA] SO EZA game!      0  train
9795    3131  gg report me team agggg [SEPA] report me team ...      2  train
10034  37028  XD [SEPA] XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...      0  train
10224  22135     xddddddddddddddddddddddddd [SEPA] ahgahahahaha      0  train
10402  36032            unluck ? [SEPA] EAIUHEAIUHEAIUEAIUHEAEA      0  train
10534  34340                    tienes que darme como 500 manos      0  train
10878  26090  qweeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...      0  train
12041  33090  OSfrog LE BALANCED FEMALE ROBIN HOOD OSfrog  [...      0  train
12803  10842               22 min agha undying [SEPA] yaysayaay      0  train
14237   6512     haahahaha [SEPA] CRY ASSHOLES [SEPA] kraaaaaay      1  train
14602  38130  reporta [SEPA] esse sf [SEPA] figueiredo [SEPA...      2  train
16351  43997                jaja pobre lloron [SEPA] hay basura      0  train
16577   1485  hay actualizacion [SEPA] lol [SEPA] se va a de...      0  train
18694  32694  ez bot ba>? [SEPA] ibig mong sabihin bobo kamp...      3  train
18731  33382       slardar pushhhhhhh [SEPA] slardar ds 1v1 mid      0  train
18844  33743  cRY MORE LA [SEPA] pinOYYYYYYYYY [SEPA] aW  [S...      0  train
20829  34335            diarrea eres} [SEPA] para eos vas medio      0  train
21094  37016  ojala no vuelva [SEPA] no quiero jugar con est...      0  train
21135  38353             it's a teamwipe [SEPA] it's a dizaztah      0  train
21487   2035  that slark [SEPA] HAWHWAHAW [SEPA] SO BAD [SEP...      1  train
21985  33078  Rsdfkpghsdšjhjosfh [SEPA] www.leagueoflegends....      0  train
22108  24484           GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      0  train
22163  27649  KKKKK [SEPA] KKKKKKKKKKKKK [SEPA] KKKKKKKKKKKK...      0  train
23139  28152       jogo muito n [SEPA] só desisti dessa partida      0  train
23336  28151  eu adoro bater em rubick q quer pagar de q jog...      0  train
24971  43767               JAJAJAJJA NO SABE A QUIEN GOLPEAR XD      0  train
25584  28145  `no susto? [SEPA] eu to tentando ensinar meu t...      0  train
26429  35195  1 for 1  [SEPA] haha [SEPA] kasrma [SEPA] is b...      1  train
27778  27910  HEHEHEHEHEEHEHEHEHEHEHEHEEHEHEHEHEHEHEHEHEHEEH...      0    val
28197  24480  ASDFSADFASDFASDFASDFASFASDFASDFSAFASDFSDAFSADF...      0    val
28564  27101        Report sf [SEPA] pinaka bobo sa buong mundo      2    val
29168   3519                THWN ORAXCLE AND WIM +1000% TO WIN!      0    val
29226  40639             I HATE THIS TEAM!!!!! [SEPA] HHSHSDHSD      1    val
29265  33881                   uya [SEPA] ks [SEPA] kayyyy esss      0    val
30971  28631  PORFAVOR AYUDEN NO LES GUSTARIA Q LES TOQUE ES...      0    val
31608  17235                   woierjewkhfiwepojoiwehfijwer ok?      0    val
31740   1612  GAGLHWSLHW [SEPA] HSLDHLWHWL [SEPA] LHAWLGAL [...      1    val
33152  32735  MURTAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...      0    val
33610  34543       OH FÜR Gottes willen [SEPA] WARUM SO EINFACH      0    val
33883  39614  WFEPI(J WPIJWPEIFG [SEPA] qfhqiuhfouqehfoqwf [...      2    val
34090  32783  u lile this [SEPA] u shit [SEPA] stfu [SEPA] e...      1    val
34880  28620  XD [SEPA] LINA Y PUGDE REPORTADO [SEPA] LINA Y...      0    val
35084   6491        GG [SEPA] AJAJAJAJAHAHAHAH [SEPA] HSJJAHAHA      0    val
35527  11475         stupid lion [SEPA] lel [SEPA] wkdopqwkdqwp      1    val
How many documents with non-english text: 56

Only 56 rows. Let's drop that as well.

In [22]:
# dataset update
dota_en = dota_en[~mask_d].reset_index(drop=True)
# length after the drop
print(f"Length after the drop: {dota_en.shape[0]}")

Length after the drop: 35822

#### Mislabeled data

In [23]:
# few top rows of the data
dota_en.head(5)

   index  message  label  split
0  11263     wow!      0  train
1  13741      WTF      0  train
2  22125  wpe wpe      0  train
3   6453   hahaha      0  train
4   9644      wtf      0  train

We might have mislabeled toxicity data that was classified as non-toxic or opposite. We need to detect and fix that as well.

In [24]:
# splits
X_d = dota_en["message"].values
y_d = dota_en["label"].astype(int).values

# simple pipeline - same config as WoT
pipe_d = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=1, max_df=0.95,
                               sublinear_tf=True, norm="l2")),
    ("clf", LogisticRegression(max_iter=1000, random_state=7524)),
])

# out-of-fold predicted probabilities
oof_probs_d = cross_val_predict(pipe_d, X_d, y_d, cv=5, method="predict_proba", n_jobs=-1)

# find label issues
issue_idx_d = find_label_issues(
    labels=y_d,
    pred_probs=oof_probs_d,
    return_indices_ranked_by="self_confidence",
)

print(f"Suspected mislabeled: {len(issue_idx_d)} ({len(issue_idx_d)/len(y_d):.1%})")

# inspect top offenders
dota_en.iloc[issue_idx_d[:50]][["message", "label"]].assign(
    predicted=oof_probs_d[issue_idx_d[:50]].argmax(axis=1)
)

Suspected mislabeled: 1527 (4.3%)

                                   message  label  predicted
7706                                   EZ^      0          3
7162                                   EZ)      0          3
5386                                   ez&      0          3
4696                                    ez      0          3
25633                                NOOB!      0          1
5070                                  noob      0          1
30173                                 NOOB      0          1
5468                                  shit      0          1
17515               SHUT UP FUCKING NOOB !      0          1
14254                       EZ PERRUUUUUUU      1          3
14040                                   Ez      1          3
11661                             ez staks      1          3
24129                                   EZ      1          3
34458             Fuck [SEPA] fucking zeus      0          1
5422                             2FCKNG EZ      1          3
33751                                   ez      1          3
30045                          why report?      0          2
11359                  ez russki [SEPA] :D      1          3
10033                       okay fuck shit      0          1
13525                                 afk?      0          2
5576                          fucking stop      0          1
26573                                 fuck      0          1
27120                                 fuck      0          1
28437                                 fuck      0          1
22689                                 fuck      0          1
29859                              commend      0          2
8073                                  fuck      0          1
11194                                 fuck      0          1
10860                                FUCK!      0          1
13149                                 FUCK      0          1
16116                                   gg      3          0
24960  gg [SEPA] ez [SEPA] ez [SEPA] blat'      0          3
1561                               commend      0          2
20100               ez kill [SEPA] ez life      0          3
16449                              ez game      2          3
30004                   NOOB [SEPA] HAHAHA      2          1
769                              gg fedeer      3          0
16395                                 fuck      0          1
19774                                 fuck      0          1
19168                                 fuck      0          1
24374                              commend      0          2
25035                                   gg      1          0
25653                        gg shitshaker      1          0
5526                       gg w[ [SEPA] ez      0          3
33427                             GG NOBOS      1          0
23140                                 HAHA      2          0
17775               ez game  [SEPA] ez mid      1          3
34508                               fuck u      0          1
27562                             1-9 ggwp      3          0
1388                                  ggwp      3          0

This is again noisy. We need to detect those that were not classified toxic while toxic

In [25]:
predicted_d = oof_probs_d.argmax(axis=1)

# only flag: labeled non-toxic, model confidently says toxic
non_toxic_mislabeled_d = (
    (y_d == 0) &
    (predicted_d != 0) &
    (oof_probs_d.max(axis=1) > 0.60)
)

# filter and sort to flagged
flagged_d = dota_en[non_toxic_mislabeled_d][["message", "label"]].copy()
flagged_d["predicted"] = predicted_d[non_toxic_mislabeled_d]
flagged_d["confidence"] = oof_probs_d.max(axis=1)[non_toxic_mislabeled_d]
flagged_d = flagged_d.sort_values("confidence", ascending=False)

with pd.option_context("display.max_rows", 252):
    print(f"Suspected 0 - toxic mislabels: {len(flagged_d)}")
    print(flagged_d)

Suspected 0 - toxic mislabels: 252
                                                 message  label  predicted  \
25633                                              NOOB!      0          1
30173                                               NOOB      0          1
5070                                                noob      0          1
5468                                                shit      0          1
7706                                                 EZ^      0          3
7162                                                 EZ)      0          3
17515                             SHUT UP FUCKING NOOB !      0          1
5386                                                 ez&      0          3
4696                                                  ez      0          3
10033                                     okay fuck shit      0          1
34458                           Fuck [SEPA] fucking zeus      0          1
22689                                               fuck      0          1
27120                                               fuck      0          1
28437                                               fuck      0          1
26573                                               fuck      0          1
10860                                              FUCK!      0          1
13149                                               FUCK      0          1
8073                                                fuck      0          1
11194                                               fuck      0          1
19774                                               fuck      0          1
16395                                               fuck      0          1
19168                                               fuck      0          1
5576                                        fucking stop      0          1
29859                                            commend      0          2
1561                                             commend      0          2
34508                                             fuck u      0          1
13525                                               afk?      0          2
24374                                            commend      0          2
2791                                                fuck      0          1
30045                                        why report?      0          2
10594                                              noobs      0          1
29950                                 LOL [SEPA] fucking      0          1
28480                                      66mins pause?      0          2
27645                                             pause?      0          2
23530                                             pause?      0          2
4114                                            y pause?      0          2
18068                                             pause?      0          2
7968                                              pause?      0          2
20100                             ez kill [SEPA] ez life      0          3
9797                                 the fucking keybord      0          1
2232                                             im noob      0          1
24960                gg [SEPA] ez [SEPA] ez [SEPA] blat'      0          3
8692                                     10 12 husk EZ?>      0          3
28640                                bg [SEPA] noob team      0          1
31791                                      Commend me :)      0          2
25479                                      commend me :)      0          2
33542                                               stfu      0          1
11030                         report for afk in fountain      0          2
5526                                     gg w[ [SEPA] ez      0          3
1392                                       ez hook ez ff      0          3
6117                                                Stfu      0          1
18245                                      fuck off zeus      0          1
22678                               mirana please report      0          2
23704                                      report spectr      0          2
17272                                GG [SEPA] fuck this      0          1
18545                             lets lobby [SEPA] noob      0          1
15429                                     oh [SEPA] shit      0          1
8224               im confsued now, who should i report?      0          2
18596                                           I AM GAY      0          1
22536                    REPORT [SEPA] BARAT [SEPA] GGWP      0          2
21116                                  fuck your english      0          1
1692                             so EZ! [SEPA] TOOO EZA!      0          3
16796         see [SEPA] that shit [SEPA] is just spooky      0          1
28670                          win these noob feel pro ?      0          1
17413                                        commend him      0          2
24344                                    Intense as fuck      0          1
29674                                      commend me ty      0          2
23300                                       spectre noob      0          1
17807       AAAAAAAAAAAAAAAAAA [SEPA] SUCK MY DIIIICKKKK      0          1
21357                                       commend lina      0          2
8640   I WILL ALWAYS SUCK HIS DICK AS LONG AS BARA WA...      0          1
1830                                              fk off      0          1
25875                           save your fucking throne      0          1
30714                               COMMEND ME [SEPA] TY      0          2
34585                                    LOL [SEPA] FUCK      0          1
28084                        hes garbage, mmr means shit      0          1
23823                           playing mmr with shit pc      0          1
11669      why the fuck you lion  [SEPA] you always lion      0          1
30670                                      WHAT THE FUCK      0          1
23117                                                 FU      0          1
26680                                                 Fu      0          1
23485                                          k unpause      0          2
7732                                        commend ursa      0          2
9699                HOLY SHIT [SEPA] HOW CAN DOOM SO BAD      0          1
10125                                          no pause?      0          2
11494                                          NO PAUSE?      0          2
21226                                  AFK [SEPA] RUBICK      0          2
8635                            GG [SEPA] FUCK THIS GAME      0          1
8653                                lol [SEPA] noob hook      0          1
19223                                  commend the juggs      0          2
22441                                   just 2 noobs top      0          1
16124                                              ez WR      0          3
1165   =)) [SEPA] ez mid [SEPA] next time pick veng [...      0          3
25021                           Very well fucking played      0          1
21563                                       did u pause?      0          2
3988   this tony [SEPA] is 2 much [SEPA] for me [SEPA...      0          1
16007                                           your mom      0          1
26129                                          WIN NIGGA      0          1
33612                               gg [SEPA] commend me      0          2
263                                  Commend support pls      0          2
29822             omg.. check your fucking net [SEPA] ..      0          1
5012                                          why pause?      0          2
32634                 talk when not done [SEPA] noob mid      0          1
21838                    lc thejm pls [SEPA] sladar noob      0          1
1502   u realize u are so fucking braindamaged when t...      0          1
12516                                          team afk)      0          2
5859          HAHGA [SEPA] COMMEND ME :) [SEPA] FOR POGI      0          2
16816                                        Very stupid      0          1
24145                                just what the fuck?      0          1
5014   if everyone just fucking calms the fuck down [...      0          1
17159                now i hit like a fucking kitten man      0          1
28304                                    hey [SEPA] FUCK      0          1
33783                                     commend meh <3      0          2
23936                                           asshole.      0          1
32055                                      commend GabeN      0          2
17997                                  COMMEND INTRO.,!!      0          2
16199  no yalll mid  [SEPA] yalll noob [SEPA] y didnt...      0          1
31943                    counterpicker [SEPA] get fucked      0          1
7202                                          COMMEND US      0          2
1033                                         and retards      0          1
18180                          please wait [SEPA] thanks      0          2
18606  finally its over [SEPA] the suffering [SEPA] f...      0          1
5631                                wait [SEPA] wait plz      0          2
24966                                         commend ty      0          2
12739             He won an off lane [SEPA] Vs a shit WK      0          1
26955                                oh what [SEPA] fuck      0          1
27019  STOP DEF [SEPA] IDIOTS [SEPA] ALYANSOV NASMOTR...      0          1
6730                                  report my team pls      0          2
6050                            gg wp [SEPA] noob sf too      0          1
6834                                      wait [SEPA] 1m      0          2
27620                               jesus fucking christ      0          1
9022                                im afk [SEPA] finish      0          2
17293                                  WAIT [SEPA] MOFOZ      0          2
32622  ur comparing ur tiny to our wk [SEPA] you guys...      0          1
34172  deward botm lane pls noob tide [SEPA] in rune ...      0          1
22000              hey wait pls [SEPA] wiat! [SEPA] wait      0          2
24939                                           wait sur      0          2
24256                                               wait      0          2
22017                                               wait      0          2
28559                                               wait      0          2
25450                                               wait      0          2
26376                                               wait      0          2
28581                                               wait      0          2
26667                                               wait      0          2
32967                           and you can fuck off too      0          1
35330                                        i rage quit      0          3
23765                                           wait pls      0          2
8588                                  NAXREN [SEPA] mOM?      0          1
16605                                   I WILL COMMEND U      0          2
9189                                     i commended you      0          2
28320                  blue talking ... [SEPA] holy shit      0          1
32508                   good game [SEPA] fuck that pudge      0          1
14876                           talk to much shit you do      0          1
29516                                       yep, i'm gay      0          1
26745                            Invoker useless unskill      0          1
15259                                           cant w8?      0          2
29273              didn't like my cow joke? [SEPA] fuck.      0          1
6083                                        will commend      0          2
17411                                     wait [SEPA] rc      0          2
32870                                       commend jugg      0          2
15505                                               WAIT      0          2
15232                                               wait      0          2
20309                                               WAIT      0          2
20402                                               WAIT      0          2
21119                                               wait      0          2
331                 invoker what the fuck are u playing?      0          1
13703                                  gg [SEPA] commend      0          2
33469                          worst invoker i ever seen      0          1
21281                                      you pause....      0          2
11074                        alive? [SEPA] what the fuck      0          1
12898               ./. [SEPA] commend me [SEPA] support      0          2
10835                                 WAIT - RYAN GOULD?      0          2
11165                                               wait      0          2
14129                                               WAIT      0          2
12043                                               wait      0          2
8827                                                wait      0          2
8356                                                wait      0          2
17522                             why u take bash retard      0          1
23598  fuck [SEPA] i missed the timing [SEPA] instant...      0          1
1362                                                WAIT      0          2
3290                                               wait?      0          2
6367                                                wait      0          2
6162                                               }wait      0          2
3725                                                wait      0          2
3891                                                wait      0          2
32506                                         WORST NAPS      0          1
8294         on some game losing SHIT [SEPA] RIGHT THERE      0          1
16756                                  GG COMMEND ME!!!!      0          2
4740                 plz, stop [SEPA] stop trash talking      0          1
10374                         relax bro [SEPA] i am noob      0          1
7129                              just wait , hes onlinE      0          2
35670                   free mmr [SEPA] fuck that 37 mmr      0          1
33693                    << [SEPA] COMMEND [SEPA] MAGNUS      0          2
950                                gg [SEPA] fuck dota 2      0          1
15519   im doing my best [SEPA] shit still happen always      0          1
1867                  come on man [SEPA] fuck you rubick      0          1
32452                                               wait      0          2
33153                                              wait!      0          2
33341                                               wait      0          2
33676                                               wait      0          2
33563  HAHAHA [SEPA] this fucking pc [SEPA] restarted...      0          1
35055                      nice [SEPA] gg [SEPA] commend      0          2
21735                                     you are a joke      0          1
23901              actually I should receive the commend      0          2
14580                       Game was good [SEPA] sf noob      0          1
26805  we lost i cant move properly [SEPA] suddenly 1...      0          1
3734                        always escape the fuck ahaha      0          1
1421                      reKT [SEPA] AA [SEPA] doG SHIT      0          1
25369          are you stupid troll?waiting for nothing?      0          1
16691  lc says he's coming [SEPA] you fuck [SEPA] why...      0          1
34745                             gg [SEPA] commend ogre      0          2
503                                             NOB TEAM      0          1
23600                      FUck you BB  [SEPA] feeder BB      0          1
34292                                ggwp [SEPA] commend      0          2
11327                           throne all [SEPA] me afk      0          2
27004  coz team comes noob [SEPA] and only thing left...      0          1
11198                 gg wp report blood [SEPA] end fast      0          2
14912  Sf said if lose he quit dota [SEPA] fucking wp...      0          1
25650   hahahaha [SEPA] i know [SEPA] hes noob [SEPA] XD      0          1
32648  COME THE FUCK ON [SEPA] ARE YOU JUST FOLLOWING...      0          1
9529                tghrowers [SEPA] ahahaha [SEPA] fuck      0          1
19665     again haste? [SEPA] ogre noob, but lucky day )      0          1
13108  deF LA FOOL [SEPA] PASUE? [SEPA] pAUSE? [SEPA]...      0          2
19513  fuck [SEPA] he is streaming on twitch [SEPA] w...      0          1
15236  AHHHH [SEPA] 274 win on invoker  [SEPA] ihave ...      0          1
13044                5 bkbs holy shit [SEPA] try is hard      0          1
3713                                          THATS DUMB      0          1
28665                                   they y unpause ?      0          2
7414                                           just wait      0          2
34177            pls finish [SEPA] its hard with 3 idiot      0          1
7900                                 ur arms are shaking      0          1
14771                              wp husker i commend u      0          2
1043                                          mid i feed      0          3
14061                             ggwp [SEPA] commend me      0          2
25261                           commend me or add plz ty      0          2
31920                                       wait for him      0          2
15357                                              feed*      0          3
18631                                               feed      0          3
361                                                  fck      0          1
2212                                                 Fck      0          1
14965                                         WAIT RECON      0          2
16297                                         damn pinoy      0          1
2249   youre score its like pi [SEPA] defending your ...      0          1
17424            holy shit [SEPA] they r not coming back      0          1
10672                       for mother russia! [SEPA] :D      0          1
9495                                        .. [SEPA] Fu      0          1
23968  i can beat any of you lil shits 1 v 1, but my ...      0          1
6851               wait [SEPA] 1 more [SEPA] please wait      0          2
34962              bkb [SEPA] haha [SEPA] stupid players      0          1
4977                                 so long [SEPA] fuck      0          1
17192                                                mad      0          3
17822  please [SEPA] hahahah [SEPA] commend me [SEPA]...      0          2

       confidence
25633    0.999984
30173    0.999984
5070     0.999983
5468     0.999946
7706     0.999937
7162     0.999937
17515    0.999894
5386     0.999850
4696     0.999850
10033    0.999589
34458    0.999495
22689    0.999052
27120    0.999052
28437    0.999052
26573    0.999052
10860    0.998717
13149    0.998717
8073     0.998717
11194    0.998717
19774    0.998135
16395    0.998135
19168    0.998135
5576     0.997891
29859    0.997580
1561     0.997425
34508    0.996867
13525    0.996698
24374    0.996525
2791     0.996295
30045    0.995893
10594    0.994496
29950    0.990886
28480    0.987394
27645    0.987394
23530    0.987394
4114     0.985091
18068    0.983059
7968     0.981364
20100    0.980536
9797     0.975584
2232     0.974480
24960    0.972176
8692     0.971397
28640    0.970857
31791    0.969083
25479    0.968089
33542    0.968062
11030    0.966246
5526     0.962516
1392     0.961368
6117     0.959584
18245    0.956753
22678    0.955544

Pattern clear: false positives cluster in predicted=2 (Aggression) - "commend", "wait", "pause", "afk" - model confuses coordination messages with aggression. Genuine mislabels mostly in predicted=1 (Ego/Insults): "noob", "fuck", "stfu", "ez".

Fix: only flag label=0 - predicted=1 (Insults). Skip predicted=2 (Aggression) - too noisy for Dota:

In [26]:
non_toxic_mislabeled_d = (
    (y_d == 0) &
    (predicted_d == 1) &        # only Ego/Insults, not Aggression
    (oof_probs_d.max(axis=1) > 0.60)
)

# filter and sort to flagged
flagged_d = dota_en[non_toxic_mislabeled_d][["message", "label"]].copy()
flagged_d["predicted"] = predicted_d[non_toxic_mislabeled_d]
flagged_d["confidence"] = oof_probs_d.max(axis=1)[non_toxic_mislabeled_d]
flagged_d = flagged_d.sort_values("confidence", ascending=False)

with pd.option_context("display.max_rows", 252):
    print(f"Suspected 0 - toxic mislabels: {len(flagged_d)}")
    print(flagged_d)

Suspected 0 - toxic mislabels: 131
                                                 message  label  predicted  \
25633                                              NOOB!      0          1
30173                                               NOOB      0          1
5070                                                noob      0          1
5468                                                shit      0          1
17515                             SHUT UP FUCKING NOOB !      0          1
10033                                     okay fuck shit      0          1
34458                           Fuck [SEPA] fucking zeus      0          1
28437                                               fuck      0          1
27120                                               fuck      0          1
22689                                               fuck      0          1
26573                                               fuck      0          1
10860                                              FUCK!      0          1
11194                                               fuck      0          1
13149                                               FUCK      0          1
8073                                                fuck      0          1
19774                                               fuck      0          1
19168                                               fuck      0          1
16395                                               fuck      0          1
5576                                        fucking stop      0          1
34508                                             fuck u      0          1
2791                                                fuck      0          1
10594                                              noobs      0          1
29950                                 LOL [SEPA] fucking      0          1
9797                                 the fucking keybord      0          1
2232                                             im noob      0          1
28640                                bg [SEPA] noob team      0          1
33542                                               stfu      0          1
6117                                                Stfu      0          1
18245                                      fuck off zeus      0          1
17272                                GG [SEPA] fuck this      0          1
18545                             lets lobby [SEPA] noob      0          1
15429                                     oh [SEPA] shit      0          1
18596                                           I AM GAY      0          1
21116                                  fuck your english      0          1
16796         see [SEPA] that shit [SEPA] is just spooky      0          1
28670                          win these noob feel pro ?      0          1
24344                                    Intense as fuck      0          1
23300                                       spectre noob      0          1
17807       AAAAAAAAAAAAAAAAAA [SEPA] SUCK MY DIIIICKKKK      0          1
8640   I WILL ALWAYS SUCK HIS DICK AS LONG AS BARA WA...      0          1
1830                                              fk off      0          1
25875                           save your fucking throne      0          1
34585                                    LOL [SEPA] FUCK      0          1
28084                        hes garbage, mmr means shit      0          1
23823                           playing mmr with shit pc      0          1
11669      why the fuck you lion  [SEPA] you always lion      0          1
30670                                      WHAT THE FUCK      0          1
23117                                                 FU      0          1
26680                                                 Fu      0          1
9699                HOLY SHIT [SEPA] HOW CAN DOOM SO BAD      0          1
8635                            GG [SEPA] FUCK THIS GAME      0          1
8653                                lol [SEPA] noob hook      0          1
22441                                   just 2 noobs top      0          1
25021                           Very well fucking played      0          1
3988   this tony [SEPA] is 2 much [SEPA] for me [SEPA...      0          1
16007                                           your mom      0          1
26129                                          WIN NIGGA      0          1
29822             omg.. check your fucking net [SEPA] ..      0          1
32634                 talk when not done [SEPA] noob mid      0          1
21838                    lc thejm pls [SEPA] sladar noob      0          1
1502   u realize u are so fucking braindamaged when t...      0          1
16816                                        Very stupid      0          1
24145                                just what the fuck?      0          1
5014   if everyone just fucking calms the fuck down [...      0          1
17159                now i hit like a fucking kitten man      0          1
28304                                    hey [SEPA] FUCK      0          1
23936                                           asshole.      0          1
16199  no yalll mid  [SEPA] yalll noob [SEPA] y didnt...      0          1
31943                    counterpicker [SEPA] get fucked      0          1
1033                                         and retards      0          1
18606  finally its over [SEPA] the suffering [SEPA] f...      0          1
12739             He won an off lane [SEPA] Vs a shit WK      0          1
26955                                oh what [SEPA] fuck      0          1
27019  STOP DEF [SEPA] IDIOTS [SEPA] ALYANSOV NASMOTR...      0          1
6050                            gg wp [SEPA] noob sf too      0          1
27620                               jesus fucking christ      0          1
32622  ur comparing ur tiny to our wk [SEPA] you guys...      0          1
34172  deward botm lane pls noob tide [SEPA] in rune ...      0          1
32967                           and you can fuck off too      0          1
8588                                  NAXREN [SEPA] mOM?      0          1
28320                  blue talking ... [SEPA] holy shit      0          1
32508                   good game [SEPA] fuck that pudge      0          1
14876                           talk to much shit you do      0          1
29516                                       yep, i'm gay      0          1
26745                            Invoker useless unskill      0          1
29273              didn't like my cow joke? [SEPA] fuck.      0          1
331                 invoker what the fuck are u playing?      0          1
33469                          worst invoker i ever seen      0          1
11074                        alive? [SEPA] what the fuck      0          1
17522                             why u take bash retard      0          1
23598  fuck [SEPA] i missed the timing [SEPA] instant...      0          1
32506                                         WORST NAPS      0          1
8294         on some game losing SHIT [SEPA] RIGHT THERE      0          1
4740                 plz, stop [SEPA] stop trash talking      0          1
10374                         relax bro [SEPA] i am noob      0          1
35670                   free mmr [SEPA] fuck that 37 mmr      0          1
950                                gg [SEPA] fuck dota 2      0          1
15519   im doing my best [SEPA] shit still happen always      0          1
1867                  come on man [SEPA] fuck you rubick      0          1
33563  HAHAHA [SEPA] this fucking pc [SEPA] restarted...      0          1
21735                                     you are a joke      0          1
14580                       Game was good [SEPA] sf noob      0          1
26805  we lost i cant move properly [SEPA] suddenly 1...      0          1
3734                        always escape the fuck ahaha      0          1
1421                      reKT [SEPA] AA [SEPA] doG SHIT      0          1
25369          are you stupid troll?waiting for nothing?      0          1
16691  lc says he's coming [SEPA] you fuck [SEPA] why...      0          1
503                                             NOB TEAM      0          1
23600                      FUck you BB  [SEPA] feeder BB      0          1
27004  coz team comes noob [SEPA] and only thing left...      0          1
14912  Sf said if lose he quit dota [SEPA] fucking wp...      0          1
25650   hahahaha [SEPA] i know [SEPA] hes noob [SEPA] XD      0          1
32648  COME THE FUCK ON [SEPA] ARE YOU JUST FOLLOWING...      0          1
9529                tghrowers [SEPA] ahahaha [SEPA] fuck      0          1
19665     again haste? [SEPA] ogre noob, but lucky day )      0          1
19513  fuck [SEPA] he is streaming on twitch [SEPA] w...      0          1
15236  AHHHH [SEPA] 274 win on invoker  [SEPA] ihave ...      0          1
13044                5 bkbs holy shit [SEPA] try is hard      0          1
3713                                          THATS DUMB      0          1
34177            pls finish [SEPA] its hard with 3 idiot      0          1
7900                                 ur arms are shaking      0          1
2212                                                 Fck      0          1
361                                                  fck      0          1
16297                                         damn pinoy      0          1
2249   youre score its like pi [SEPA] defending your ...      0          1
17424            holy shit [SEPA] they r not coming back      0          1
10672                       for mother russia! [SEPA] :D      0          1
9495                                        .. [SEPA] Fu      0          1
23968  i can beat any of you lil shits 1 v 1, but my ...      0          1
34962              bkb [SEPA] haha [SEPA] stupid players      0          1
4977                                 so long [SEPA] fuck      0          1

       confidence
25633    0.999984
30173    0.999984
5070     0.999983
5468     0.999946
17515    0.999894
10033    0.999589
34458    0.999495
28437    0.999052
27120    0.999052
22689    0.999052
26573    0.999052
10860    0.998717
11194    0.998717
13149    0.998717
8073     0.998717
19774    0.998135
19168    0.998135
16395    0.998135
5576     0.997891
34508    0.996867
2791     0.996295
10594    0.994496
29950    0.990886
9797     0.975584
2232     0.974480
28640    0.970857
33542    0.968062
6117     0.959584
18245    0.956753
17272    0.951231
18545    0.949279
15429    0.949081
18596    0.941373
21116    0.934628
16796    0.923212
28670    0.919823
24344    0.917938
23300    0.914988
17807    0.914310
8640     0.909744
1830     0.908424
25875    0.908149
34585    0.903886
28084    0.899859
23823    0.896158
11669    0.889875
30670    0.888959
23117    0.888671
26680    0.888671
9699     0.883489
8635     0.880905
8653     0.880322
22441    0.873154
25021    0.859366
3988     0.859302
16007    0.856871
26129    0.856364
29822    0.852065
32634    0.848930
21838    0.848919
1502     0.847285
16816    0.843360
24145    0.842373
5014     0.835050
17159    0.833007
28304    0.831921
23936    0.829001
16199    0.817484
31943    0.814636
1033     0.806362
18606    0.796943
12739    0.793673
26955    0.791167
27019    0.788948
6050     0.786993
27620    0.780312
32622    0.778295
34172    0.775296
32967    0.773060
8588     0.765842
28320    0.761816
32508    0.760653
14876    0.752696
29516    0.751442
26745    0.748830
29273    0.738132
331      0.728111
33469    0.723426
11074    0.721404
17522    0.718062
23598    0.716728
32506    0.712396
8294     0.709954
4740     0.709239
10374    0.709131
35670    0.703388
950      0.699247
15519    0.698419
1867     0.697537
33563    0.690489
21735    0.686496
14580    0.685249
26805    0.681006
3734     0.680501
1421     0.679383
25369    0.677611
16691    0.677378
503      0.667204
23600    0.666557
27004    0.663778
14912    0.657835
25650    0.654051
32648    0.651880
9529     0.650990
19665    0.649810
19513    0.647913
15236    0.647856
13044    0.644983
3713     0.641787
34177    0.636237
7900     0.632961
2212     0.622413
361      0.622413
16297    0.615295
2249     0.614134
17424    0.611247
10672    0.610482
9495     0.606094
23968    0.602687
34962    0.601988
4977     0.600796

Let's drop those

In [27]:
# drop mislabelling 
dota_en = dota_en[~non_toxic_mislabeled_d].reset_index(drop=True)
print(f"Length after update: {dota_en.shape[0]}")

Length after update: 35691

#### Final verification

In [28]:
print("=== Shape ===")
print(dota_en.shape)

print("=== Nulls ===")
print(dota_en.isnull().sum())

print("=== Duplicate messages ===")
print(dota_en.duplicated(subset="message").sum())

print("=== Label distribution ===")
counts = dota_en["label"].value_counts().sort_index()
pct = dota_en["label"].value_counts(normalize=True).sort_index().mul(100).round(1)
label_names = {0: "Other (O)", 1: "Ego (E)", 2: "Aggression (A)", 3: "Impolite (I)"}
print(pd.DataFrame({"count": counts, "pct%": pct}).rename(index=label_names))

=== Shape ===
(35691, 4)
=== Nulls ===
index      0
message    0
label      0
split      0
dtype: int64
=== Duplicate messages ===
11051
=== Label distribution ===
                count  pct%
label
Other (O)       26424  74.0
Ego (E)          4703  13.2
Aggression (A)   2292   6.4
Impolite (I)     2272   6.4

No null values after dropping 8 empty utterances. Duplicates exist but will be explored in EDA - short gaming phrases like "gg" appear frequently across matches and are expected repeats, not data errors. Label distribution mirrors WoT: heavy skew toward non-toxic (O), with Ego, Aggression, and Impolite as minority classes. Save to parquet.

In [29]:
# save cleaned dota to parquet for easier loading in future steps
dota_en.to_parquet(PROJECT_ROOT / "data/processed_data/dota/dota.parquet", index=False)